### ISSUE TITLE
Direct integration with Forge modules

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#1]
r10k relies on having the puppet module tool available to interact with modules installed from the forge. This adds an external dependency and means that required fixes like module permissions have to be handled through that external tool. It would be a Nice Thing (TM) if r10k directly managed these modules instead of shelling out.

**Comment by abohne** [comment]
+1

**Comment by mlg9000** [comment]
+1

**Comment by adrienthebo** [comment]
This was resolved in upstream in the module tool in commit https://github.com/puppetlabs/puppet/commit/fe7b9f0e0376cd17f12d4512f2cbf4519b3aa1ef , so it shouldn't be a problem with Puppet version 3.2.4 and later. However it be better to have some sort of direct integration the Forge, so that we're not directly dependent on having the right version of Puppet. I'm going to repurpose this ticket into a general issue for better forge integration.

**Comment by adrienthebo** [comment]
Implemented in fd6c712 and related commits.
