### ISSUE TITLE
Dependency resolver

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/r10k#1031]
@glennsarti has written a [dependency resolver](https://github.com/lingua-pupuli/puppetfile-resolver/) for the `Puppetfile`. We should consider using it in r10k itself.

See #38 and #305

**Comment by op-ct** [comment]
Also see @rnelson0's summary of the "significant issues" with automated dependency resolving in https://github.com/puppetlabs/r10k/issues/621#issuecomment-334486864.

If dependency resolution is added to r10k, I would prefer it to be opt-in rather than enabled by default.

**Comment by nmaludy** [comment]
Idea: could do something like a `Puppetfile` and `Puppetfile.lock`, similar to Gemfiles in Ruby. Then your Puppetfile could be your main dependencies and your Puppetfile.lock could be your resolved dependencies. Could also allow for resolution and locking on the client side with the same tooling.

**Comment by op-ct** [comment]
> Idea: could do something like a `Puppetfile` and `Puppetfile.lock`, similar to Gemfiles in Ruby. Then your Puppetfile could be your main dependencies and your Puppetfile.lock could be your resolved dependencies. Could also allow for resolution and locking on the client side with the same tooling.

[librarian-puppet](https://github.com/voxpupuli/librarian-puppet#how-to-use) used `Puppetfile.lock` files to save resolved deps like this.
