### ISSUE TITLE
Stand up Jekyll microsite with docs section

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/r10k#1035]
- [ ] Stand up a starter Jekyll microsite
- [ ] Minor theming, maybe some branding
- [ ] Use existing docs to create docs framework
- [ ] Flesh out docs a little bit for continuity
- [ ] Identify community writers interested in participating

**Comment by logicminds** [comment]
Use  hugo and netlify better as it auto deploys.

https://gohugo.io/hosting-and-deployment/hosting-on-netlify/
