### ISSUE TITLE
Deploy module doesn't sync its environment

### ISSUE THREAD

**Issue by isqo** [puppetlabs/r10k#1040]
## Describe the Bug
When the git reference of a module changes in the Puppet file, the deploy module command doesn't deploy it, it deploys its previous git revision.

## Expected Behavior
If the Puppet file changes, The deploy module command should adapt to the update, it should use the new git reference.

## Steps to Reproduce
1. Create a Puppet file with the Concat module in branch production of a control-repo
`
mod 'concat',
  git:    'https://github.com/isqo/puppetlabs-concat.git',
  branch: 'master'
`

2. You should deploy the environment first
`
 /opt/puppetlabs/puppet/bin/r10k deploy environment production -v
`
3. Update the branch of concat.
`
mod 'concat',
  git:    'https://github.com/isqo/puppetlabs-concat.git',
  branch: '1.0.x'
`
4.  Try to deploy only the module and not the entire environment
`
 r10k deploy module concat -e production -v
`
5.  The module doesn't change

## Additional Context
In an environment in which deployments are frequent and puppetfile changes a lot, being constrained to deploy the entire environment each time isn't productive. deploy environment of a large puppet file may take 5 minutes while deploying modules individually takes a lot less (sometimes few seconds).

**Comment by Magisus** [comment]
As a workaround, you should be able to run `r10k deploy environment <env_name>` _without` the `-p` and avoid actually deploying the modules. That command will fetch the updated puppetfile (and anything outside of modules that changed in the environment), but not actually deploy any modules. You can then follow up with the single module deploy.

**Comment by adrienthebo** [comment]
`r10k deploy module <module>` should only deploy that given module, and not touch the environment itself. That said I can see us providing something like the following:

```
r10k deploy environment --puppetfile --only-modules module1,module2,module3
```

Would that work for your use case, @isqo ?

**Comment by isqo** [comment]
Hello guys thanks for the workaround and quick responses, @adrienthebo yes, i think it's a good feature and will work for my use case (btw, i'd like to work on it as an open source hobbyist :) ), otherwise, what about providing a sync-env flag to the deploy module command that sync the environment before deploying modules when passed. I implemented it quickly on my fork in  https://github.com/isqo/r10k/commit/92c1c39246cfacf21795c24d34a22d01b896a54a, what's wrong about it ?

**Comment by isqo** [comment]
Hello, i also worked on the --only-modules option, which solution is good for the use case ? pull request ?
