### ISSUE TITLE
R10k should use %LOCALAPPDATA% for Windows cachedir

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/r10k#1049]
When run on Windows, r10k's default cachedir setting is `~/.r10k`. This can be problematic when used with roaming profiles, in the event the HOME environment variable on Windows points to a network drive that is unavailable.

![win-r10k-cachedir-error](https://user-images.githubusercontent.com/100142/80422653-6c7e2d80-8893-11ea-8319-1365f5e2d0ae.jpg)

In general, it's not good practice to rely on HOME for this kind of thing on Windows. We should ensure that when puppetfile install is invoked on Windows it uses LOCALAPPDATA, instead of HOME, for the cachedir.

Issued ported from https://tickets.puppetlabs.com/browse/RK-347

**Comment by hegyre** [comment]
Hi guys,

I've having same issue here.

It would be better to use USERPROFILE env variable.
See https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables

Is there any way to manually tells r10k to use a specific cachedir ?

Edit: you can just update HOME env variable to fix that.
Example with PowerShell:
```$Env:HOME = "$Env:USERPROFILE"```

**Comment by kreeuwijk** [comment]
When is this issue finally getting fixed?

**Comment by Magisus** [comment]
For reference, the default comes from here https://github.com/puppetlabs/r10k/blob/103d3eebb6aac45c89a31063c7355ce6bf63eb6a/lib/r10k/git/cache.rb#L19

I'm working on getting a priority on this for when we might be able to work on this internally. PRs are also welcome if someone familiar with windows directory APIs wants to give it a shot 🙂

**Comment by joshcooper** [comment]
Note the file expansion of `~` to a directory is really a ruby thing, not specific to r10k, and you can see how ruby prefers [`HOME` -> `HOMEDRIVE/HOMEPATH` -> `USERPROFILE`]( https://github.com/ruby/ruby/blob/d1ba5545513b68d39ca29b578a42bd8d48a7804e/win32/win32.c#L548-L562). Using `ENV['USERPROFILE']` should be easy enough on Windows, so hopefully you shouldn't need to call Win32 API.

**Comment by mwaggett** [comment]
resolved by https://github.com/puppetlabs/r10k/pull/1099
