### ISSUE TITLE
use logging instead of legacy log4r dependency?

### ISSUE THREAD

**Issue by mwaggett** [puppetlabs/r10k#1053]
Copied from https://tickets.puppetlabs.com/browse/RK-359

Hi people!
I'm still digging through all the puppet/r10k/bolt/pdk dependencies. Sorry for all the issues!

I noticed that r10k pulls in log4r. This gem basically seems dead. The links to the repo at rubygems.org are dead. I was unable to find a proper repository for it. Also it has no license which should be pretty critical?

At the bolt project was a similar discussion: https://tickets.puppetlabs.com/browse/BOLT-268

Would you consider switching to an alternative to log4r?

CC: @binford2k @DavidS , we talked about this some days ago

**Comment by mwaggett** [comment]
cc @bastelfreak

**Comment by bastelfreak** [comment]
hey people. any chance to get some progress here? I think relying on a dead gem could be considered as a security risk. Also that makes it basically impossible to create proper packages. I need to build log4r from source and there is no source code available :(

**Comment by mwaggett** [comment]
hey @bastelfreak, thanks for filing this issue. We agree that this is an improvement, but due to other issues demanding precedence, we don’t anticipate being able to address this any time soon. If you are interested in submitting a patch, please open a pull request referencing this issue.

**Comment by bastelfreak** [comment]
I wanted to try this on my own, but the referenced bolt issue is gone or has changed permissions:

![2020-10-28-133344_525x189_scrot](https://user-images.githubusercontent.com/341866/97436410-427cf500-1922-11eb-8acc-b62b08650604.png)

I will see if I find something helpful in their codebase

**Comment by mwaggett** [comment]
@bastelfreak here is the associated Bolt PR: https://github.com/puppetlabs/bolt/pull/244

**Comment by bastelfreak** [comment]
hey,
I did some digging through the bolt PR but  I don't understand enough Ruby to port this to r10k. To me it's unclear which license is assigned to log4r. I could not find any information about it in the gem itself. As a conclusion I'm not sure if I can use r10k (nor anybody else). It would be nice if Puppet could increase the priority here slightly.

**Comment by mwaggett** [comment]
@npwalker putting this on your radar for prioritization
