### ISSUE TITLE
R10k Does not clean up tmp directories when downloading forge modules

### ISSUE THREAD

**Issue by mwaggett** [puppetlabs/r10k#1054]
Copied from: https://tickets.puppetlabs.com/browse/RK-339

When R10k deploys forge modules, it does not fully clean up the temp directories it creates. This only occurs when we run r10k on a new puppet environment.With our setup , this grows fairly quickly and could exhaust the server inodes.    

Example:

When r10k runs it create a directory /tmp/d$DATE. Within this directory it creates sub directories and after the deployment is complete it cleans up the sub directories but leave the root directory /tmp/d$DATE.

Affects Versions: r10k 3.0.0

**Comment by corporate-gadfly** [comment]
> 
> When R10k deploys forge modules, it does not fully clean up the temp directories it creates. This only occurs when we run r10k on a new puppet environment.With our setup , this grows fairly quickly and could exhaust the server inodes.
> 

In my experience, it happens on every run of `r10k` _(not just for new environments)_. I cannot implement a webhook, so in my case the there is a cron job which runs every 10 minutes. Two empty directories get left in `/tmp` every 10 minutes.

**Comment by corporate-gadfly** [comment]
`rspec` fails because of incorrect expectations, but my problem is solved with this patch:
```diff
diff --git a/lib/r10k/forge/module_release.rb b/lib/r10k/forge/module_release.rb
index 588678f..01b17eb 100644
--- a/lib/r10k/forge/module_release.rb
+++ b/lib/r10k/forge/module_release.rb
@@ -212,14 +212,14 @@ module R10K
 
       # Remove the temporary directory used for unpacking the module.
       def cleanup_unpack_path
-        if unpack_path.exist?
+        if unpack_path.parent.directory?
           unpack_path.parent.rmtree
         end
       end
 
       # Remove the downloaded module release.
       def cleanup_download_path
-        if download_path.exist?
+        if download_path.parent.directory?
           download_path.parent.rmtree
         end
       end
```
I am a newbie with ruby, so take it with a grain of salt.
`r10k` is version `3.5.0`. And gems:
```bash
/opt/puppetlabs/puppet/bin/gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6.2
  - RUBY VERSION: 2.5.8 (2020-03-31 patchlevel 224) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /opt/puppetlabs/puppet/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/puppetlabs/puppet/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/puppetlabs/puppet/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0
     - /root/.gem/ruby/2.5.0
     - /opt/puppetlabs/puppet/lib/ruby/vendor_gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /opt/puppetlabs/bin
     - /root/bin
```
and on `CentOS Linux release 8.1.1911 (Core)`.

**Comment by mwaggett** [comment]
resolved by https://github.com/puppetlabs/r10k/pull/1072
