### ISSUE TITLE
Git cache breaks with pool_size > 1 if managing the same git source twice

### ISSUE THREAD

**Issue by Magisus** [puppetlabs/r10k#1058]
A bug recently surfaced in our beaker acceptance tests, that seems valid, but might not be a common workflow. It appeared after the merge of https://github.com/puppetlabs/r10k/pull/1044, updating the default pool size to 4.

If you are managing two objects (in this case non-module objects) backed by the same git repo, and are using a `pool_size` of more than 1, the caching mechanism for git behaves poorly on the initial deploy.

**Puppetfile**
```
mod 'non_module_object_1',
  :install_path => './',
  :git => 'git://github.com/puppetlabs/control-repo.git',
  :branch => 'production'
mod 'non_module_object_2',
 :install_path => '',
 :git => 'git://github.com/puppetlabs/control-repo.git',
 :branch => 'production'
```
 
**Error output** at `--verbose=debug2` from `r10k deploy environment -p`:
```
[2020-04-30 22:28:15 - INFO] Deploying Puppetfile content /etc/puppetlabs/code/environments/production/non_module_object_1
[2020-04-30 22:28:15 - DEBUG1] Creating new git cache for "git://github.com/puppetlabs/control-repo.git"
[2020-04-30 22:28:15 - DEBUG] Module thread 23963080 exiting: queue empty
[2020-04-30 22:28:15 - DEBUG2] Starting process: ["git", "clone", "--mirror", "git://github.com/puppetlabs/control-repo.git", "/var/cache/r10k/git---github.com-puppetlabs-control-repo.git"]
[2020-04-30 22:28:15 - INFO] Deploying Puppetfile content /etc/puppetlabs/code/environments/production/non_module_object_2
[2020-04-30 22:28:15 - DEBUG1] Creating new git cache for "git://github.com/puppetlabs/control-repo.git"
[2020-04-30 22:28:15 - DEBUG2] Starting process: ["git", "clone", "--mirror", "git://github.com/puppetlabs/control-repo.git", "/var/cache/r10k/git---github.com-puppetlabs-control-repo.git"]
[2020-04-30 22:28:15 - DEBUG] Module thread 23579460 exiting: queue empty
[2020-04-30 22:28:15 - DEBUG2] Finished process:
Command: git clone --mirror git://github.com/puppetlabs/control-repo.git /var/cache/r10k/git---github.com-puppetlabs-control-repo.git
Stderr:
fatal: destination path '/var/cache/r10k/git---github.com-puppetlabs-control-repo.git' already exists and is not an empty directory.
Exit code: 128
[2020-04-30 22:28:15 - ERROR] Command exited with non-zero exit code:
Command: git clone --mirror git://github.com/puppetlabs/control-repo.git /var/cache/r10k/git---github.com-puppetlabs-control-repo.git
Stderr:
fatal: destination path '/var/cache/r10k/git---github.com-puppetlabs-control-repo.git' already exists and is not an empty directory.
Exit code: 128
```

I think this occurs because two threads kick off to deploy the entries in the puppetfile and both try to cache the new repo simultaneously, so the second clone fails because its path isn't clear -- the directory was populated between when it decided it needed to clone and when the clone actually completed. Subsequent deploys work fine, because the cache is already populated.

This reproduced very reliably. We're updating our tests for now to no longer have two resources with the same backing repo for the time being, since we think that isn't terribly valid. Seeing as no one has hit this yet, it seems uncommon at least.

**Comment by justinstoller** [comment]
@adrienthebo , @dhollinger , @reidmv , @bastelfreak , @binford2k , @npwalker  I'm super curious to see if any of you have concerns about how often the above situation might be encountered.

**Comment by bastelfreak** [comment]
Hi,
sounds like an interesting usecase, I haven't seen that in the wild. But my assumption is that it's a valid one and that it should work.

**Comment by npwalker** [comment]
While it might currently work, I'm not sure it makes a lot of sense.  I'd be fine failing if we can detect that two modules use the same git source.  

if it's easy enough we could downgrade to a pool_size of 1 instead of failing.  

Or depending on the work compared to the above we could try to make the caching code safe from two threads trying to both cache the same git source twice.

Or if we can detect the same git source twice we could just dedupe so we never try to download the same git source twice?  

Lots of options but given the low likelihood of someone trying to do this I'd be fine failing and saying the user needs to set pool_size to 1

**Comment by binford2k** [comment]
I don't see the benefit of duplicate git sources. But it also seems relatively easy to detect. At that point you could either dedupe or just downgrade pool_size to 1 (with a warning).

**Comment by Magisus** [comment]
We're going to look into a real fix this afternoon, because if it's relatively straightforward, the best option is obviously just to fix it.

**Comment by justinstoller** [comment]
I've opened https://github.com/puppetlabs/r10k/pull/1059 with an approach to fixing this instead of warning. For those of you I pinged that review code I'd welcome any comments wrt the approach and unit tests. I still need to update an acceptance test and changelog but I think it's functionally correct.
