### ISSUE TITLE
Implement the 'forge' Puppetfile configuration directive

### ISSUE THREAD

**Issue by thias** [puppetlabs/r10k#106]
The current README mentions it's a noop. In situations where there is no Internet access whatsoever, it's really useful to be able to use a local forge.

(note that I've searched existing issues, but found none to track this)

**Comment by thias** [comment]
Just a quick note : I saw that the protocol isn't included in the current example, and that https is hardcoded in parts of the code. I think it'll be required to move the protocol to be part of the "forge" value from the Puppetfile, in order to be able to use plain http.

Looking at librarian-puppet, it seems like the protocol is part of the setting, so it would be the same. They have `forge "http://forge.puppetlabs.com"` in their example file.

**Comment by walidshaari** [comment]
In our workplace, we too have the situation of disconnected and came to this issue in hope to see what possible options are in R10k for local modules, or forge. or  what the forge directive can point to locally if not the official puppet forge. (e.g.  local repo served by http, nfs from previously downloaded modules.)

**Comment by scotje** [comment]
I'm going to go ahead and close this issue. There is now a Forge `baseurl` setting in r10k.yaml (https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#baseurl) which I think makes a lot more sense than controlling this on a per-environment basis in the Puppetfile.

`forge` directives in the Puppetfile will likely be deprecated in a future version of r10k, not that they ever did anything. :)
