### ISSUE TITLE
postrun per-environment

### ISSUE THREAD

**Issue by mwaggett** [puppetlabs/r10k#1068]
Copied from https://tickets.puppetlabs.com/browse/RK-329

I'd like to be able to have a script run after each dynamic environment is deployed, so I can run things like "puppet generate types --environment whatever" as part of "r10k deploy environment -p".

There's a postrun script but I think it's run once per execution, not per environment, and doesn't receive information about the updated environment(s), at least as far as I know.

**Comment by mwaggett** [comment]
cc @MikaelSmith

**Comment by alexjfisher** [comment]
I think https://github.com/puppetlabs/r10k/pull/836 addressed this.

**Comment by mwaggett** [comment]
ah yeah, this appears to duplicate https://github.com/puppetlabs/r10k/issues/697
