### ISSUE TITLE
Quickstart is out of date

### ISSUE THREAD

**Issue by dantman** [puppetlabs/r10k#1088]
The [Quickstart](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/quickstart.mkd) instructs users to use `hieradata/common.yaml` and `hiera_include('classes')`.

This results in a hiera 3 setup with deprecation warnings.

**Comment by binford2k** [comment]
oof, this is really out of date. Thanks for flagging it @dantman!

**Comment by akomakom** [comment]
What is the correct way to set up r10k in this regard?  Following the quickstart, I see:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Function lookup() did not find a value for the name 'classes'`
