### ISSUE TITLE
r10k will always complain if no Puppetfile is present

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#11]
Given a repo with no Puppetfile, it will warn with the following:

<pre>
[R10K::Root - WARN] #<R10K::Root:0x00000000dd9578>:/etc/puppet/environments/master does not exist, cannot enumerate modules.
</pre>

If the directory does exist but the Puppetfile doesn't, then maybe a debug message should be logged but a warning shouldn't be thrown.

**Comment by vexilar** [comment]
I believe this is actually caused by lack of a site folder in the module

**Comment by vexilar** [comment]
i basically (a) created an empty repo with a dummy text file (b) saw the error (c) added the Puppetfile (d) saw the error (e) added the site folder (f) no longer saw the error.

**Comment by adrienthebo** [comment]
I'm catching up on triage for r10k; I'll try to investigate this more closely in the next few days and get a fix out.

**Comment by adrienthebo** [comment]
Released in 1.0.0rc1.
