### ISSUE TITLE
r10k assumes master branch when no :ref is set, breaks when master is not default branch

### ISSUE THREAD

**Issue by natewalck** [puppetlabs/r10k#110]
When you have a repo configured without a :ref in the Puppetfile which uses something other than 'master' as the default branch, r10k tries to check out the master branch and throws this error:

`[R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7f49b4f30110> failed while running: Cannot check out unresolvable ref 'master' at /etc/puppet/environments/production/modules/some_module`

Ideally, r10k would pull the default branch rather than pulling master explicitly.

**Comment by adrienthebo** [comment]
After poking around inside of Git internals I realized that this could be easily resolved by invoking `git symbolic-ref HEAD` to determine the correct branch to use. This may make it into r10k 1.5.0 depending on how it interacts with other integrations, and it'll need to be behind a feature flag.

**Comment by scotje** [comment]
I have created the JIRA ticket RK-215 to track this issue: https://tickets.puppetlabs.com/browse/RK-215
