### ISSUE TITLE
allow r10k to deploy with an arbitrary ssh key

### ISSUE THREAD

**Issue by tvpartytonight** [puppetlabs/r10k#1109]
## Use Case
Currently, ssh credentials are configured in the r10k.yaml and use for authentication; it would also be useful to specify a key per deploy, so that r10k doesn't require having the key written to disk.
 
## Describe the Solution You Would Like
R10k accepts a deploy arg/env-var for the ssh key used.

This is similar to #1106.

**Comment by Magisus** [comment]
If we decide to implement this for the shellgit provider, here's a post describing how you can pass SSH keys to `git clone` without messing with the system SSH config: https://stackoverflow.com/questions/6688655/select-private-key-to-use-with-git/41947805#41947805

**Comment by Magisus** [comment]
If we decide to implement this for the shellgit provider, here is a post about how SSH keys can be passed directly to git operations without editing the system SSH config: https://stackoverflow.com/questions/6688655/select-private-key-to-use-with-git/41947805#41947805

**Comment by mwaggett** [comment]
resolved by https://github.com/puppetlabs/r10k/pull/1116
