### ISSUE TITLE
Error updating r10k to v. 3.7.0 on Centos 7: "cri requires Ruby version >= 2.5."

### ISSUE THREAD

**Issue by gdubicki** [puppetlabs/r10k#1121]
## Describe the Bug

```
[root@puppetmaster:~]# /opt/puppetlabs/puppet/bin/gem install -v 3.7.0 r10k
ERROR:  Error installing r10k:
        cri requires Ruby version >= 2.5.
```

## Expected Behavior

It should update.

## Steps to Reproduce

1. Have r10k 3.3.1 and cri ﻿2.6.1.
2. Run `/opt/puppetlabs/puppet/bin/gem install -v 3.7.0 r10k`

## Environment

Puppet: 5.5.22
```
/opt/puppetlabs/puppet/bin/ruby --version
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]
```
CentOS Linux release 7.5.1804 (Core)

## Additional Context

I did work around this with updating cri to 2.15.6 first and then updating r10k.

But the same r10k update worked on our test puppetmaster in December without such workarounds.

I guess that r10k doesn't pin the cri package version so when updating it tries to install the latest cri which is incompatible with ruby 2.4 bundled with Puppet 5.5. I suppose that pinning the cri version should help.

**Comment by mwaggett** [comment]
Hi @gdubicki, thanks for opening this issue! It looks like cri dropped support for old versions of Ruby in a Z release in December.. 😒

The current version of r10k allows using cri 2.15.10, which is the last version to support the old Ruby versions, so you should be able to continue using it.

I will look into getting this fixed, but we plan to drop support for Ruby < 2.5 in our next major release.

**Comment by mwaggett** [comment]
Fixed by https://github.com/puppetlabs/r10k/pull/1135
