### ISSUE TITLE
Revise mismatched version logic/add logging

### ISSUE THREAD

**Issue by cedws** [puppetlabs/r10k#1129]
We looked into an issue today in production where some catalogs were failing to compile due to errors in module code.
After some digging, we found that our periodic r10k deploy job was reinstalling specific modules on every run.

The offending code is here:
https://github.com/puppetlabs/r10k/blob/c6fac31a7f55d6e5e26c380f0571b4af9072d92c/lib/r10k/module/forge.rb#L120-L124

A Forge module being reinstalled on every run happened to have a `.git` directory - we've since upgraded that module to a version that doesn't have the directory anymore.

I'm not sure why it was decided that r10k should reinstall modules that contain a `.git` directory but this should at least be logged. In fact, this whole class could do with a bit more logging.

**Comment by cedws** [comment]
What a utopia we'd be living in if problems went away by themselves.

**Comment by Magisus** [comment]
@justinstoller is this something that your work around using module version pins to assume that modules haven't changed will also fix?

**Comment by justinstoller** [comment]
No, this is unrelated to the changes I'm working on.

The rationale/workflow for that behavior is discussed here: https://github.com/puppetlabs/r10k/pull/411

I agree the class should have more logging, especially in its state resolution.

**Comment by mwaggett** [comment]
hey @cedws do you have any interest in opening a pull request to add the logging you feel is missing? We're happy to help you with it if you need!

**Comment by cedws** [comment]
Yes. But no guarantees on when I can get to it.

**Comment by mwaggett** [comment]
awesome @cedws, no rush! Since this ticket is more about the `.git` behavior, which is intentional, I'm going to close this ticket, but feel free to open a PR to add logging, or open a new issue about logging specifically. Thanks!
