### ISSUE TITLE
puppet 3.5 changes the way modulepath is loaded

### ISSUE THREAD

**Issue by kennyg** [puppetlabs/r10k#113]
puppet 3.5 changes the way modulepath is loaded. can you update the instructions with respect to internal modules and puppetfile module paths?

**Comment by adrienthebo** [comment]
Is this with respect to directory environments and the `modulepath` and `environmentpath` settings? If so the existing `modulepath` examples should continue to work for Puppet 3.x, although the documentation will need to updated in the longer term, anywho.

**Comment by rnelson0** [comment]
I'm terribad at Github apparently, I don't know how to attach a PR to an existing issue. Nevertheless, I've updated the documentation based on the Puppetlabs documentation and my findings (http://rnelson0.com/2014/06/05/puppet-3-6-1-updates/). I don't know how to resolve the second modulepath value of $environments/dist, however, so perhaps the PR needs some tweaking.

**Comment by 3flex** [comment]
Hi @rnelson0 you can't directly attach a PR to an issue as far as I'm aware (you have to have a new PR in addition to the original issue), but you can reference the issue by either having a commit reference the issue number or mentioning (as you did) in the PR description.

To automatically close the issue when the PR is merged see https://help.github.com/articles/closing-issues-via-commit-messages. I think that would have been appropriate in this case, and if the maintainer disagrees they'd note that before merging.

@kennyg did @rnelson0's change address your issue? You could consider closing it.

**Comment by adrienthebo** [comment]
Modulepath documentation is now available at https://github.com/adrienthebo/r10k/blob/master/doc/dynamic-environments/master-configuration.mkd.
