### ISSUE TITLE
File permissions on files from Git

### ISSUE THREAD

**Issue by ChrisPortman** [puppetlabs/r10k#114]
Hi All,

Occasionally when I do a `r10k deploy environment -p`, the modules update from git but the file permissions go a little wild and then puppet runs fail because of it.  I end up just having to `chmod -R a+r /top/level/module/path`.  Does anyone else get this, is there a reason for it, way to make it stop?

Let me know if I can provide any more info...

Thanks,
Chris

**Comment by adrienthebo** [comment]
What umask is set with the user that's running puppet?

**Comment by adrienthebo** [comment]
Errn r10k rather.

**Comment by ChrisPortman** [comment]
I run it as root (both from the cmd line and root's crontab) and the umask is 0022.  Its REALLY inconsistent though.

**Comment by adrienthebo** [comment]
Are the same modules affected or is there no discernible pattern? How are
you seeing this error occur?

**Comment by ChrisPortman** [comment]
At the moment, i cant see any patterns.  I dont notice it until puppet bails because it cant find a class.  Usually the permissions on the offending file are 0640

**Comment by adrienthebo** [comment]
@ChrisPortman could you strip down an environment to have a single git module specified in the Puppetfile, and attempt to reproduce from that? If that doesn't trigger it then try re-adding modules till there's a single point where the errors start occurring.

**Comment by adrienthebo** [comment]
This issue hasn't seen an update in a few weeks; are you still seeing problems with this?

**Comment by ChrisPortman** [comment]
Hi Adrien,

Sorry for tje lack of feed back. I've been trying to nail down the issue with little luck. However I'm thinking its actually an issue with git on RHEL rather than r10k. I'm seeing similar behaviour from the Vcsrepo module as well.

Thanks,
Chris

<div>-------- Original message --------</div><div>From: Adrien Thebo notifications@github.com </div><div>Date:03/05/2014  08:14  (GMT+10:00) </div><div>To: adrienthebo/r10k r10k@noreply.github.com </div><div>Cc: ChrisPortman chris@portman.net.au </div><div>Subject: Re: [r10k] File permissions on files from Git (#114) </div><div>
</div>This issue hasn't seen an update in a few weeks; are you still seeing problems with this?

**Comment by adrienthebo** [comment]
Thanks for the update, I'm trying to keep closer tabs of reported issues so that I don't let issue reports go stale. Please let me know what the outcome of your investigations are, in case it means there needs to be work done on the r10k front.

**Comment by adrienthebo** [comment]
Because I can't reproduce this and it looks like it may be an issue with Git rather than r10k itself, I'm closing this issue out. If this issue persists please comment on this issue and I can reopen it.
