### ISSUE TITLE
git silently fails on `git fetch --prune` of the control repo cache

### ISSUE THREAD

**Issue by dhgwilliam** [puppetlabs/r10k#115]
Occasionally I get this error:

```
R10K::TaskRunner - ERROR] Task #<R10K::Task::Deployment::DeployEnvironments:0x0000000275a0b0> failed while running: "git --git-dir /var/cache/r10k/-vagrant fetch --prune" returned with non-zero exit value 1
```

where `/vagrant` is the r10k remote. After a bit of looking, it seems that all `git fetch` related commands have an exit code of 1 once this stage is reached.

**Comment by dhgwilliam** [comment]
I should add that this error is received upon running `r10k deploy env -p`

**Comment by adrienthebo** [comment]
The exit code from git commands are entirely meaningless unfortunately, so r10k does need to report more information when errors happen. This issue looks like it's a duplicate of GH-96 so I'm going to close this issue in favor of the older issue; if this is in error please let me know and I can reopen it.
