### ISSUE TITLE
postrun script gets called with environments that weren't updated.

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/r10k#1215]
## Describe the Bug
3.11.0 contained https://github.com/puppetlabs/r10k/pull/1190
With this change, the postrun command is run after using `r10k deploy module`.

Unfortunately, the script is not called with only the environments that were updated, but with all environments that contain the module (even if they weren't updated).

## Expected Behavior
The postrun `$modifiedenvs` variable to only include environments that were actually modified.

## Steps to Reproduce

This can probably be reproduced in lots of way, but in my environment, I have a Puppetfile containing in house modules configured a bit like...
```ruby
mod 'somemod',  :git => 'ssh://git@git.example.com:7999/pupmod/somemod.git',
                :branch => :control_branch,
                :default_branch => 'main'
```

Most of the time, a module won't have many branches (possibly just the main branch), but there will be lots of control repo branches (with developers working on separate work, mainly editing profiles/hiera etc.).  Those environments will all be using `main` branch for these modules.

If you need to modify a module, you create a branch in the module repo with a branch name matching the control repo branch/puppet environment you're working on.

Pushing such a branch runs `r10k deploy module` for that module and *only* the matching control-repo branch/environment will actually get updated. But since 3.11.0 postrun (and possibly `generate types`) is then being run with *all* environments.  This is painfully slow when you have lots of environments (in my case ~150 as of today).

**Comment by Magisus** [comment]
Thanks for filing this, I think [this logic](https://github.com/puppetlabs/r10k/blob/66c3bb825b6ef6ebbd90846e8a26f826467c6909/lib/r10k/action/deploy/module.rb#L109-L117) is probably at fault, I know I didn't test with `control_branch`. I'll take a look.

**Comment by Magisus** [comment]
Just to clarify, you're running `r10k deploy module` without specifying any environments, right?

So what's happening is that r10k is _trying_ to update the module for all environments. At the moment, it doesn't care (and doesn't have a good way to tell) whether the module sync actually _did_ anything. And in fact, if the `main` branch of the module had changed, it _would_ do something, even for environments that don't match the new branch name, as a side effect of this workflow. It sounds like in your case that probably would never be the case, but that's out of discipline/automation, and not something general that can be guaranteed.

I agree this is bad. Fixing it properly is likely to be a somewhat involved. I think to do it right, each module implementation would need to return the result of its `sync` function ("synced" or "didn't sync"), and the collected sum of those would need to be plumbed through to this action, to decide whether to run the command or not for each environment. I'll poke at it today to see what that might look like.

Is there a way for you to avoid the slowdown (e.g. is it feasible for you to disable your postrun command), or do you think it would be better to revert this while we figure out how to proceed?

**Comment by Magisus** [comment]
Okay, I think this PR fixes the issue: https://github.com/puppetlabs/r10k/pull/1216. Lemme know what you think. I'm going to be on vacation for the next week, but review in the meantime is still appreciated! 

And do let us know if you need us to revert the feature in the meantime.

**Comment by alexjfisher** [comment]
Fixed in https://github.com/puppetlabs/r10k/pull/1216
