### ISSUE TITLE
The puppet_forge version should be bumped to 3.1.0+

### ISSUE THREAD

**Issue by trevor-vaughan** [puppetlabs/r10k#1217]
## Describe the Bug
The puppet_forge dependency is causing issues updating gems that depend on `r10k`.

## Expected Behavior
The latest functional dependencies would be used.

## Additional Context
At this time, I have not seen any issues using `puppet_forge` 3.1.0+

**Comment by mwaggett** [comment]
Thanks for opening this @trevor-vaughan ! Unfortunately, `puppet_forge` 3.1.0+ drops support for Ruby 2.3, so making this bump would be considered a breaking change. We currently don't have an estimate for when we'll be able to do an r10k 4.0.0 release, but this will need to wait until then. This JIRA ticket has some additional info: https://tickets.puppetlabs.com/browse/RK-377

**Comment by mwaggett** [comment]
We [attempted](https://github.com/puppetlabs/r10k/pull/1218) to loosen the `puppet_forge` dependency to allow for a range of versions that would support Ruby 2.3 through Ruby 3, but unfortunately `gem install`ing on Ruby 2.3 didn't work, so we had to [revert](https://github.com/puppetlabs/r10k/pull/1219).
