### ISSUE TITLE
Gracefully handle collision of VCS managed directories and Puppetfile managed directory

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#123]
When r10k deploys a Puppetfile it forcibly takes over the `modules` directory without checking if there is an existing directory. If users are tracking modules in that directory in a VCS repo, that directory will be wiped out with warning. If r10k tries to install modules from a Puppetfile and the target directory already exists, r10k should fail hard with an error and should not destroy the managed directory.

**Comment by mwedgwood-rmn** [comment]
One workaround might be to use two modules directories - one for puppetfile-managed modules and one for VCS-managed. This has the advantage of clarity about which modules are which.

In this case, it might be nice to allow the user to specify what the r10k-managed modules directory would be named.

**Comment by adrienthebo** [comment]
The ability to customize the name of the moduledir is already present (https://github.com/adrienthebo/r10k/blob/master/lib/r10k/puppetfile.rb#L107-L109) but isn't very flexible, since it requires an absolute path which doesn't mesh well with having lots of branches. This issue is captured in GH-43.

**Comment by mwedgwood-rmn** [comment]
[Modulepath's deprecation](http://docs.puppetlabs.com/puppet/3.6/reference/release_notes.html#deprecation-config-file-environments-and-the-global-manifestmodulepathconfigversion-settings) leaves no way to use two directories of modules in the same environment, so collision detection seems like the only way forward.

One approach might be:
1. Only delete directories whose name matches a module to be deployed
2. If a matching directory is _not_ a git repository, throw an error and die

**Comment by adrienthebo** [comment]
@mwedgwood-rmn In Puppet 3.6+, the modulepath needs to be configured on a per-environment basis with [environment.conf](http://docs.puppetlabs.com/references/3.6.latest/configuration.html#modulepath) - it's still possible to have multiple module directories for one environment, but the configuration was shifted around.

**Comment by mwedgwood-rmn** [comment]
Aha! I think that'll meet our needs. Thanks.

Seems the deprecation notice should mention something about environment.conf. We totally missed it.

**Comment by adrienthebo** [comment]
I mistakenly targeted GH-201 at this issue but this issue itself is not related; ignore the previous chatter from GitHub.
