### ISSUE TITLE
Use forge v3 API

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#124]
The forge integration for tracking the latest version of a module uses the old v1 API, which is apparently very inefficient. R10k should use the v3 API endpoints for looking up module versions.

**Comment by adrienthebo** [comment]
This change is backwards incompatible; if people are using r10k with a private forge (and I know there are users doing so) then this can't be entirely swapped out. We can add the v3 API support but we can't use the v3 API until there's a way to switch to the v1 API if users need it.

**Comment by dgolja** [comment]
Why just not add an option in the config file to explicitly enable V3 API if this would make the r10k more efficient ?

**Comment by adrienthebo** [comment]
Since r10k doesn't yet support the `forge` directive (#106) it's not directly possible to use a custom Forge with r10k; in addition the v3 API integration only applies to tracking the latest version of a module which can only be used with the official Forge. https://tickets.puppetlabs.com/browse/RK-27 updated r10k to use the v3 API and will be released in 1.5.0; if API compatibility truly is an issue then we can resolve those issues in a later release.
