### ISSUE TITLE
Feature: Branch selection for tracked repos

### ISSUE THREAD

**Issue by mwedgwood-rmn** [puppetlabs/r10k#129]
Some projects use feature branches on a central repo for all changes. It would be nice to be able to specify which branches to check out. For example, if I have development, test, and production branches plus a multitude of topic branches, my r10k.yaml might look like this:

```
...
:sources:
  :myrepo:
    remote: "http://..."
    branches: ['dev', 'test', 'production']
...
```

**Comment by adrienthebo** [comment]
+1, this dovetails in nicely with GH-101. I think this could probably be built for 1.4 at the earliest, maybe 1.5.0 if it doesn't make the 1.4.0 cut.

**Comment by lazyfrosch** [comment]
It actually looks like as if parts of this is already implemented, but not working:

```
:sources:
  :myrepo:
    remote: "http://..."
    environments:
      - dev
      - test
      - production
```

But it looks like that code is not used...

Or am I wrong?

**Comment by bkc1** [comment]
+1 on this, being able to specify branches would be a very helpful option and prevent r10k from deploying unwanted side/feature branches if someone accidentally pushes them to the remote. 

Any update on if and/or when this might be included? thx
