### ISSUE TITLE
Running r10k without default config file null refs

### ISSUE THREAD

**Issue by vexilar** [puppetlabs/r10k#13]
If I run r10k without a config file in the default location and without passing it the config file parameter I get:
Runtime error:  TypeError: can't convert nil into String

However, if I pass an invalid location for a config file I get a better error:
Runtime error: Errno::ENOENT: No such file or directory - /etc/r30k.yaml

**Comment by adrienthebo** [comment]
Oh gads, I haven't responded to this in over three weeks! Sorry, I'm really behind on triage!

Which command are you invoking that produces the error? Which version of r10k is this? Could you call it with the `--trace` option and paste the stack trace here?

**Comment by adrienthebo** [comment]
Released in 1.0.0rc1
