### ISSUE TITLE
multiple moduledir in Puppetfile

### ISSUE THREAD

**Issue by naevtamarkus** [puppetlabs/r10k#133]
I understand you don't mind having multiple moduledir statements in a single Puppetfile. How about the following:

```
moduledir 'modules'   # would be the default, no need to specify it
mod x
mod y
moduledir 'manifests'
mod z
```

I understand that having a begin/end looks nicer... but its usefulness is just the same. 
The deploy part works (I think I already mentioned it before) but not the Purge part. I have been looking at the code and it LOOKS relatively easy to solve, without breaking backwards compatibility:
- Modules code does nott need to be modified, since moduledir is part of its properties (that's why the deploy works)
- The Purge task in task/puppetfile.rb would then use, instead of the moduledir to do the cleaning, a similar approach as with the Deploy  (@puppetfile.load and then @puppetfile.modules.each do |mod|). I still have to figure out how to do this in a language I don't know.
- The desired_contents (in r10k/puppetfile.rb) will have to include the moduledir, not only the module.name itself. The same goes with all current_contents, stale_contents and pending_contents (in util/purgeable.rb), so that the mapping includes full paths and not only module names. I am not sure if making all modules "full-pathed" would break any existing rspec test, but that's probably the smart thing to do.

Note that, after this change, the Puppetfile attr :moduledir does not make any sense (it seems to be used only by the purger, anyway, until this change is done) and should be removed (together with the spec checks). I don't think it hurts if we don't remove it just yet, so I would leave this to a second PR to clean up code.

**Comment by luisfdez** [comment]
@adrienthebo , any update on this enhancement? I'm facing a similar scenario. It's more cosmetic than functional but I find useful to support.
