### ISSUE TITLE
Improve logging when using multiple sources

### ISSUE THREAD

**Issue by zachfi** [puppetlabs/r10k#136]
When deploying multiple sources, the log output does not specify the source that is being deployed.

**Comment by adrienthebo** [comment]
+1. GH-91 also requests similiar functionality around having finer grained control over deploying multiple sources.

**Comment by adrienthebo** [comment]
Commit 9496266c started logging the full path to the environment and module being deployed; while it doesn't explicitly mention the source that the environment belongs to it does provide much more context about what's being done. If this solves your issue feel free to close this issue.

**Comment by zachfi** [comment]
This sounds perfect.  Thank you.
