### ISSUE TITLE
.git/objects/info/alternates not updated on remote changes

### ISSUE THREAD

**Issue by acidprime** [puppetlabs/r10k#137]
Currently when a remote is changed in the Puppetfile, r10k will not always update the to point to the new ref .git/objects/info/alternates. This can cause tags to not currently resolve is certain situations such as organizational repo moves with github enterprise.

**Comment by adrienthebo** [comment]
This is probably related to GH-131.

**Comment by adrienthebo** [comment]
It looks like this partially regressed in 3b9b39265d7, where it was assumed that `@remote` was the current state and not the intended state and thus would always be in sync.

**Comment by adrienthebo** [comment]
Fix committed as 04827ff56691caa183b89b25ea251f8f11f240ff, could stand verification before being merged.

**Comment by adrienthebo** [comment]
Merged in 20c878e.
