### ISSUE TITLE
Can not change default modules dir

### ISSUE THREAD

**Issue by mythus** [puppetlabs/r10k#143]
Hi,

In our setup we use dynamic environments and in our repositories the modules dir is used  for internally developed modules, so it conflicts with the r10k(librarian-puppet) need to manage this directory. It will be very nice if we could specify from the r10k.yaml where the modules are deployed and change the default modules directory. For now we made the following work around by modifying Puppetfile class initialization and adding extmodules instead of modules:
def initialize(basedir, moduledir = nil, puppetfile = nil)
    @basedir         = basedir
    @moduledir     = moduledir  || File.join(basedir, 'extmodules')

Setting up moduledir in the Puppetfile is not an option because it do not take into account the dynamic environment. Do you know of better work around of this issue ?

Best regards,

**Comment by adrienthebo** [comment]
This looks like a duplicate of #141 so I'm closing it out. If this is incorrect please comment on it and I can see about reopening it.
