### ISSUE TITLE
Removing files in the cachedir does not allow rebuilding the cache properly.

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/r10k#144]
Related: https://github.com/adrienthebo/r10k/issues/131 and https://github.com/adrienthebo/r10k/issues/137

I updated the repository location for r10k. The update was to move from one project to another in a private Stash server. Original:

```
remote: "ssh://git@url:7999/oldproject/puppet-opensource.git"
```

Updated:

```
remote: "ssh://git@url:7999/newproject/puppet-opensource.git"
```

The updated repo has had further changes made to it after forking from the previous repo, specifically that the module's git locations were changed to the new project as well.. After performing a deploy (r10k deploy environment -p), the resulting environments were still based on the original repo contents. I investigated the cachedir and found the following files:

```
:cachedir: /var/cache/r10k

[user@puppet puppet-opensource]$ ls /var/cache/r10k
ssh---git@url-7999-oldproject-repo1.git
ssh---git@url-7999-oldproject-repo2.git
ssh---git@url-7999-oldproject-puppet-opensource.git
ssh---git@url-7999-oldproject-repo3.git
ssh---git@url-7999-newproject-puppet-opensource.git
```

In spite of the updated cache for the new puppet-opensource repo, the other modules were still installed off the older repo's Puppetfile contents. I cleared the cache contents and found it only created more problems:

```
[rn7284@puppet puppet-opensource]$ sudo rm -fR /var/cache/r10k/ssh---git\@url*
[rn7284@puppet puppet-opensource]$ sudo r10k deploy environment -pv
Faraday: you may want to install system_timer for reliable timeouts
[R10K::Task::Deployment::DeployEnvironments - INFO] Loading environments from all sources
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment production
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Environment::Deploy:0x7f83b62268e8> failed while running: Command git --git-dir /etc/puppet/environments/production/.git fetch --prune cache exited with 128: error: object directory /var/cache/r10k/ssh---git@url-7999-oldproject-puppet-opensource.git/objects does not exist; check .git/objects/info/alternates.
error: refs/heads/master does not point to a valid object!
error: refs/remotes/cache/feature does not point to a valid object!
error: refs/remotes/cache/production does not point to a valid object!
error: refs/remotes/origin/HEAD does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/remotes/origin/production does not point to a valid object!
fatal: '/var/cache/r10k/ssh---git@url-7999-oldproject-puppet-opensource.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly

[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments
```

I tried a few other things (r10k puppetfile purge, r10k puppetfile check, r10k deploy module <names>) but the only thing that worked was removing /etc/puppet/environments/production (I only have one environment right now). Afterward, r10k deploy environment -p worked fine.

```
[root@puppet puppet]# rm -fR /etc/puppet/environments/production/
[root@puppet puppet]# logout
[rn7284@puppet puppet-opensource]$ sudo r10k deploy environment -p
```

The production environment's contents are now OK.

**Comment by adrienthebo** [comment]
This failure was probably due to a mismatch between the `cache` remote and the contents of the `alternates` file, would you be able to try to reproduce this and ensure that the fix for GH-137 also fixes your case?

**Comment by rnelson0** [comment]
I can't replicate it at this time and if I do encounter it again, I will look at a new ticket related to GH-147.
