### ISSUE TITLE
Possible to leverage SSH ControlMaster for git repos?

### ISSUE THREAD

**Issue by nvalentine-puppetlabs** [puppetlabs/r10k#146]
Sitting here watching r10k deploy an environment consisting of nearly 60 module git repos and wondering if it would be possible to utilize SSH's ControlMaster to re-use SSH connections and therefore improve speed of env build?

**Comment by adrienthebo** [comment]
Is it possible? Theoretically. Is it feasible to implement in r10k? I'm not optimistic.

Setting up the ssh configuration to use ControlMaster looks to be a bit intrusive in that it requires touching a number of user configuration files, which is definitely outside of the primary scope of r10k. It looks like it could be implemented by end users that could set up the necessary configuration, and if I'm reading the documentation correctly it looks like all SSH connections started by Git/r10k could benefit. If this is the case then this could be a matter of documenting it.

I'm going to leave this open and target it at the 'unplanned' version, and I'll leave it open for about 3 months for community members to work on. If it doesn't see any activity within that time frame I'll close it out until there's interest expressed in implementing this feature.

**Comment by jlambert121** [comment]
I just did some playing around with this in my environment and found there to be a negligible difference with and without ControlMaster for my environment.  81 modules total, 41 are in git.  On a rerun time went from 40.0s to 39.875, on a clean machine checkout time went from 4m 32.2s to 4m 17.3s.

**Comment by nrvale0** [comment]
@jlambert121, that's rather disappointing. Was this for purge-and-rebuild of a single environment/branch?

**Comment by jlambert121** [comment]
Single environment.  The longer time was a "rm -rf" on the environment first.

**Comment by nrvale0** [comment]
I wonder if any benefit would manifest when doing a build out of all
branches in the control repo? Not that that is a common scenario.

Also, the particular environment I was working in when this idea occurred
to me has a Gitlab server which has surprisingly long connx setup times. I
should test there. Can you gist your setup?

-- via mobile

**Comment by jeremy-asher** [comment]
I've seen a considerable benefit with using ControlMaster/ControlPersist on an environment with over 100 Git repos.  To get any benefit, however, I had to work around an issue with ssh holding stderr open (see #169).  Here's some typical times I'm seeing for re-deploying after an rm -fr on the environment so the cache repos were already up to date:

without persist:
real    2m57.505s
user    0m53.520s
sys     0m10.960s

with persist:
real    1m16.332s
user    0m49.100s
sys     0m10.730s

**Comment by adrienthebo** [comment]
What steps did you need to go through to configure the SSH ControlMaster?

**Comment by mwedgwood-rmn** [comment]
In an ssh client config (i.e. ~/.ssh/config), possibly in a Host block:

```
ControlPath ~/.ssh/control_master/%r@%h-%p
ControlMaster auto
ControlPersist 10m
```

Here's a brief overview, from PuppetLabs conveniently enough: http://puppetlabs.com/blog/speed-up-ssh-by-reusing-connections

**Comment by jeremy-asher** [comment]
I've been experimenting with shorter timeouts (10 seconds) due to the openssh issue I mentioned in #169.  Currently, r10k will hang after each git fetch operation for the duration of the ControlPersist setting.

I've been using the GIT_SSH environment variable to activate the ControlMaster setting and work around the openssh issue.  I set GIT_SSH in root's .profile (export GIT_SSH=/usr/local/bin/wrapper) and when running r10k via mcollective agent.  Here's a hackey manifest that deploys a wrapper:

``` puppet
$wrapper_file = '/usr/local/bin/git_ssh_r10k_wrapper'
$ssh_config_file = '/etc/r10k_ssh_config'
$git_server = 'git.example.com'

$wrapper_content =
"#!/bin/bash
ssh -F ${ssh_config_file} $* 2>/dev/null
"
file { $wrapper_file:
  ensure  => file,
  mode    => '0755',
  content => $wrapper_content,
}

$ssh_config_content =
"Host ${git_server}
  ControlMaster auto
  ControlPersist 10
  ControlPath ~/.ssh/socket-%r@%h:%p
"
file { $ssh_config_file:
  ensure  => file,
  content => $ssh_config_content,
}
```

**Comment by adrienthebo** [comment]
Since this is primarily a matter of configuring SSH to use the ControlMaster setting, I'm marking this as a documentation ticket. It would be good to have this either added to the documentation ticket, or documented in an outside location and linked to from the docs.

This does rely on functionality added into 1.4.0, so I'll leave this open for about a month after 1.4.0 ships to allow for time for a documentation pull request to be filed.

**Comment by adrienthebo** [comment]
1.4.0 has shipped so if there is continued interest in this I would like to see an update before 2015, else I'll close this issue out.

**Comment by adrienthebo** [comment]
Because this issue hasn't seen any activity in about a month I'm closing this; if someone wants to update the docs for this functionality pull requests are gladly accepted!
