### ISSUE TITLE
Richer logging functionality

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#148]
log4r has very rich semantics for log destinations and verbosity of log hierarchies. However the current logging system only allows the log level to be set on a global basis and only allows logging to the console.

First off, r10k should expose the loglevel for individual hierarchies. Users should be able to specify the global log level as is currently allowed, and in addition r10k should be able to take a list of log hierarchies and the desired level so that detailed logging can be done for specific subsystems.

In addition r10k should allow users to specify the log outputs. This should include the current console logging, a rich console logger that logs to stdout and stderr for the appropriate log levels and colorizes levels appropriately, and a file log output.

**Comment by hybby** [comment]
I'd love for r10k's logging to be more configurable.  Any plans to do this?
