### ISSUE TITLE
Branch aliasing? Branch name override

### ISSUE THREAD

**Issue by tfhartmann** [puppetlabs/r10k#149]
I suppose this is really an r10k feature request, but wouldn't be possible for r10kto clone a branch into a directory name that doesn't correspond to branch name? In particular I'd like to be able to pass a config option that says " if branch is named master, clone it into environments/production"

**Comment by millerjl1701** [comment]
+1. I support multiple groups of admins: some use branches for dynamic environments while others don't preferring a single master branch. The ability to pass a r10k config option to specify the directory to create for master would be extremely useful and simplify my current processes..

**Comment by adrienthebo** [comment]
It's within reason, and because `master` is the default Git branch name but production is the default Puppet environment name, it's a common use case. However if a branch is given an alias and another branch with that name exists, what should happen?

**Comment by tfhartmann** [comment]
So I think that my strong preference, since I'm imagining aliasing as an _explicit_ override that the alias always take preference.   So if it's configured in /etc/r10k.yaml for example that "master" maps to "production" that should a "production" branch get created that it get skipped by r10k, and a error message logged or thrown saying something like " Master branch has been aliased to the production environment already - branch production ignored" 

A second option may be a "fail" outright, with a message indicating that something has gone horribly wrong and to send a fire-engine for cleanup. 

Like I said, my preference is for option "a"  which would protect against accidental overriding of the pre-existing name spaces, and also require that an Admin _explicitly_ configure r10k to do a branch/environment alias.

**Comment by millerjl1701** [comment]
I don't think that conflict would happen in my case as I use prefixing on my dynamic environments and I wouldn't use prefixing on these aliased environments... So, which ever method of failure would allow the feature to go out the door quicker gets my vote. :)

**Comment by adrienthebo** [comment]
GH-135 partially touches on having environments with one version code checked out with an arbitrary name, could you check that out and see how it could affect you and if it deals with your use case?

**Comment by millerjl1701** [comment]
Yes, I believe so. Based on the comments, it appears that one would specify in /etc/r10k.yaml for a particular source the option "ref: 'branchname'" and only that branch would then be deployed to that name. Did I read things correctly? If so, then yes, this would cover my use case.

**Comment by jonnangle** [comment]
I have a similar requirement, but I need to map the branch name to an environment name dynamically - that is, we have a certain format for branch names (personal/user/branch, a la Giolite), which need to be mapped to an environment name (user_branch). At the moment, the 'invalid_branches' functionality gets us part of the way there, but a way to map branches to environments in a more general purpose way would be needed to fulfill our use case completely.

**Comment by bwitt** [comment]
hi was this implemented?  I don't see it in the docs.
