### ISSUE TITLE
r10k-0.0.10: uninitialized constant R10K::Git::WorkingDir::Forwardable (NameError)

### ISSUE THREAD

**Issue by larstobi** [puppetlabs/r10k#15]
```
/var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/git/working_dir.rb:19: uninitialized constant R10K::Git::WorkingDir::Forwardable (NameError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/r10k-0.0.10/lib/r10k/module/git.rb:3
```

Full trace: https://gist.github.com/larstobi/5337226
From Ubuntu Precise LTS.

**Comment by adrienthebo** [comment]
Thanks for reporting this, what version of ruby was this using and how was r10k run?

**Comment by larstobi** [comment]
```
# ruby --version 
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

**Comment by larstobi** [comment]
r10k was run just like this:

```
root@master:~# r10k
```

**Comment by adrienthebo** [comment]
I wasn't able to reproduce on my laptop with Ruby 1.8.7, so I'll have to test this on a VM.

**Comment by justenwalker** [comment]
I got this issue too on Ubuntu 12.04.2 Server edition.  I upgraded ruby to 1.9.3 but that did not fix it.  Eventually I found that adding `require 'forwardable'` to the top of r10k/git/working_dir.rb got me past this.
