### ISSUE TITLE
r10k does not report when subversion client wants to interact with user

### ISSUE THREAD

**Issue by timidri** [puppetlabs/r10k#155]
I am using subversion and when running 

```
r10k -v debug puppetfile install
```

r10k does not report if svn client asks something on the terminal, for instance credentials or conflict resolution decision. This looks like it's hanging and I always thought I had a proxy or firewall problem... cost me a lot of time. Can r10k report this somehow?

**Comment by adrienthebo** [comment]
When r10k is installing modules, each module must be able to complete or fail without prompting for user input. I believe the fix for this is invoking `svn` commands with the `--non-interactive` flag so that svn commands will not stall while trying to read from stdin.

**Comment by timidri** [comment]
That is a good idea. On this topic, is it possible to specify subversion credentials somewhere for the Puppetfile definition?

**Comment by adrienthebo** [comment]
Not at the moment, but I plan on adding options to specify the credentials in the Puppetfile and in a file on the system running r10k.

**Comment by rnelson0** [comment]
While I don't use svn, I was able to verify that this branch doesn't blow up at least.

**Comment by adrienthebo** [comment]
Merged into master in dda9df2.
