### ISSUE TITLE
git cache creation error when running in Cygwin

### ISSUE THREAD

**Issue by ghost** [puppetlabs/r10k#157]
my windows username is nnkrepelja

my puppetfile contains
mod 'wget',
  :git => 'ssh://git@stash.acme.com:7999/pup/puppet-wget.git'

When I run:
r10k --verbose DEBUG2 puppetfile install
I get:

[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::Task::Module::Sync - INFO] Deploying wget into /cygdrive/c/pierre/workspaceGeppetto4Stash/tomcat-vagrant/modules
[R10K::Git::Cache - DEBUG] Creating new git cache for "ssh://git@stash.acme.com:7999/pup/puppet-wget.git"
[R10K::Git::Cache - DEBUG1] Execute: git clone --mirror ssh://git@stash.acme.com:7999/pup/puppet-wget.git /home/nnkrepelja/.r10k/git/ssh---git@stash.acme.com-7999-pup-puppet-wget.git
[R10K::Git::Cache - DEBUG2] [git clone --mirror ssh://git@stash.acme.com:7999/pup/puppet-wget.git /home/nnkrepelja/.r10k/git/ssh---git@stash.acme.com-7999-pup-puppet-wget.git] STDERR: fatal: destination path '/home/nnkrepelja/.r10k/git/ssh---git@stash.acme.com-7999-pup-puppet-wget.git' already exists and is not an empty directory.
[R10K::TaskRunner - ERROR] Task #R10K::Task::Module::Sync:0x00000600799630 failed while running: Couldn't update git cache for ssh://git@stash.acme.com:7999/pup/puppet-wget.git: "fatal: destination path '/home/nnkrepelja/.r10k/git/ssh---git@stash.acme.com-7999-pup-puppet-wget.git' already exists and is not an empty directory."

The folder C:\cygwin64\home\nnkrepelja.r10k\git exists and it's empty. From Cygwin I can create files into it (touch /home/nnkrepelja/.r10k/git/pippo.txt) , and folders too.

The same command succeeds when run from the DOS Command prompt.

I wonder how at least to disable the creation of a git cache?

Thank you so much!
pierre

**Comment by adrienthebo** [comment]
The git cache repos cannot be disabled, and if you can't clone those then git is very badly broken. Does this occur when you use cmd.exe or powershell?

**Comment by adrienthebo** [comment]
This hasn't seen an update in about a couple of weeks; is this issue still valid?

**Comment by ghost** [comment]
sorry! No, when I use cmd it all works fine.... what I do now is running r10k only from cmd....

But yes, as you say, git must be badly broken on my machine.... I should probably reinstall it from scratch... I assume you can close this issue, it looks like I am the only person having this problem so it must be something messed up on my side.

thanks!

**Comment by adrienthebo** [comment]
Sounds good. If this is an issue with cygwin/Git/r10k interacting I'm very happy to address it, so I'm going to leave it open for a while longer. If you've already reinstalled cygwin and Git I can try to reproduce on a VM; if I don't hear back in a few weeks I'll consider this issue as resolved. Thanks for the issue report!

**Comment by adrienthebo** [comment]
Since there have been no further reports of this issue and no more information I'm going to close it out; if this does reoccur please add a comment to that effect and I can reopen.
