### ISSUE TITLE
deploying a new environment is too slow

### ISSUE THREAD

**Issue by lycplus** [puppetlabs/r10k#168]
a git workflow like this:
locally:
git checkout -b new_feature
...
add feature
...
git commit
git push -u origin new_feature

then, on puppet master:
r10k deploy environment -p

When the Puppetfile contains many modules (7.4M in my case), the deployment takes too long. It seems r10k downloads all modules in environments/new_feature/modules/, even though there are lots of modules of the same version in environments/production/modules.

This prevents developers from deleting branches too frequently. I wonder if there is a configuration option to specify a external module directory like /etc/puppet/modules, so that all environments can share modules.

**Comment by adrienthebo** [comment]
How many forge based modules are you using, and how many git based modules are you using?

**Comment by lycplus** [comment]
I use the puppetfile in https://github.com/glarizza/puppet_repository
11 forge based, 3 git based

**Comment by adrienthebo** [comment]
r10k uses extremely heavy caching of git repositories and is generally pretty fast; your bottleneck for those is probably going to be due to disk I/O latency. Forge modules are not yet cached so those have to be re-downloaded every time. The Forge module code is going to be redone as part of GH-1 and will include caching. What sort of times do you see when creating a new environment? How long does it take do do something like `puppet module install branan/eight_hundred` ?

**Comment by lycplus** [comment]
`puppet module install branan/eight_hundred` is instant. 
What sort of times do you see when creating a new environment? 

In total, it takes 1 to 3 minutes, Is this normal?

**Comment by adrienthebo** [comment]
That's phenomenally slow; I created a test environment with 93 modules and several of those had binary files committed; deploying everything from scratch took 53 seconds. What version of r10k are you using? Could you run r10k with `--verbose debug2` and look for commands that are exceptionally slow?

**Comment by lycplus** [comment]
[R10K::Git::Cache - DEBUG1] Execute: git clone --mirror git://github.com/hunner/puppet-wordpress.git /var/cache/r10k/git---github.com-hunner-puppet-wordpress.git

I also tried 
git clone git://github.com/hunner/puppet-wordpress.git 

It also stucks, is there any logging for such slow git repository?

**Comment by adrienthebo** [comment]
There is not yet timing information for running commands, but it's planned. How long does it take to run that `git clone`?

**Comment by lycplus** [comment]
About three minutes.

**Comment by adrienthebo** [comment]
So creating a new environment takes around 1 - 3 minutes, and fetching a fresh copy of hunner/wordpress takes about 3 minutes, correct? If you run `r10k deploy environment -v debug2` and eyeball the time it takes, is the deployment of the wordpress module dominating the runtime?

**Comment by lycplus** [comment]
Yeah, I think it's the problem of the repository.

**Comment by adrienthebo** [comment]
In that case there's probably very little I can do. For the last test can you remove that module, rerun the deploy, and see if the environment deploy time is more performant?

**Comment by lycplus** [comment]
I have already used R10K in our production environment. It works fine.
