### ISSUE TITLE
quickstart documentation does not result in a working setup

### ISSUE THREAD

**Issue by Wijnand** [puppetlabs/r10k#175]
I have used this documentation but I fail to get a working setup.
The documentation needs at least a default node declaration in the site.pp. 
However, after including that it fails to find profile::base:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class profile::base for geppetto.mycorp.nl on node geppetto.mycorp.nl

It would be nice if the documentation just works, it would be a very nice quickstart with directory environments.

**Comment by adrienthebo** [comment]
What are the permissions on the files in the environments directory, and specifically `manifests/profile/base.pp` and the parent directories in the environment in question?

**Comment by ghost** [comment]
@Wijnand - The site.pp does not require a default node declaration, as all appropriate classes are included as the result of:

`hiera_include('classes')`

Can you remove your default node declaration, perform another run, and let me know what the error is?

**Comment by Wijnand** [comment]
The permissions are not the problem as far as I can see.

```
# ls -ald /etc/puppet/
drwxr-xr-x 5 puppet puppet 4096 Jul 29 06:32 /etc/puppet/
# ls -ald /etc/puppet/environments/
drwxr-xr-x 6 puppet puppet 4096 Jul 29 06:31 /etc/puppet/environments/
# ls -ald /etc/puppet/environments/test/
drwxr-xr-x 6 puppet puppet 4096 Jul 29 06:32 /etc/puppet/environments/test/
# ls -ald /etc/puppet/environments/test/manifests/
drwxr-xr-x 3 puppet puppet 4096 Jul 29 06:31 /etc/puppet/environments/test/manifests/
# ls -ald /etc/puppet/environments/test/manifests/profile/
drwxr-xr-x 2 puppet puppet 4096 Jul 29 06:31 /etc/puppet/environments/test/manifests/profile/
# ls -ald /etc/puppet/environments/test/manifests/profile/base.pp
-rw-r--r-- 1 puppet puppet 45 Jul 29 06:31 /etc/puppet/environments/test/manifests/profile/base.pp
```

I also removed the default node declaration as @richardraseley suggested.

Error is still the same:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class profile::base for geppetto.mycorp.nl on node geppetto.mycorp.nl

But if you can create a working setup with the current quickstart documentation then the error must be at my end and I apologize for creating an incorrect issue :-)

**Comment by ghost** [comment]
@Wijnand - Thank you for that information. Can you confirm that the `environment=test` option is set in the `puppet.conf` file on `geppetto.mycorp.nl` ?

Let's not say this is 'user error' just yet. =]

**Comment by Wijnand** [comment]
Yes, I can confirm that :-)

I do have a working setup now (I had to move on, could not afford more downtime) but its not as simple and clean as the quickstart documentation.

I created toplevel local directory and added it in the modules load path in environment.conf. Within that directory I created a complete module structure for the site module:

```
# ls -d /etc/puppet/environments/production/local/site/*
/etc/puppet/environments/production/local/site/files  /etc/puppet/environments/production/local/site/manifests  /etc/puppet/environments/production/local/site/templates
```

And the manifests directory contains a init.pp class. 

```
# head -n 1 /etc/puppet/environments/production/local/site/manifests/init.pp
class site {
```

All my manifests are now inside this site module:

```
# head -n 1 /etc/puppet/environments/production/local/site/manifests/roles/mysql.pp
class site::roles::mysql {
```

I still have the quick start tutorial inside the test branch/environment so I am able to do experiments and try adjustments if that helps?

**Comment by ghost** [comment]
@Wijnand - I am going to run back through the script again tonight, but I just haven't experienced the issues you're seeing. What platform are you using?

@adrienthebo - Could you assign this issue to me please?

**Comment by ghost** [comment]
@Wijnand - On second thought, it might be as late as Friday afternoon before I have time. We'll get to the bottom of it though.

In the meantime, can you share what distro you're using?

**Comment by Wijnand** [comment]
@richardraseley This is on ubuntu 14.04

**Comment by adrienthebo** [comment]
@richardraseley have you been able to look into this any more?

**Comment by rnelson0** [comment]
I randomly stumbled onto this; the issue is that puppet will only look for classes in the modules dir and profiles/base.pp is in the manifests dir. I'm not sure of the intent of the existing documentation but I think changing:

mkdir {modules,manifests/profile,hiera}

To:

mkdir {modules,modules/profile,modules/profile/manifests,hiera}

And changing the file references for the class to modules/profile/manifest/base.pp will help. This should cause Puppet to find the module properly. However, I am not in a position to test. @Wijnand or @richardraseley can you test this?

**Comment by ghost** [comment]
OK - this was a really simple oversight on my part. The first issue is that the 'modulepath' parameter includes directories 'modules' and 'site' when the later should've been dropped ('site' was an artifact from a configuration I referenced).

The intent is to craft a 'profile' module which contains the classes necessary to instantiate any desired resources with the business-specific configuration / logic. We then gather these 'profiles' into 'roles' by including them at a particular place in Hiera's hierarchy.

That being the case, the directory structure is indeed jumbled - as you pointed out. The 'profile' module should conform to the following: https://docs.puppetlabs.com/puppet/3.6/reference/modules_fundamentals.html#module-layout

I will prepare a PR tomorrow to fix this and be sure to test it with Ubuntu 14.04.

**Comment by guzmanbraso** [comment]
Bump, same behavior on latest Debian Stable following quickstart.

**Comment by guzmanbraso** [comment]
I've tried @rnelson0 suggestion but didn't work because profile folder inside modules is purged by default when running r10k deploy. BTW also had to add mod stdlib to Puppetfile as ntp needs str2bool().

Any ideas? I'm well documenting everyhing I'm doing on Debian to get quickstart to work, as soon I get it working I'll submit a pull request to fix the docs.

My puppetmaster server:
- r10k 1.3.4
- puppetmaster 3.7.1-1
- debian 7.0 wheezy
- kernel 3.2.0-4

**Comment by ghost** [comment]
@guzmanbraso - I just haven't been able to make time to work on this, but the distillation of what needs to happen is:

(_) Some directory in the top level of the environment which will get added to the modulepath.
(_) A 'module' called 'profile' in aforementioned directory.

**Comment by rnelson0** [comment]
@guzmanbraso you are correct, the modules/profile directory will be wiped; I was only looking at why puppet wasn't finding the files before. A 'site/profile' directory would work since 'site' is already in the modulepath.

**Comment by guzmanbraso** [comment]
@richardraseley @rnelson0 Thank you! That did the trick, just updated the quickstart guide and will submit pull request in a few seconds.

**Comment by ghost** [comment]
:+1:  Thank you @guzmanbraso

**Comment by adrienthebo** [comment]
GH-192 has been merged and should fix the issue, could someone confirm?

**Comment by adrienthebo** [comment]
It's been about two weeks since this has been updated; I'm going to consider this as closed.  @Wijnand @guzmanbraso @richardraseley @rnelson0 thanks for your help on this!
