### ISSUE TITLE
Cache paths on Windows

### ISSUE THREAD

**Issue by benpriestman** [puppetlabs/r10k#181]
Hi,

One of my current workflows for developing on Windows is to run VMs as Vagrant boxes, using a shared directory between my host machine and the guest VMs. My puppet projects sit in the shared directory. I use R10K on my masters to control dev and prod puppet code, but was using librarian-puppet during development (as I hadn't discovered the `r10k puppetfile` command). I hit issues with this a few months back, when downloading modules from git repositories started failing with mysterious permission errors. This turned out to be the 260-character limit on Windows being reached by the long directory names used in the cache directories.There are numerous issues around this with librarian. See, for example, https://github.com/rodjek/librarian-puppet/issues/208.
Now I've discovered that I can use r10k on WIndows much more easily than librarian-puppet and I've discovered the `r10k puppetfile` command, I've switched to using r10k throughout - because it is better. I still have issues with long file-names in cache paths, though. I get around this at the moment by setting my %HOME% environment variable to something close to the root of a drive. This works, but it is a bit of a hack. What I'm after is a way to set the cachedir for the `r10k puppetfile` command. I've tried setting up a r10k.yaml file and feeding this in on the commandline with `-c` option, but this seems to be ignored. Being able to control this command with a config file, or just being able to supply a %R10K_CACHE% environment variable would do the trick.

**Comment by adrienthebo** [comment]
This looks related to the issues laid out in GH-105.

**Comment by benpriestman** [comment]
Yes, solving GH-105 would fix thisue. Although other approaches to specifying the cache Dir would also work for me. Being able to use shorternames for the cache directories  would also help.

**Comment by adrienthebo** [comment]
Does powershell have the same limitations around 260 character limits on file names?

**Comment by benpriestman** [comment]
It's not a shell limitation, but an core api one. See
http://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath.
That article reminds me that there's an alternative path notation that
allows access to much longer paths. I'll let you know if have any joy from
testing this.

**Comment by c33s** [comment]
not stale

**Comment by Magisus** [comment]
Looks like the change you asked for was merged: It's been possible to specify a config file for all commands (including `puppetfile`) for a while https://github.com/puppetlabs/r10k/blob/ef72a75d3b250c800c1ff382c00fa3eb0aaa9aa8/lib/r10k/action/base.rb#L32.

Can you give that a try and let us know if it doesn't work or insufficient?
