### ISSUE TITLE
Sometimes r10k does not see changes

### ISSUE THREAD

**Issue by phpguru** [puppetlabs/r10k#184]
Cent OS 6.5 - when I run an r10k update on a fresh branch, it works great.

When I change the filename of an erb template, or even sometimes removing/adding code from a pp file, I will observe the same exact error on the agent run I saw before the commit.  I use this script (saved to /usr/local/bin/r10ku), which forces removing the cache as well, before each environment build.

```
#!/bin/bash

if [ $# -eq 0 ]; then
   echo 'Branch name (environment to build) required'
   exit 1
fi

echo "Building $1 ..."

rm -rf /var/cache/r10k/*
rm -rf /etc/puppetlabs/puppet/environments/$1
/opt/puppet/bin/r10k deploy environment $1 -p --verbose

echo "Done."
```

localhost
git push origin oldname
ssh puppetmaster
r10ku oldname
ssh puppetagent
puppet agent -t --environment oldname
// throws old error from code removed by last commit/push to origin oldname

I have found that I can only seem to force an r10k full refresh by pushing to a newname branch, and then building that:

localhost
git push origin oldname:newname
ssh puppetmaster
r10ku newname
ssh puppetagent
puppet agent -t --environment newname
// happy code or next error to fix...

**Comment by adrienthebo** [comment]
Are you making a change to the repository listed as a source in `r10k.yaml` or are you making a change to a module listed in the Puppetfile? If the latter, then modules in the Puppetfile are only updated on the first environment deploy and must be done manually. See https://github.com/adrienthebo/r10k/blob/master/doc/dynamic-environments/usage.mkd#deploying-environments for more information.

**Comment by phpguru** [comment]
I am experiencing the issue when making changes to erb templates and pp code in the git repo referenced in r10k.yaml (the former). When oldname branch is built for the first time, the code changes appear. When oldname branch is changed (rename or move an erb template, for example, and commit and push to the same oldname branch) the changes are not reflected on the agent, even after purging r10k cache and running r10k deploy oldname ... I realize this is probably a result of something strange about my setup but I'm not sure what it could be, have Puppet Enterprise support and they aren't sure either. Everything about my monolithic install "looks like it should work". It's not a huge dealbreaker ATM since I can workaround by doing featurename1, featurename2,... for each push & build, but it had worked without this at sometime previous so I am not entirely sure what changed.

**Comment by adrienthebo** [comment]
What version of Puppet are you using on your master? Puppet 3.6 and later may cache environment information (https://docs.puppetlabs.com/references/3.6.latest/configuration.html#environmenttimeout) which could be triggering this. Have you tried running a deployment and then waiting for a few minutes before running the agent?

**Comment by adrienthebo** [comment]
In addition when you encounter this failure case, have you SSHed into your Puppet master to see if the correct code has actually been deployed on disk?

**Comment by phpguru** [comment]
I am running PE 3.3.1 on master & agents. As a matter of fact, the new version of the code is present as expected under /etc/puppetlabs/puppet/environments/branchname/\* when running r10k branchname. Thanks for the link about environmenttimeout.

**Comment by phpguru** [comment]
I think you're right Adrien, I didn't realize we were setting custom environment_timeout durations! Solved. Check for an environment.conf and/or environment_timeout settings in your configuration.
