### ISSUE TITLE
Does r10k support Dynamic environments with r10k using svn instead of git on the hiera.yaml?

### ISSUE THREAD

**Issue by juasiepo** [puppetlabs/r10k#197]
Hi,

I feel pretty comfortable using dynamic environments using r10k and git.
BUT I have been asked to try using svn instead of git

At the Puppetfile level should be pretty easy as it is well documented

mod 'apache',
  :svn => 'https://github.com/puppetlabs/puppetlabs-apache/trunk',
  :rev => '154'

But I don't know how to (if it is possible) configure the r10k.yaml
file. I have searched on the Internet but I haven't found a valid
example. So I have supposed that the r10k should be like this:

:cachedir: '/var/cache/r10k'

:sources:
  :base:
    remote: 'https://svnserver/svn/puppet/'
    basedir: '/tmp/svn'

:purgedirs:
- '/tmp/svn'

Then running the deploy command gives the following error

r10k deploy environment --config /etc/r10k-svn.yaml
Faraday: you may want to install system_timer for reliable timeouts
[R10K::TaskRunner - ERROR] Task
# R10K::Task::Deployment::DeployEnvironments:0x7f304601a428 failed

while running: Couldn't update git cache for
https://svnserver/svn/puppet/: "fatal: HTTP request failed"

Does r10k support svn at r10k.yaml level?
Any idea what am I doing wrong?

Thanks for your time

**Comment by adrienthebo** [comment]
Try adding `type: svn` to the base source and see if that starts working for you.

**Comment by juasiepo** [comment]
Thank you

I just found this link: https://github.com/adrienthebo/r10k/issues/104
explaining the same.
Now the command r10k deploy environment --config /etc/r10k-svn.yaml runs
but gets frozen.

I suppose because the authentication required by the svn.
Do you now how to workaround this?

**Comment by juasiepo** [comment]
I found the solution, authentication is out of the scope of r10k.
Thank you for your time

Best regards

**Comment by adrienthebo** [comment]
It actually is in spite and is in progress in GH-155. I need people to test the new code so if you're interested i can run you through testing the topic branch that allows pw auth.

I'm going to reopen this issue because it does expose the fact that svn environments aren't well documented.

**Comment by adrienthebo** [comment]
@juasiepo the code that will handle SVN auth is at https://github.com/adrienthebo/r10k/issues/135#issuecomment-59583751, if you're still interested in that functionality could you take a look or try that code out?

**Comment by juasiepo** [comment]
I was using the svn authentication cache to handle this and for testing purposes was enough for me

At this moment I am not sure yet if we will continue on this direction (using svn as a backend).
I will let you know when the decision is taken in order to proceed with the test.

**Comment by adrienthebo** [comment]
SVN documentation has been added as part of 1.4.0.

**edit** and SVN auth has been handled in GH-155.
