### ISSUE TITLE
Runtime error for synchronize

### ISSUE THREAD

**Issue by emning** [puppetlabs/r10k#22]
I expect this may be a configuration error of some kind, but I can't figure out what's going on.

Running `r10k synchronize` produces the following output:

```
Runtime error: #<NoMethodError: undefined method `instance' for R10K::Deployment:Class>
```

Other commands, such as `r10k environment list` return the same.

I can get `r10k puppetfile install` to work in a folder containing an environment that I check out manually. This installs the modules specified in the Puppetfile to `modules/`, as expected.

Background: I'm trying to get r10k setup on our Puppet master. We already have a setup where git branches equal environments, and where creation and destruction of environments is handled by a git hook. I'm hoping to replace this hook with `r10k synchronize`.

This is on an updated Ubuntu 12.04, and I installed r10k by cloning the git repo as of today, doing a gem build and installing the resulting gem. Installation seems to have worked fine.

My `/etc/r10k.yaml` contains the following:

```
:cachedir: '/var/cache/r10k'

:sources:
  :plops:
    remote: '/srv/puppet.git'
    basedir: '/etc/puppet/environments'

:purgedirs:
  - '/etc/puppet/environments'
```

Our Puppet repo that contains the environments is located at `/srv/puppet.git` on the same server, and is a bare repo. I have tried variations of paths and `file://` URLs, but this doesn't seem to make a difference.

Any clue what's going on here?

**Comment by adrienthebo** [comment]
What version of r10k are you using? Is this the master branch of r10k or was it installed from rubygems?

**Comment by emning** [comment]
This is the master branch from github at the latest commit as of now, that is 4647ea11df.

I built it using gem build and installed it system-wide with sudo gem install, which seemed to pull in all dependencies ok.

**Comment by adrienthebo** [comment]
The master branch is on the tail end of a major rewrite, and it's not currently stable. The `r10k environment deploy` and `r10k module deploy` commands are getting switched to `r10k deploy environment` and `r10k deploy module` command and I'm deprecating the old methods. I need to add deprecation notices for all of those, and I've gotten a bit of a start.

In the mean time, `r10k puppetfile` and `r10k deploy` are pretty stable, but I can't guarantee the stability of master right now. But if nothing else I need to add those deprecation messages.

**Comment by emning** [comment]
All right! That explains it. Thank you. :)
