### ISSUE TITLE
Bad version number when trying to import a forge module

### ISSUE THREAD

**Issue by deviantony** [puppetlabs/r10k#225]
Puppetfile definition:

```
mod "rodjek/logrotate"
```

Then I start the command:

```
/usr/local/bin/r10k deploy environment -p
```

And here is the error report:

```
R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7ff29a322820> failed while running: Command puppet module --modulepath /etc/puppet/environments/development/modules install --version=1.1.1 --ignore-dependencies rodjek/logrotate exited with 1: Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
16:01:51               (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `issue_deprecations')
16:01:51            Error: Version numbers MUST begin with three dot-separated numbers
16:01:51            Error: Try 'puppet help module install' for usage
```

This is weird because the following command is just working fine:

```
 sudo puppet module --modulepath /etc/puppet/environments/development/modules install --ignore-dependencies --version 1.1.1 rodjek/logrotate
```

**Comment by adrienthebo** [comment]
This works for me:

```
└> cat Puppetfile 
mod "rodjek/logrotate"
└> bexec r10k puppetfile install -v debug
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::Task::Module::Sync - INFO] Deploying logrotate into /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
[R10K::Task::Puppetfile::Purge - DEBUG] No stale modules in /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
└> cat modules/logrotate/metadata.json 
{
  "name": "rodjek-logrotate",
  "version": "1.1.1",
  "source": "https://github.com/rodjek/puppet-logrotate",
[...]
```

The interesting thing for me is that when I apply this Puppetfile with maxed out debugging, I don't install a specific version of the module:

```
[R10K::Module::Forge - DEBUG1] Starting process: ["puppet", "module", "--modulepath", "/home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules", "--color", "false", "install", "--force", "rodjek/logrotate"]
```

Question time:
- What version of Puppet are you running?
- How did you install Puppet?
- What version of r10k are you running?
- What is the output of `puppet module list --environment development`?
- What are the contents of the Puppetfile for that environment?

**Comment by deviantony** [comment]
Ok so, a little update.
- Puppet 3.6.2
- Installed on Ubuntu via native packages
- r10k 1.3.1

Puppetfile content:

```
# Forge modules
mod "puppetlabs/stdlib"
mod "puppetlabs/ntp"
mod "puppetlabs/apt"
mod "puppetlabs/java"
mod "puppetlabs/apache"
mod "puppetlabs/concat"
mod "puppetlabs/mysql"
mod "maestrodev/wget"
mod "maestrodev/maven"
mod "maestrodev/sonarqube"
mod "saz/locales"
mod "nanliu/staging"
mod "puppetlabs/rabbitmq"
mod "puppetlabs/java_ks"

mod "private_module",
    :git => "http://gitlab.domain/puppet/private_module.git",
    :ref => "develop"

# ...more private modules on our private repository...
```

So I've spin up a Vagrant box to do some tests with Puppet 3.6.2 and r10k 1.3.4. I've spotted a few problems but I can't seem to be able to reproduce them.

For example, if I install from a Puppetfile with Puppet forge modules only and just after that use a Puppetfile with my private modules then the forge modules are not recognized any more (each one outputs a versio number error). But if I clean the module directory then I am able to import everything...
This happened to me once, and after testing it again: no issue. Weird...

**Comment by deviantony** [comment]
I've upgraded my production masters to r10k 1.3.4, cleaned my development environment folder and everything has been imported without problem...

**Comment by adrienthebo** [comment]
Could you make sure that you don't have any duplicate module definitions in the Puppetfile? If you don't specify a forge module version then no version will be used, so I'm baffled by the fact that you're seeing the Puppet module tool called with a version.

**Comment by deviantony** [comment]
My bad, I've copy/paste the line from my production branch Puppetfile which has a specified version for this module. The version is not specified for the development environment.

And nope, no duplicate.

**Comment by adrienthebo** [comment]
So the actual module you've specified is `mod 'rodjek/logrotate', '1.1.1'`?

**Comment by deviantony** [comment]
I've specified on my production branch:

```
mod 'rodjek/logrotate', '1.1.1'
```

And on my dev branch:

```
mod 'rodjek/logrotate'
```

Both were not working.

**Comment by adrienthebo** [comment]
The only way I can see this error happening is with the literal string contents of the version field. However, to confirm - clearing out and redeploying the modules for the environment resolved the problem, and you're not longer able to replicate the error?

**Comment by deviantony** [comment]
Yes, by clearing out and redeploying it's now working. I've tried to update the Puppetfile again by removing/adding some modules but I can't reproduce the error.

**Comment by adrienthebo** [comment]
Alright, I'm closing this as cannot reproduce. If this does show up again please comment on this issue and i can reopen it.

**Comment by deviantony** [comment]
The issue is back.

I've just added two new puppet forge modules to my Puppetfile and the r10k import crashed again:

```
Faraday: you may want to install system_timer for reliable timeouts
Faraday: you may want to install system_timer for reliable timeouts
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7f53ac8c5300> failed while running: Command puppet module --modulepath /etc/puppet/environments/development/modules install --force rtyler/jenkins exited with 1: Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `issue_deprecations')
Error: Version numbers MUST begin with three dot-separated numbers
Error: Try 'puppet help module install' for usage
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7f53ac8c5350> failed while running: Command puppet module --modulepath /etc/puppet/environments/development/modules install --force darin/zypprepo exited with 1: Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `issue_deprecations')
Error: Version numbers MUST begin with three dot-separated numbers
Error: Try 'puppet help module install' for usage
```

So I've try to clean my development environment folder, and now I'm unable to import any forge module. Every forge module import crash with the version number error.

**Comment by adrienthebo** [comment]
Ate you able to try the latest version of r10k from source? That has more detailed command logging.

**Comment by deviantony** [comment]
I'm already using the 1.3.4 version.

**Comment by adrienthebo** [comment]
I mean the latest version of r10k from Git, not the latest version from rubygems.

**Comment by adrienthebo** [comment]
Also, is it possible that you have leading or trailing whitespace in the module version? The error you're seeing happens when the version doesn't match `\d\.\d\.\d`, more or less.

**Comment by adrienthebo** [comment]
To confirm that the version number is properly formatted, try doing `grep 'rodjek/logrotate' Puppetfile | xxd` and pasting the results here.

**Comment by deviantony** [comment]
This time, the problem occurs when I try to import another module: darin/zypprepo

It's a Puppet forge module so I have no control over the module version and I'm not declaring any version in the Puppetfile.
Here is the output of `grep 'darin/zypprepo' Puppetfile | xxd`:

```
grep 'darin/zypprepo' Puppetfile | xxd          
0000000: 6d6f 6420 2264 6172 696e 2f7a 7970 7072  mod "darin/zyppr
0000010: 6570 6f22 0a                             epo".
```

**Comment by adrienthebo** [comment]
I can't reproduce this with either module:

rodjek/logrotate:

```
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::Task::Module::Sync - INFO] Deploying logrotate into /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
[R10K::Module::Forge - DEBUG1] Execute: puppet module --modulepath /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules install --force rodjek/logrotate
[R10K::Module::Forge - DEBUG2] [puppet module --modulepath /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules install --force rodjek/logrotate] STDOUT: Notice: Preparing to install into /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
└── rodjek-logrotate (v1.1.1)
[R10K::Task::Puppetfile::Purge - DEBUG] No stale modules in /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
```

darin/zypprepo:

```
└> bundle exec r10k puppetfile install -v debug2
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::Task::Module::Sync - INFO] Deploying zypprepo into /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
[R10K::Module::Forge - DEBUG1] Execute: puppet module --modulepath /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules install --force darin/zypprepo
[R10K::Module::Forge - DEBUG2] [puppet module --modulepath /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules install --force darin/zypprepo] STDOUT: Notice: Preparing to install into /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
└── darin-zypprepo (v1.0.1)
[R10K::Task::Puppetfile::Purge - DEBUG] No stale modules in /home/adrien/development/r10k/testing/puppetfile/gh-225-bad-version/modules
```

Can you create a Puppetfile with just one of these modules listed and run `r10k puppetfile install` to see if you can replicate this behavior in isolation?

In addition you can set a specific version for a module sourced from the Forge, per the Puppetfile docs: https://github.com/adrienthebo/r10k/blob/master/doc/puppetfile.mkd#forge-1 - the fact that you're seeing a specific module installed is strange because that's not default behavior.

If you can replicate this error by just running the `puppetfile install`, can you stand up a fresh system with r10k and try to reproduce there?

**Comment by deviantony** [comment]
Ok so here is a resume of my tests:

Testing a Puppetfile with one Forge module - Works fine:

```
forge "http://forge.puppetlabs.com"

# Forge modules
mod "darin/zypprepo"
```

Testing a Puppetfile with the other Forge module - Works fine:

```
forge "http://forge.puppetlabs.com"

# Forge modules
mod "rodjek/logrotate"
```

Testing a Puppetfile with both Forge modules - Works fine:

```
forge "http://forge.puppetlabs.com"

# Forge modules
mod "rodjek/logrotate"
mod "darin/zypprepo"
```

Testing a Puppetfile with both Forge modules and a private git module - Works fine:

```
forge "http://forge.puppetlabs.com"

# Forge modules
mod "darin/zypprepo"
mod "rodjek/logrotate"

mod "dns",
    :git => "http://gitlab.domain/puppet/dns.git",
    :ref => "develop"

```

Now, I've spotted that one of my private git module has a bad version number ('1.0' in place of '1.0.0') in its metadata.json.

Testing a Puppetfile with both Forge modules and a private git module with bad version - CRASH:

```
forge "http://forge.puppetlabs.com"

# Forge modules
mod "darin/zypprepo"
mod "rodjek/logrotate"

mod "bind",
    :git => "http://gitlab.domain/puppet/bind.git",
    :ref => "develop"

```

Output:

```
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7f9de419bc28> failed while running: Command puppet module --modulepath /etc/puppet/environments/testing/modules install --force darin/zypprepo exited with 1: Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `issue_deprecations')
Error: Version numbers MUST begin with three dot-separated numbers
Error: Try 'puppet help module install' for usage
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x7fcbcbbfcc20> failed while running: Command puppet module --modulepath /etc/puppet/environments/testing/modules install --force darin/zypprepo exited with 1: Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `issue_deprecations')
Error: Version numbers MUST begin with three dot-separated numbers
Error: Try 'puppet help module install' for usage
```

But as you can see, the error is pointing the Forge modules. That is quite a misleading error.

Anyway my problem is solved :-)

**Comment by adrienthebo** [comment]
Aha, that's very interesting! I suppose that the module tool must be loading all module data for some reason, sees the bad metadata and then dies. You might want to file that as a bug against Puppet because if we're ignoring dependencies we shouldn't load metadata from the other modules.

Anywho, since this is an issue with the module tool and not r10k I'm going to close this out. As always if this does trace back to r10k please comment on this issue and I can reopen it. Thanks!

**Comment by deviantony** [comment]
Hey, I would like to file the bug against Puppet but I'm not sure how to explain the bug ! Could you file it for me?
