### ISSUE TITLE
environment.conf example needs to be updated for PE 3.7.x

### ISSUE THREAD

**Issue by bhechinger** [puppetlabs/r10k#272]
Starting with 3.7.0 the provided environment,conf example no longer works.

It needs to be changed from:

modulepath = modules:site

to:

modulepath = modules:site:$basemodulepath

It appears that starting with 3.7.0 basemodulepath is no longer automatically searched. It needs to be explicitly provided.

**Comment by elyscape** [comment]
This is specific to PE, I believe.

**Comment by bhechinger** [comment]
Ok, so maybe best is to put a note in the docs about PE 3.7.0 and newer requiring that? I spent an awful lot of time with puppetlabs support to figure that out and I’d love to make sure no one else has to figure that out on their own as well.

-brian

**Comment by adrienthebo** [comment]
I think that this should be documented in https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/master-configuration.mkd; a pull request to make that change would be greatly appreciated!
