### ISSUE TITLE
module name validation

### ISSUE THREAD

**Issue by erinn** [puppetlabs/r10k#275]
Ok, I have a puppetfile that refuses to go as it were. It passes the check:
/usr/local/bin/r10k puppetfile check --verbose
Syntax OK

However, it fails to run:
/usr/local/bin/r10k deploy environment testing -p
[R10K::Action::Deploy::Environment - ERROR] Module names must match either 'modulename' or 'owner/modulename'

It may be helpful for the error to elucidate the offending line in the PuppetFile.

I removed the hyphens, still no luck. Here is a sanitized version of the puppetfile (hopefully I didn't remove the offender):

forge "http://forge.puppetlabs.com"
# Modules from the Puppet Forge

mod "puppetlabs/stdlib"
mod "puppetlabs/mysql"
mod "puppetlabs/ntp", :latest
mod "razorsedge/snmp", :latest

mod "postfix",
    :git => "https://github.com/erinn/puppet-postfix.git"
# Custom internal modules follow.

mod "aide",
        :git => "gitolite3@git.example.com:aide"

mod "apache",
        :git => "gitolite3@git.example.com:apache"

mod "audit",
        :git => "gitolite3@git.example.com:audit"

mod "bacula",
        :git => "gitolite3@git.example.com:bacula"

mod "baseapps",
        :git => "gitolite3@git.example.com:baseapps"

mod "beanstalkd",
        :git => "gitolite3@git.example.com:beanstalkd"

mod "bind",
        :git => "gitolite3@git.example.com:bind"

mod "cron",
        :git => "gitolite3@git.example.com:cron"

mod "denyhosts",
        :git => "gitolite3@git.example.com:denyhosts"

mod "disableservices",
        :git => "gitolite3@git.example.com:disableservices"

mod "epel",
        :git => "gitolite3@git.example.com:epel"

mod "func",
        :git => "gitolite3@git.example.com:func"

mod "group",
        :git => "gitolite3@git.example.com:group"

mod "grub",
        :git => "gitolite3@git.example.com:grub"

mod "inittab",
        :git => "gitolite3@git.example.com:inittab"

mod "ipa_client",
        :git => "gitolite3@git.example.com:ipa_client"

mod "kernel",
        :git => "gitolite3@git.example.com:kernel"

mod "kernel_reboot_pci",
        :git => "gitolite3@git.example.com:kernel_reboot_pci"

mod "lesssecure",
        :git => "gitolite3@git.example.com:lesssecure"

mod "login_defs",
        :git => "gitolite3@git.example.com:login_defs"

mod "logrotate",
        :git => "gitolite3@git.example.com:logrotate"

mod "logwatch",
        :git => "gitolite3@git.example.com:logwatch"

mod "modprobe",
        :git => "gitolite3@git.example.com:modprobe"

mod "modprobe_blacklist",
        :git => "gitolite3@git.example.com:modprobe_blacklist"

mod "motd",
        :git => "gitolite3@git.example.com:motd"

mod "mysql_backup",
        :git => "gitolite3@git.example.com:mysql_backup"

mod "node.js",
        :git => "gitolite3@git.example.com:node.js"

mod "nut",
        :git => "gitolite3@git.example.com:nut"

mod "opendkim",
        :git => "gitolite3@git.example.com:opendkim"

mod "pam_cracklib",
        :git => "gitolite3@git.example.com:pam_cracklib"

mod "pam_su",
        :git => "gitolite3@git.example.com:pam_su"

mod "pam_tally2",
        :git => "gitolite3@git.example.com:pam_tally2"

mod "pam_unix",
        :git => "gitolite3@git.example.com:pam_unix"

mod "passwd",
        :git => "gitolite3@git.example.com:passwd"

mod "pki",
        :git => "gitolite3@git.example.com:pki"

mod "prelink",
        :git => "gitolite3@git.example.com:prelink"

mod "profile",
    :git => "gitolite3@git.example.com:profile"

mod "example_staging_yum_repo",
        :git => "gitolite3@git.example.com:example_staging_yum_repo"

mod "example_testing_yum_repo",
        :git => "gitolite3@git.example.com:example_testing_yum_repo"

mod "example_yum_repo",
        :git => "gitolite3@git.example.com:example_yum_repo"

mod "psacct",
        :git => "gitolite3@git.example.com:psacct"

mod "puppet",
        :git => "gitolite3@git.example.com:puppet"

mod "resolv_conf",
        :git => "gitolite3@git.example.com:resolv_conf"

mod "role",
    :git => "gitolite3@git.example.com:role"

mod "rsyslog",
        :git => "gitolite3@git.example.com:rsyslog"

mod "security_limits",
        :git => "gitolite3@git.example.com:security_limits"

mod "selinux",
        :git => "gitolite3@git.example.com:selinux"

mod "ssh_authorized_keys",
        :git => "gitolite3@git.example.com:ssh_authorized_keys"

mod "sshd",
        :git => "gitolite3@git.example.com:sshd"

mod "ssl_abaqis_wc",
        :git => "gitolite3@git.example.com:ssl_abaqis_wc"

mod "ssl_example_wc",
        :git => "gitolite3@git.example.com:ssl_example_wc"

mod "sudo",
        :git => "gitolite3@git.example.com:sudo"

mod "sysconfig_init",
        :git => "gitolite3@git.example.com:sysconfig_init"

mod "sysconfig_network",
        :git => "gitolite3@git.example.com:sysconfig_network"

mod "sysctl",
        :git => "gitolite3@git.example.com:sysctl"

mod "sysstat",
        :git => "gitolite3@git.example.com:sysstat"

mod "time",
        :git => "gitolite3@git.example.com:time"

mod "timeout",
        :git => "gitolite3@git.example.com:timeout"

mod "vmware",
        :git => "gitolite3@git.example.com:vmware"

mod "yum_cron",
        :git => "gitolite3@git.example.com:yum_cron"

mod "yum_updatesd",
        :git => "gitolite3@git.example.com:yum_updatesd"

**Comment by adrienthebo** [comment]
```
mod "node.js",
:git => "gitolite3@git.example.com:node.js"
```

That's your issue - the period in the module name.

https://github.com/puppetlabs/r10k/pull/271 will add better reporting of errors like this; I'm supposed to be on vacation until the 5th so you should see a 1.4.1 release that'll contain that fix.

**Comment by adrienthebo** [comment]
Fixed as part of GH-271.
