### ISSUE TITLE
r10k is sensitive to module name separator in metadata.json

### ISSUE THREAD

**Issue by njm506** [puppetlabs/r10k#283]
There are forge modules using / as a separator in their names rather than -; although this is really an issue with those modules, it would seem reasonable to accept / as a separator character.  We're currently redeploying the puppetdb module on every r10k run as it reports a mismatch.

**Comment by adrienthebo** [comment]
Could you provide an example module that demonstrates this behavior?

**Comment by njm506** [comment]
puppetlabs-puppetdb 4.0.0 on the forge does it; every time the status will
be :mismatch, as the metadata.json specifies the name as
"puppetlabs/puppetdb" (so r10k determines that the author is
"puppetlabs/puppetdb", and the module name is "").

On 14 January 2015 at 17:29, Adrien Thebo notifications@github.com wrote:

> Could you provide an example module that demonstrates this behavior?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puppetlabs/r10k/issues/283#issuecomment-69955057.

## 

Nick Moriarty
Linux Systems Administrator and Developer

IT Services
Information
University of York
Heslington
York
YO10 5DD
United Kingdom
+44 (0)1904 32 3484

e-mail disclaimer: http://www.york.ac.uk/docs/disclaimer/email.htm

**Comment by adrienthebo** [comment]
Well, that's adorable. Both [stdlib](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/metadata.json#L2) and [apache](https://github.com/puppetlabs/puppetlabs-apache/blob/master/metadata.json#L2) use a hyphen, but [puppetdb](https://github.com/puppetlabs/puppetlabs-puppetdb/blob/master/metadata.json#L2) uses a slash.

Thanks for reporting this, I'm targeting this at 1.4.2.

**Comment by adrienthebo** [comment]
If you need a temporary workaround, you should be able to install modules like this from GitHub instead of the forge; that should bypass the buggy metadata behavior.

**Comment by njm506** [comment]
The forge documentation does indicate that only the hyphen is technically
correct (
https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#another-note-on-module-names),
so it's definitely an issue with the PuppetDB module (I've opened an issue
against it); it seemed a simple enough thing for r10k to cope with (and I
wouldn't be surprised if some other module authors had made this mistake),
hence the suggestion.

Many thanks - I'll use the workaround for the time being.

On 14 January 2015 at 18:12, Adrien Thebo notifications@github.com wrote:

> If you need a temporary workaround, you should be able to install modules
> like this from GitHub instead of the forge; that should bypass the buggy
> metadata behavior.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/puppetlabs/r10k/issues/283#issuecomment-69962605.

## 

Nick Moriarty
Linux Systems Administrator and Developer

IT Services
Information
University of York
Heslington
York
YO10 5DD
United Kingdom
+44 (0)1904 32 3484

e-mail disclaimer: http://www.york.ac.uk/docs/disclaimer/email.htm

**Comment by adrienthebo** [comment]
This is a pretty simple issue to fix, and unless the Puppet Forge will reject modules with an incorrect separator we'll have to support both anyways, so it's a worthwhile thing to fix.

**Comment by adrienthebo** [comment]
Sorry for the delay in handling this - issues have been transitioning to JIRA which has meant that a few tickets have fallen through the cracks. This should be fixed in r10k 1.5.0, could you verify that this is the case?

**Comment by njm506** [comment]
I've just upgraded us to 1.5.1 and the issue does appear to have been fixed.
