### ISSUE TITLE
Unspecified failure if StrictHostKeyChecking is not disabled

### ISSUE THREAD

**Issue by ggeldenhuis** [puppetlabs/r10k#293]
If r10k has not previously connected to a service it will just fail when you try and run r10k. The problem is that in the background r10k is being asked to accept the host key. This can be disabled by setting up an exception in the .ssh/config file.

Host server01.example.com
  StrictHostKeyChecking no
  IdentityFile ~/.ssh/id_rsa_r10k

However the error message should really be "brought forward" and be visible to the end user rather than just a generic error message.

**Comment by adrienthebo** [comment]
Which version of r10k are you using?

**Comment by ggeldenhuis** [comment]
1.4.0 I believe based on searching for files called r10k.
Eg:
/opt/puppet/lib/ruby/gems/1.9.1/cache/r10k-1.4.0.gem

r10k --version would be a useful future addition.

**Comment by adrienthebo** [comment]
`r10k version` will report the current version. What does r10k output when you run into this issue?

**Comment by ggeldenhuis** [comment]
Doh..... I completely missed that version flag. 

[R10K::Action::Deploy::Environment - ERROR] Couldn't update git cache for git@company:enterprise-provisioning/r10k-control.git
Original exception:
Command exited with non-zero exit code:
Command: git --git-dir /var/cache/r10k/git@company-enterprise-provisioning-r10k-control.git fetch --prune origin
Stderr:
Host key verification failed.
fatal: The remote end hung up unexpectedly
Exit code: 128

So admittedly the error message is descriptive after reading it properly. So if possible allowing the user to accept a host key rather than giving an error would be better behaviour.

**Comment by adrienthebo** [comment]
Right now r10k assumes that Git itself has been set up to clone whatever remotes are needed; it does need the ability to pass along extra options to the underlying transport command.

**Comment by ggeldenhuis** [comment]
Ok, I will do a pull request for some documentation updates to clarify the position on ssh usage. In my personal view as long as the documentation warns you it is ok.

**Comment by adrienthebo** [comment]
https://github.com/puppetlabs/r10k/pull/274/files partially touches on SSH deploy keys, would you be able to extend on that? https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/git-environments.mkd would be a good home for that documentation.

**Comment by ggeldenhuis** [comment]
The pull request looks sufficient for now in terms of adding additional explanation. I can certainly make a start on extending the git-environments.mkd documentation file.

**Comment by bittner** [comment]
What is the current state of this ticket?

Is adding `StrictHostKeyChecking no` to `/root/.ssh/config` encouraged? (It's sort of a security risk.)
If not, what is the suggested setup for new Puppet masters?

**Comment by bittner** [comment]
As of an answer on the #puppet Slack channel, @rnelson0 [suggests adding the host key](https://github.com/puppetinabox/controlrepo/blob/production/r10k_installation.pp#L5-L8) in the installation process, e.g.

``` puppet
sshkey { 'github.com':
  type => 'ssh-rsa',
  key  => 'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==',
}
```

See: https://docs.puppet.com/puppet/latest/types/sshkey.html

**Note:** The above code sample will only work when `HashKnownHosts=no` in your SSHd configuration (on Debian 8 this is `yes` by default). You'll get 2 hashed keys for your server otherwise when you connect with SSH for the first time, that you both have to add. ([Why hash host names?](https://security.stackexchange.com/questions/56268/ssh-benefits-of-using-hashed-known-hosts), [Why two entries?](https://askubuntu.com/questions/446878/why-do-ive-two-entries-per-server-in-known-hosts-file))
