### ISSUE TITLE
Feature Request - Puppetfile dependency report

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/r10k#305]
I can easily see this being something you wouldn't want in the source code for r10k, but as it is so relevant I thought I would suggest it.   Please direct me if you know of something that has already been built for this.  
## Use case

I want to be able to run a command / click a button, and have a report built (command line / web) of two things: 
1. Are all the minimum package dependencies being met (ie compare metadata.json files against the Puppetfile and see what the minimums are)
2. How many versions behind are we on all of our packages?
3. Are there any incompatibilities in the module.json files
4. Should be able to run this on every environment 
5. Graph out (with .dot files maybe?)  a dependency graph, to see what modules use parts of the Puppetfile.  From there we can identify unused modules as well

I'd imagine this is something a lot of people could benefit from, especially in larger installations where there are 40-50 modules in the puppetfile. 

What are your thoughts?  Maybe putting a utility like this in r10k isn't a great idea...  but there are some arguments towards it. (I'm really doing a good sales job here.. )

**Comment by adrienthebo** [comment]
Web app? No. CLI? Yes, in some incarnation. Something like this is on the roadmap, but this goes into dependency resolution which is down the road a bit.

**Comment by brettswift** [comment]
Ok cool.   I copied these criteria from an internal trello card so agreed - the web app isn't likely.  

I've added in another bullet point in case you want to reference this in the future: 

```
5. Graph out (with .dot files maybe?)  a dependency graph, to see what modules use parts of the Puppetfile.  From there we can identify unused modules as well
```

I'll close this issue as it's already on your roadmap.  Is there a feature for this on the puppetlabs site that I could track? 

Thanks!

**Comment by adrienthebo** [comment]
It's currently a lot of neat ideas and vaporware; I would like to have this issue hang around until we make more concrete tickets.
