### ISSUE TITLE
Allow update or installation of a single module when using the puppetfile subcommand

### ISSUE THREAD

**Issue by iverberk** [puppetlabs/r10k#33]
Currently the puppetfile subcommand is always installing/updating all the modules specified in the Puppetfile. 

To save time and make a more granular approach to installing/updating modules possible, it would be nice if you could specify which module you want to install/update. Something like:

r10k puppetfile install < modulename >

**Comment by adrienthebo** [comment]
Adding this to the 1.1.0 milestone. Thanks for the issue report!

**Comment by rnelson0** [comment]
Adrien, is this retargeted at a newer version?

**Comment by EdgeJ** [comment]
The conversation for this feature request appears to have dropped off a few years back without any firm resolution (that I can tell, anyway).  But, this would be a fairly useful feature for developing on custom modules that might need to be updated frequently on a test system without having to use cycles to update other modules that won't be changing frequently (e.g Forge modules).  To that end, I've submitted a PR to implement this relatively simple feature.
