### ISSUE TITLE
Support metadata.json-style version strings

### ISSUE THREAD

**Issue by karaken12** [puppetlabs/r10k#347]
The version string for Forge modules should support version requirements like ">= 3.2.0" and "1.x", as well as "1.2.5".

This could form a part of automatic dependency resolution (which is obviously a ways off), but it could be done before then (and wouldn't need a major revision, since it wouldn't break existing functionality).

**Comment by karaken12** [comment]
I don't seem to be able to add labels, so could someone add: "[type] enhancement", "[category] forge", "[subsystem] module" and "[subsystem] puppetfile"? Ta.

**Comment by adrienthebo** [comment]
This issue is related to #38.

**Comment by adrienthebo** [comment]
The ability to support version strings without adding dependency resolution isn't too useful; given a range of valid versions and no preference between them all r10k will do is install the latest version in that range. Does that provide any value?
