### ISSUE TITLE
Add support for CVS based environments and modules

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#381]
A lot of organizations still make heavy use of CVS for version control and pain generation, and right now they're not able to take advantages of all of the features r10k has to offer. We should implement CVS support alongside of Git and SVN for modules and environments to make sure that r10k is universally available to all people regardless of the decade their VCS tool came from.

**Comment by adamcrews** [comment]
My T-Rex thanks you for filing this feature request.

**Comment by adrienthebo** [comment]
The satisfaction of T-Rexes using r10k is very important to me.

**Comment by adrienthebo** [comment]
So now that we've had some laughs at the expense of CVS, until someone can provide a very good reason to add CVS support, proof that said support will be used, and a very large check to help cover the costs of the resulting rehabilitation of the developers involved, this ain't happening.
