### ISSUE TITLE
Update fails when remote repository has been forced-pushed

### ISSUE THREAD

**Issue by gehel** [puppetlabs/r10k#394]
It seems that if I rewrite history in my git repo, r10k will not update the latest changes. I have not digged into the details but here is what I tried:
- checkout an environment containing module X (`r10k -v info deploy environment -p`)
- realized there was a typo in module X, fixed the typo, squashed the commit, pushed it (`push --force`)
- checkout the environment again containing module X (`r10k -v info deploy environment -p`)
- change was not present

I then removed the module (`rm -rf /etc/puppet/environments/<env>/modules/X`) and the cache (`rm -rf /var/cache/r10k/<cache-for-module-X>`) and it started working again.

I know that rewriting history is controversial, but on a development branch I would argue that it make sense. r10k should probably be robust to this kind of things.

**Comment by adrienthebo** [comment]
R10k should be able to do non-fast forward fetches; the refspec used during fetches (`+refs/*:refs/*`) will ensure that the remote repo refs always overwrite the local refs to allow history rewriting. What version of r10k are you using?

**Comment by gehel** [comment]
I'm using 1.5.0. The problem might well be something else. As I have now deleted the cache and the checkout, I'm not sure how to investigate further. I did not try to reproduce the problem yet. (Feel free to close this issue as not reproduceable...)

Note that I did not get any error during update, but the module was not updated. Not sure if / how I can help you debug this.

**Comment by adrienthebo** [comment]
This was due to overly aggressive caching of Git repositories, and has been fixed in r10k 1.5.1. See https://tickets.puppetlabs.com/browse/RK-86 for more information.
