### ISSUE TITLE
Can a a set of environments be created without cloning the modules from Puppetfile?

### ISSUE THREAD

**Issue by zachfi** [puppetlabs/r10k#4]
If not, might I request this feature?

The use case is when you are deploying multiple r10k repositories, but only using the modules from one of them and don't need to update all of the modules for all of the branches. Thus, deploying only the per environment branches without cloning any of the modules would be super useful.

If this already exists, apologies, and I am happy to help document.

**Comment by adrienthebo** [comment]
Try `r10k environment deploy -u` to only update the root level repositories. If you want to recurse, `r10k environment deploy -u -r`. Be warned that the first time an environment is updated it will force a recursive update; otherwise the environment will be incomplete.

**Comment by zachfi** [comment]
Works nicely, thank you.  I think I was overloading the term environment.

**Comment by zachfi** [comment]
Works, thanks.
