### ISSUE TITLE
Installing r10k 1.5.x cannot generate documentation after install

### ISSUE THREAD

**Issue by robh007** [puppetlabs/r10k#406]
There appears to be an issue that's occurred since the update of the Faraday gem. Faraday appears to have a dependency with multipart-post which throws the following error when trying to install it.

Installing ri documentation for multipart-post-2.0.0...

Invalid output formatter

For help on options, try 'rdoc --help'

The current work around is to install version 1.4.2 of r10k then run gem update r10k. This looks like all dependencies are satisfied and installs 1.5.1 without any problems. Is anyone else seeing this issue? Currently using ruby 1.8.7 on a Centos 6.5 host. 

[root@puppetmaster ~]# gem install r10k -v 1.5.0
Successfully installed colored-1.2
Successfully installed cri-2.6.1
Successfully installed log4r-1.1.10
Successfully installed multi_json-1.11.0
Successfully installed json_pure-1.8.2
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.9.1
Successfully installed faraday_middleware-0.9.1
Successfully installed faraday_middleware-multi_json-0.0.6
Successfully installed semantic_puppet-0.1.1
Successfully installed r10k-1.5.0
11 gems installed
Installing ri documentation for colored-1.2...
Installing ri documentation for cri-2.6.1...
Installing ri documentation for log4r-1.1.10...
Installing ri documentation for multi_json-1.11.0...
Installing ri documentation for json_pure-1.8.2...
Installing ri documentation for multipart-post-2.0.0...

Invalid output formatter

For help on options, try 'rdoc --help'

**Comment by robh007** [comment]
I could issue install with the following options --no-rdoc --no-ri

**Comment by adrienthebo** [comment]
Are you certain that there is an issue installing r10k, or if there is an issue generating the documentation? Gems can be successfully installed even if an error occurs while building documentation.

Could you provide the output of `r10k version -v` with r10k 1.5.1?

**Comment by adrienthebo** [comment]
It looks like multipart-post specifies the ["darkfish" rdoc formatter](https://github.com/nicksieger/multipart-post/blob/master/multipart-post.gemspec#L20) in the gemspec, so this is an upstream issue. Try uninstalling r10k and installing from scratch, and check if r10k is functional even if there were issues generating documentation.

**Comment by robh007** [comment]
Sorry should have probably been a little more clearer, r10k is installing fine, its generating the docs as you pointed out where the error is generated, this then prevents my packer job from completing successfully. The only way to not get the errors is to install 1.4.2 then update to 1.5.1 or don't generate the rdocs.

**Comment by adrienthebo** [comment]
Well, you have a few choices on this - either install the [darkfish rdoc formatter](https://rubygems.org/gems/darkfish-rdoc) before installing r10k, install r10k with the `--no-rdoc` and `--no-ri` flags, or file a pull request against the multipart-post project to remove the use of the custom rdoc formatter. Since this is an issue with a dependency there's nothing I can really do to fix this from my end; if you think of something let me know, otherwise I'll probably close this issue out in a week or so as not a bug.

**Comment by robh007** [comment]
Closing issue.
