### ISSUE TITLE
README is missing bootstrapping information

### ISSUE THREAD

**Issue by eliasp** [puppetlabs/r10k#41]
The README doesn't provide any information on how to get started with r10k.

Although it would be somehow a cool feature to have r10k bootstrap it self somehow, it should at least provide some basic information on how to install it.

I don't think everyone can figure it out that it can be installed as "gem".

**Comment by adrienthebo** [comment]
Yeah, you raise an excellent point. The README should have a better walkthrough of the features, use cases, etc. I have http://somethingsinistral.net/blog/rethinking-puppet-deployment/ which was the more verbose overview of this topic, but it's a blog post and not a README.

I'll work on extracting the relevant documentation and put it into the README when I can make time. Thanks for submitting the issue!

**Comment by Ancillas** [comment]
I'm a ruby noob, and struggled to get r10k installed for this very reason.
Once I figured it out though, it was simple.  I'll take a stab at adding
this type of info into the readme, and I'll submit a pull request when it's
ready.

Greg

**Comment by adrienthebo** [comment]
@Ancillas @eliasp does https://github.com/adrienthebo/r10k/commit/019abe2e65d3368e1760438a8c1818f88dfa86a8 look like it's sufficient to clear this up?

**Comment by eliasp** [comment]
Looks good so far. Maybe it could mention [puppet-r10k](https://github.com/puppetlabs-operations/puppet-r10k) as an extra hint.

I'm also missing information on all the possible configuration variables for r10k.yaml (it currently just says _This basic configuration should be enough for most deployment needs_ below the example without listing other possible config variables, possible paths for r10k.yaml etc.), but that's probably a job for another issue.

**Comment by Ancillas** [comment]
I made a few changes and put them in https://github.com/Ancillas/r10k.  If
they look okay, I'll submit a pull request.  Note that I did some rebase magic, and forced a push so the history changed just a bit.  f4447a1a24b545548d185c85319e16dec281c86a

**Comment by adrienthebo** [comment]
The changes made by @Ancillas were merged last June, @eliasp thanks again for reporting this issue and @Ancillas thanks again for the documentation update!
