### ISSUE TITLE
Is it possible to loop the list of mods in Puppetfile

### ISSUE THREAD

**Issue by devopsprosiva** [puppetlabs/r10k#418]
Hi,

Instead of adding multiple mod statements for git based modules, can I loop through a list of modules like this?

``` ruby
mod_list = [mod1,mod2,mod3]

mod_list.each { |module|
mod '#{module}'
  :git => 'git@gitserver:<project>/#{module}',
  :ref => 'master'
}
```

Thanks,
Siva

**Comment by adrienthebo** [comment]
Yes; see the [Puppetfile documentation](https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#puppetfile) for more information. The section to note is this:

> Because the Puppetfile format is actually implemented using a Ruby DSL
> any valid Ruby expression can be used. That being said, being a bit too
> creative in the DSL can lead to surprising (read: bad) things happening,
> so consider keeping it simple.

**Comment by adrienthebo** [comment]
Since there's been no further comments on this issue I'm closing it; if you have additional questions feel free to comment on this issue and I can reopen it.
