### ISSUE TITLE
r10k should retry certain module errors

### ISSUE THREAD

**Issue by larstobi** [puppetlabs/r10k#42]
Sometimes modules have transient failures. This might be caused by bugs in Github or by other reasons, such as bad company proxies or network issues.

When r10k experiences a "git fetch" failure, or a "puppet module install"  failure, for certain error types, it should mark the module for a retry or two.

**Comment by adrienthebo** [comment]
Sorry for the delay in responding to this; it's been a hell of a year. :) Could you provide a list of errors that you would like to see retried on error?

**Comment by larstobi** [comment]
Hmm, I don't remember the details of these errors, I should have provided that list when I reported this issue. I'll close it. :)

**Comment by helperton** [comment]
INFO	 -> Deploying Puppetfile content /etc/puppetlabs/code/environments/our_environment/modules/stdlib
ERROR	 -> Unable to connect to https://forgeapi.puppetlabs.com (using proxy http://ourproxy:9090): Failure when receiving data from the peer
