### ISSUE TITLE
Having when i am trying to use with svn

### ISSUE THREAD

**Issue by supriyawishesu** [puppetlabs/r10k#425]
Hi,

I created the Puppetfile using svn. This is the content in puppetfile. 

```
mod 'createdirectory',
  :svn => 'http://xxxx.xxx.xxx/svn/puppet/puppetlabs/puppet/environments/testing/modules',
  :username => 'xxxx',
  :password => 'xxxx'
```

But it throwing me error:

```
ERROR    -> Command exited with non-zero exit code:
Command: svn --non-interactive checkout http://xxxx.xxx.x.xx/svn/puppet/puppetlabs/puppet/environments/testing/modules createdirectory --username xxxx --password xxxx -q
Stderr:
Errno::ENOENT: No such file or directory - svn
Exit code: 254
```

**Comment by adrienthebo** [comment]
Could you provide the output of running r10k with run with `-v debug2` ?

**Comment by adrienthebo** [comment]
It's been about two weeks since this ticket has seen an update, is this still an issue for you?

**Comment by supriyawishesu** [comment]
Hi Adrien,

I will do it today or tommorw and will show you

**Comment by supriyawishesu** [comment]
Hi,

Here is the output

/opt/puppet/bin/r10k deploy environment -v debug
[2015-06-09 15:18:16 - ERROR] Environment collision at
/etc/puppetlabs/puppet/environments/production between
development:production and testing:production

**Comment by supriyawishesu** [comment]
Hi,

```
/opt/puppet/bin/r10k deploy environment -v debug2
[2015-06-09 15:18:57 - DEBUG2] Starting process: ["svn", "--non-interactive", "ls", " http://xxxxx/svn/puppet/puppetlabs/puppet/branches", "--username", "xxxx", "--password", "xxx"]
[2015-06-09 15:18:57 - DEBUG2] Finished process: Command: svn --non-interactive ls http://xxxxxx/svn/puppet/puppetlabs/puppet/branches --username xxxxx --password xxxxx
Stdout:
development_branch/
testing_branch/
version1/
Exit code: 0
[2015-06-09 15:18:57 - DEBUG2] Starting process: ["svn", "--non-interactive", "ls", "xxxxxx/svn/puppet/puppetlabs/puppet/branches", "--username", "xxxxx", "--password", "xxxxx"]
[2015-06-09 15:18:57 - DEBUG2] Finished process: Command: svn --non-interactive ls http://xxxxxx/svn/puppet/puppetlabs/puppet/branches --username xxxxx --password xxxxx
Stdout:
development_branch/
testing_branch/
version1/
Exit code: 0
[2015-06-09 15:18:57 - ERROR] Environment collision at
/etc/puppetlabs/puppet/environments/production between
development:production and testing:production
```

**Comment by adrienthebo** [comment]
First off, you just leaked your SVN password in that above example. I've redacted it but you should probably change that.

Secondly, could you provide a sanitized copy of your r10k.yaml?

**Comment by adrienthebo** [comment]
Also, this looks to be the same issue as #429 - is the original issue you described still applicable?

**Comment by adrienthebo** [comment]
Actually, looking at #429 more closely indicates that you have two sources, development and production, that have the same remote. This means that you'll try to create two copies of each environment, and trying to manage the contents of one folder twice is bad. https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/svn-environments.mkd#how-it-works documents that each directory in the 'branches/' SVN directory will be created as an environment, so you'll have the 'production' environment from the 'trunk/' directory, and then the 'development_branch', 'testing_branch', and 'version1' environments created alongside it.

**Comment by supriyawishesu** [comment]
Hi Adrien

Here is my r10k.yaml fle

## cat r10k.yaml

# This example configuration details the most commonly used configuration

# options for the `r10k deploy` command.

#

# The 'cachedir' setting controls where cached content, such as mirrored Git

# repositories, are stored on the local machine. This location should be

# persistent, as environments and modules may rely on these files in order

to

# be updated.

#

# See

https://github.com/puppetlabs/r10k/blob/1.5.1/doc/git/cloning-and-mirroring.mkd

# for more information on how r10k caches Git repositories.

#

# The default value is "~/.r10k"

cachedir: '/var/cache/r10k'

_sources:_
-  main:*
-    type:  svn*
-    remote: 'http://xxxx.xxx.xxx/svn/puppet/puppetlabs/puppet
  http://xxxx.xxx.xxx/svn/puppet/puppetlabs/puppet'*
-    basedir: '/etc/puppetlabs/puppet/environments'*
-    username: 'xxxx'*
-    password: 'xxxx'*
-    prefix: true*
-  development:*
-    type:  svn*
-    remote:
  'http://xxx.xxx.xxx/svn/puppet/puppetlabs/puppet/environment/development
  http://xxx.xxx.xxx/svn/puppet/puppetlabs/puppet/environment/development'*
-    basedir: '/etc/puppetlabs/puppet/environments'*
-    username: 'xxxxxx'*
-    password: 'xxxx'*
-    prefix: true*

_/opt/puppet/bin/r10k deploy environment -p -v debug2_
_[2015-06-11 10:09:16 - DEBUG2] Starting process: ["svn",
"--non-interactive", "ls",
"http://xxxx.xxx.xx/svn/puppet/puppetlabs/puppet/branches
http://xxxx.xxx.xx/svn/puppet/puppetlabs/puppet/branches", "--username",
"xxxx", "--password", "xxxx"]_
_[2015-06-11 10:09:16 - DEBUG2] Finished process:_
_Command: svn --non-interactive ls
http://xxx.xxx.xxx/svn/puppet/puppetlabs/puppet/branches
http://xxx.xxx.xxx/svn/puppet/puppetlabs/puppet/branches --username xxxxx
--password xxxxx_
_Stdout:_
_modules/_
_Exit code: 0_
_[2015-06-11 10:09:16 - DEBUG2] Starting process: ["svn",
"--non-interactive", "ls",
"http://xxxxxx/svn/puppet/puppetlabs/puppet/environment/development/branches
http://xxxxxx/svn/puppet/puppetlabs/puppet/environment/development/branches",
"--username", "xxxxx", "--password", "xxxxx"]_
_[2015-06-11 10:09:16 - DEBUG2] Finished process:_
_Command: svn --non-interactive ls
http://xxx-xxx-xxx/svn/puppet/puppetlabs/puppet/environment/development/branches
http://xxx-xxx-xxx/svn/puppet/puppetlabs/puppet/environment/development/branches
--username xxxxx --password xxxxx_
_Stderr:_
_svn: URL
'http://xxx-xxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches
http://xxx-xxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches'
non-existent in that revision_
_Exit code: 1_
_[2015-06-11 10:09:16 - ERROR] Command exited with non-zero exit code:_
_Command: svn --non-interactive ls
http://xxx-xxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches
http://xxx-xxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches
--username xxxxx --password xxxxx_
_Stderr:_
_svn: URL
'http://xxxx-xxxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches
http://xxxx-xxxx-xxxx/svn/puppet/puppetlabs/puppet/environment/development/branches'
non-existent in that revision_
_Exit code: 1_

**Comment by adrienthebo** [comment]
A post on the mailing list indicates that this issue has been resolved, closing.
