### ISSUE TITLE
Fails to notice or fix files missing or unclean from working copies unless ref changes

### ISSUE THREAD

**Issue by dominics** [puppetlabs/r10k#428]
Say you have a simple Puppetfile utilizing Git modules like:

```
moduledir 'modules'

mod 'stdlib',
    git: 'ssh://git@github.com/puppetlabs/puppetlabs-stdlib',
    ref: 'master'
```

Then you do:

```
r10k puppetfile install
cd modules/stdlib
rm -rf * # or just edit a file or two
```

Then, r10k's behaviour is inconsistent and relies on the state of the HEAD reference of the local working copy (and ignores the actual checked-out on-disk file state):
- If the working copy is at the correct ref, none of the changed/missing files are fixed (deleted files stay missing, changed files stay changed), and r10k fails to ensure the module is at the requested version in effect (because the files in the WC do not match that ref)
- If the working copy is at an incorrect or out-of-date ref (i.e. when the ref is next updated), all of the changed/missing files are fixed, and the WC is reset to the correct ref

I describe this as inconsistent, because either r10k should refuse to act on unclean working copies, or it should always act on working copies to bring them to the exact state specified in the Puppetfile (essentially, resetting the WC). It certainly shouldn't _sometimes_ act on them.

At the very least it should give a warning if the working copy just acted on is still unclean at the end of the sync (because it has failed to fulfil its contract of 'make module X be at version Y' in anything other than HEAD git position).

**Comment by adrienthebo** [comment]
Per https://github.com/puppetlabs/r10k/issues/61#issuecomment-83047343 I don't want to support this; changing live code on a production system is inherently risky and not something I want to support. If someone wants to submit a PR that checks for a dirty tree and warns I would be willing to look at it but I make no guarantees that I'll merge it.

**Comment by dominics** [comment]
This isn't a production system, but a development environment where I'm testing changes to a module (ideally without having to do an entire push/deploy cycle). That is, the use-case is similar to a tool like puppet-librarian: just a generic bundler used to put modules in place at specified versions.

This bug doesn't involve the deploy subcommand at all. So I don't think it's correct to assume it's only a problem for live production code editing.

**Comment by adrienthebo** [comment]
Well, that's a use case that I hadn't really considered. For development purposes this is more reasonable. I can't promise that I can start working on this issue in the near future, but you do present a good case for providing this functionality.
