### ISSUE TITLE
"Error while running: #<NotImplementedError: fork is not available on this platform" on puppet 4.1, with jruby 1.7.20

### ISSUE THREAD

**Issue by dj-wasabi** [puppetlabs/r10k#434]
Hi,

I installed Puppet 4.1 on a machine.

```
rpm -Uvh http://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
yum install puppetserver
```

See version:

```
[root@vserver-140 file]# /opt/puppetlabs/bin/puppet help

< ... >
See 'puppet help <subcommand> <action>' for help on a specific subcommand action.
See 'puppet help <subcommand>' for help on a specific subcommand.
Puppet v4.1.0
```

I also installed jruby, by downloading the jrubu-bin.zip (1.7.20) from their website (http://jruby.org/download). Next I installed r10k by 'gem install r10k' and it is installed correctly. I can see the version:

```
[root@vserver-140 file]# r10k version
r10k 1.5.1
```

I have an correct r10k.yaml file:

```
[root@vserver-140 file]# cat /etc/r10k.yaml 
:cachedir: /var/cache/r10k
:sources:
  puppet:
    prefix: false
    basedir: /etc/puppetlabs/code/environments
    remote: "/etc/puppetlabs/file"

:purgedirs:
  - /etc/puppetlabs/code/environments
```

I have an Puppetfile in an git repository checked out and have some modules configured:

```
forge "http://forge.puppetlabs.com"

mod "apache",
  :git => "http://gitlab.dj-wasabi.local/puppet/apache.git"
mod "apt",
  :git => "http://gitlab.dj-wasabi.local/puppet/apt.git"
mod "mysql",
  :git => "http://gitlab.dj-wasabi.local/puppet/mysql.git"
```

But when I run an r10k, I get the following message:

```
[root@vserver-140 file]# r10k deploy environment -pv 

Error while running: #<NotImplementedError: fork is not available on this platform>
```

What am I doing wrong? Am I missing something?
Hope to hear from someone

Kind regards,
Werner

**Comment by adrienthebo** [comment]
Per https://tickets.puppetlabs.com/browse/RK-13 r10k does not run on JRuby; r10k uses fork/exec to execute external commands which the JVM does not provide. Since RK-13 is already tracking this issue I'm going to close this out in favor of the existing issue; if you have additional comments or concerns please post them on that issue. Thanks!
