### ISSUE TITLE
Error swallowed on removing unmanaged path when permissions not sufficient

### ISSUE THREAD

**Issue by brettswift** [puppetlabs/r10k#444]
We run r10k with a `procppt`  user, instead of root. 

I've noticed that with puppet 3.8,  (and the default r10k 1.5.1) it can't delete the production environment. 

``` bash
$ r10k deploy environment -pv
 ~ ~ ~ ~ ~
 ~ ~ ~ ~ ~
INFO     -> Deploying module /etc/puppetlabs/puppet/environments/master/modules/jmsbroker
INFO     -> Deploying module /etc/puppetlabs/puppet/environments/master/modules/oracle
INFO     -> Deploying module /etc/puppetlabs/puppet/environments/master/modules/ssh
INFO     -> Deploying module /etc/puppetlabs/puppet/environments/master/modules/rundeck_projects_bss
INFO     -> Removing unmanaged path /etc/puppetlabs/puppet/environments/production

[bswift@devcorepptl944 environments]$ ll
total 32
drwxr-xr-x 11 procppt procppt 4096 Jun  8 14:02 bootstrap_testing
drwxr-xr-x 11 procppt procppt 4096 Jun  8 16:00 develop
drwxr-xr-x 11 procppt procppt 4096 Jun  8 13:31 feature_pe_upgrade_3_8
drwxr-xr-x 11 procppt procppt 4096 Jun  9 07:45 feature_weblogic_bugfixes
drwxr-xr-x 11 procppt procppt 4096 Jun  8 13:32 feature_windows_redux
drwxr-xr-x 11 procppt procppt 4096 Jun  8 16:00 master
drwxr-x---  2 root    root    4096 Jun  8 13:29 production
```

Interesting bits: 
1.  the environments folder is owned by pe-puppet
2.  the production environment is owned by root. 
3. procppt is a member of the pe-puppet group.

together this tells me that procppt doesn't have permissions to delete that folder, yet we don't get an error, or warning.  I did nuke that environment in our bootstrap script but it seems to rise like a phoenix and re-appear. 

I'm guessing most people run their r10k process as root.  Maybe this isn't a supported way of running r10k - however it has worked for us since PE 3.2.

**Comment by adrienthebo** [comment]
This is a supported way of doing things, unfortunately I think there's a collision between what the Puppet Enterprise module is doing (creating the production environment) and what r10k is trying to do (randomly muck with files). Fixing the issue might require changing some classification for the puppet_enterprise module, but that can be done right away. With respect to how errors are being swallowed, could you provide the output of `r10k deploy environment --trace` when running r10k to get a backtrace from the error?

**Comment by brettswift** [comment]
To get this far I've had to change the `environments_dir_mode` of `puppet_enterprise` to 775, and add the procppt user to the pe-puppet group.   Which param in puppet_enterprise would help here? 

--trace doesn't offer anymore information, because there isn't an error. 

It's not really a huge deal, except I'd prefer if someone does put their node on the prodution environment that it fails to find it, rather than them getting a compile error.   For that to happen it has to be cleared out. 

Is there any other info that I could share that would help?

**Comment by adrienthebo** [comment]
Oh, interesting - r10k _doesn't error at all_ when a directory is unwritable and it attempts to remove it. Interesting. Yeah, this isn't great - I need to investigate more to figure out why r10k isn't failing hard in this situation.

**Comment by DavidS** [comment]
r10k also swallows other errors with the destination directory. I just was baffled for a few minutes why it didn't do anything on deploy, when it was missing the destination directory:

```
vagrant@localhost:~$ strace -e file -f r10k -v debug puppetfile install
...
[pid  1373] getcwd("/home/vagrant", 200) = 14
[pid  1373] open("/home/vagrant/Puppetfile", O_RDONLY) = 5
[pid  1373] openat(AT_FDCWD, "/home/vagrant/modules", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  1373] open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = 5
[pid  1374] +++ exited with 0 +++
+++ exited with 0 +++
```

This is r10k 2.0.2 installed as gem. This report looks similar enough that I didn't thought a new issue necessary.
