### ISSUE TITLE
[question] is it possible to add a Git Path on the Puppetfile (Windows/Linux)?

### ISSUE THREAD

**Issue by lmayorga1980** [puppetlabs/r10k#450]
Or it will use whatever is on the PATH?

**Comment by adrienthebo** [comment]
A Git path for using a specific Git binary, or something else?

**Comment by lmayorga1980** [comment]
Yeah.

**Comment by lmayorga1980** [comment]
or if will use a ENV variable like GIT_PATH? or something like that

**Comment by adrienthebo** [comment]
R10k will check ENV['PATH'] for the first Git binary found and will use that, it's not directly tunable except by changing the environment under which r10k runs. Do you have multiple versions of Git installed and need to use a certain one or something like this?

**Comment by lmayorga1980** [comment]
Was just wondering if it can be possible.

**Comment by adrienthebo** [comment]
It could be added, but I haven't seen any interest in this feature until now. If there's a really compelling case for this feature we could prioritize it; if this was just for the sake of knowledge and you don't need any more information feel free to close out this issue.

**Comment by lmayorga1980** [comment]
I was trying to install a version of git with certain extensions that was not supposed to be installed on the PATH (Hidden Git) and have a generic one that can be managed through puppet. 

The first one would more likely to test experimental features like big files etc.

**Comment by adrienthebo** [comment]
Since this issue was asking a question and we were able to answer it, I'm closing this issue out as solved. If you would like to see the ability to specify a specific Git command for r10k, please file an issue at https://tickets.puppetlabs.com/browse/RK. Thanks!
