### ISSUE TITLE
r10k puppetfile check doesn't validate everything

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/r10k#452]
I have run into two distinct issues where the r10k puppetfile check command failed to catch my syntax errors.

This is reproducible via

```
mod 'oradb', :repo => 'https://github.com/biemond/biemond-oradb'
```

Now the check command misses the problem here, while the r10k deploy environment command catches this error when it evaluates the code. 

Additionally,  if you make a mistake like:

```
mod 'puppetlabs-registry'

```

The r10k puppetfile check fails to catch the error.

Now, why would anybody makes these errors if they just paid attention to the DSL.  This is due to the fact that we have to list dependencies in multiple formats ( .fixtures.yml, librarian-puppet, beaker and r10k) so I ended up just coping and pasting and mixed up the DSL because they are all different.

**Comment by tuxmea** [comment]
another check issue:

    mod 'test',
      :git => 'git@git:project/test.git',
      :ref => :master

r10k puppetfile check will not report an error, but git fails with unexpected type (symbol instead of string)
