### ISSUE TITLE
can't disable purging when using r10k

### ISSUE THREAD

**Issue by dec-pupop** [puppetlabs/r10k#463]
I want to use r10k in a very simple way. I have a jenkins build process that checks out our main puppet project that contains the puppetfile with reference to all the modules needed and their commit reference. this works perfect, i just tar it all up and push it out as a build.

I have some python code which i want to place in the build, I would preferably use r10k to check this out and I like to have the puppetfile keep track of the entire history of the project. but the issue is when 
I check out the python it deletes other directories in the specified moduledir.

I just installed r10k using gem install r10k
and issue command r10k puppetfile install

is it possible to disable purging?

**Comment by adrienthebo** [comment]
Can you place the extra code outside of the `/modules` directory? Content that lives outside of that directory shouldn't be affected by purging.

**Comment by TheMeier** [comment]
You can also tell r10k to use a different moduledir in the Puppetfile, but then you will have to add that dir to your modulepath

**Comment by dec-pupop** [comment]
The VM I am using r10k on is a jenkins slave, so in all cases I specify a path that is not the modulepath as it is part of a build process.

for example : 
/tmp/workspace/puppet_build/

This is the setup I want :
/tmp/workspace/puppet_build/
                            puppet_main/modules/ - all puppet modules checked out here
                            python - all python code checked out here
                            other   - anything else check out on same level

so firstly I use jenkins git plugin to checkout puppet_main (this contains puppetfile, then run r10k install against the  puppetfile. when r10k checks python it deletes all other directories in that path.

right now the only thing I can do is specify r10k to check out to a temporary location and then move it to the location I want. but this feels too much like a hack.

**Comment by dec-pupop** [comment]
Any ideas?

**Comment by TheMeier** [comment]
i think the modulepath option i mentioned earlier is really worth trying here..

**Comment by dec-pupop** [comment]
so in the example i provided above : 
/tmp/workspace/puppet_build/
puppet_main/modules/ - all puppet modules checked out here
python - all python code checked out here
other - anything else check out on same level

in my puppet.conf I should add : 

/tmp/workspace/puppet_build/:/tmp/workspace/puppet_build/puppet_main/modules/:/tmp/workspace/puppet_build/python:/tmp/workspace/puppet_build/other 
as my modulepath

and this should stop purging of other directories?

**Comment by TheMeier** [comment]
i was talking about the modulepath option in the _Puppetfile_ you can use it to have r10k check out modules in another directory (which you must append to the puppet modulepath) and thus not purge the directory modules

**Comment by dec-pupop** [comment]
@TheMeier I am a little bit confused with your suggestion. I can't see modulepath as an option in the puppetfile documentaiton I only see 'moduledir ' which I am using. 

so in my case I have a puppetfile like : 
https://gist.github.com/dec-pupop/72cb44416c3165bd134c

but when i check out puppet_main then run r10k puppet_main gets purged when python and other stuff get checked out.
