### ISSUE TITLE
Allow r10k puppetfile install to specify a custom cached dir

### ISSUE THREAD

**Issue by choonming** [puppetlabs/r10k#481]
I'm currently using R10k with Jenkins as part of continuous testing. The control repos are validated and testing with the following commands:

`bundle exec r10k puppetfile check`
`bundle exec r10k puppetfile install`

This will create a cached dir in /var/lib/jenkins/.r10k which then will be share with all the other control repos and their various branches. I would like to be able to specify at least an environment variable of PUPPETFILE_CACHE_DIR which I can then point it to the Jenkins' workspace.

**Comment by adrienthebo** [comment]
If you're able to specify a normal r10k config like `r10k --config some-file.yaml puppetfile install`, would that meet your needs? In this example any deploy specific settings would be ignored so you could reuse a normal r10k config.

**Comment by choonming** [comment]
@adrienthebo it'll be great if I can specify a r10k --config r10k.yaml puppetfile install to specify a custom cachedir or a PUPPETFILE_CACHE_DIR environment variable. At present specifying --config with puppetfile subcommand will throw an error since its deprecated

**Comment by adrienthebo** [comment]
The global --config option was deprecated at one point because it was only used by `r10k deploy`; I'm planning on removing that deprecation and making it a global option again. See https://tickets.puppetlabs.com/browse/RK-120 for more information.

**Comment by choonming** [comment]
Great! I'm looking forward to the next release!

**Comment by adrienthebo** [comment]
Since RK-120 will meet your needs I'm going to close this issue out in favor of the JIRA issue; thanks for bringing this up!
