### ISSUE TITLE
[question] Deploy r10k command in a masterless configuration

### ISSUE THREAD

**Issue by lmayorga1980** [puppetlabs/r10k#486]
I already have a nice Puppetfile that brings down all my dependencies. Why r10k is asking me for another configuration file `r10k.yaml` if I don't have a puppet master. 

Basically I deploy all my nodes using `puppet apply` using Rundeck without the need of a Puppet Master why do I need another configuration file.

**Comment by adrienthebo** [comment]
How are you running r10k?

**Comment by lmayorga1980** [comment]
Workflow as follows:
1. Execute r10k puppefile install on the target system using ssh.
2. Run puppet appy with the specific directory path of the modules.

No puppet master involved but would be nice to deploy code as environments.

**Comment by adrienthebo** [comment]
If you're running `r10k puppetfile install` then you shouldn't need an `r10k.yaml`, when you run the command is r10k exiting and indicating that you do need that file? And what version of r10k are you running?

**Comment by lmayorga1980** [comment]
r10k puppetfile install works perfectly but i wanted to use r10k deploy
environment to execute different environment code on my masterless nodes.

2.0.3

**Comment by adrienthebo** [comment]
`r10k deploy` is for operating on Git repositories like https://github.com/jenkins-infra/jenkins-infra where you have multiple branches and each branch represents a separate environment, which in turn may hold a Puppetfile. If you're not using Git to hold a Puppetfile and modules and so forth, then you don't need to use `r10k deploy`; if you only have a Puppetfile then the only relevant command for you is `r10k puppetfile install`.

It seems like we're talking about two different things, am I misunderstanding your question/problem?

**Comment by lmayorga1980** [comment]
Maybe `r10k deploy` is not suitable for my needs. At this moment all my puppet modules are in independent github repositories and I am using the Puppetfile to bring down all my forge dependencies at runtime when we deploy `puppet apply` on my remote nodes.

**Comment by adrienthebo** [comment]
If you are just using a Puppetfile and are not versioning it or branching it with version control then no, `r10k deploy` isn't the right thing - just keep using `r10k puppetfile install`. If you have any more questions let me know, otherwise I'm going to close this out as solved.

**Comment by lmayorga1980** [comment]
What about if I have lets say 10 puppet internal modules and 5 forge modules and inside my internal modules I would like to have a `silver/gold` branching workflow. 

I would like to use Vagrant to set some automated testing on everything on my `silver` branch. I guess inside my `Vagrantfile` I would have something like `r10k deploy environment silver`

Maybe this is too much...

**Comment by adrienthebo** [comment]
For deploying environments there are workarounds listed in https://github.com/puppetlabs/r10k/issues/23 that allows what you're proposing; the environment is used as "hint" of sorts for switching which branch of a Git module is checked out by taking advantage of the fact that a Puppetfile is just a Ruby DSL, which allows you to use arbitrary Ruby to do all sorts of Clever Things (TM). See the comments on #23 for more information; they're not directly applicable but it's a place to start.

If you do wind up implementing some custom logic in the Puppetfile, please note the comment in https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#puppetfile about using arbitrary Ruby.

But to be clear, `r10k deploy` is meant to create multiple environments from a common source, like a Git repository or AWS S3 bucket, or something that can create multiple environments. If all you have is a Puppetfile and want to create modules from that Puppetfile, then just use `r10k puppetfile`.

**Comment by adrienthebo** [comment]
Since there hasn't been a comment on this issue in a couple of weeks I'm assuming this issue is resolved and am closing it; if you have any additional questions please comment on this issue and I can reopen it. Thanks!
