### ISSUE TITLE
/etc/puppetlabs/r10k/r10k.yaml file is not read

### ISSUE THREAD

**Issue by jorhett** [puppetlabs/r10k#488]
The docs at https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd say that /etc/puppetlabs/r10k/r10k.yaml is preferred since 1.5.0, but 2.0.3 of the gem doesn't include this change.

I'm guessing you made that change only for PE users. In my opinion it fits in line with the path changes introduced in the open source Puppet 4 and it would be great to have that in the non-PE version too.

**Comment by TheMeier** [comment]
works for me:

```
gem list r10k
*** LOCAL GEMS ***
r10k (2.0.2, 1.5.1)
```

without new config:

```
WARN     -> The r10k configuration file at /etc/r10k.yaml is deprecated.
WARN     -> Please move your r10k configuration to /etc/puppetlabs/r10k/r10k.yaml.
```

with both configs:

```
WARN     -> Both /etc/puppetlabs/r10k/r10k.yaml and /etc/r10k.yaml configuration files exist.
WARN     -> /etc/puppetlabs/r10k/r10k.yaml will be used.
```

**Comment by jorhett** [comment]
Is this code base different than what you get from "gem install r10k" from stock ruby?  Because with that version it ignores the PL prefix and does not complain about the file in /etc.

**Comment by TheMeier** [comment]
this is installed via "gem install r10k" on centos 7. actually i just did "gem update r10k" and get exactly the same result

**Comment by jorhett** [comment]
_forehead slap_

Sorry, for historic reasons I was still using r10k.conf :( Entirely sleep-headed testing error last night. These aren't the droids you're looking for. Nothing to see here except a tired writer ;)
