### ISSUE TITLE
-v / --verbose options aren't working

### ISSUE THREAD

**Issue by aheritier** [puppetlabs/r10k#49]
The help states that to have more details we can use options -v or --verbose

```
-v --verbose    Set verbosity level
```

But with these options it dies with

```
Error while running: #<RuntimeError: Unrecognized options: verbose>
```

On IRC codec found that a workaround is to use

```
r10k -v 0 puppetfile install
```

**Comment by Ancillas** [comment]
I think you have to pass in a logging value when you use --verbose.

`r10k --verbose DEBUG`

**Comment by aheritier** [comment]
It's not a problem for me in that case to just update the help message

**Comment by AnneTheAgile** [comment]
Looking at the code, it seems like the issue #32 , done 5mos ago or before this ticket was created, probably should have fixed the issue. aheritier , did you use the very latest code at that time?
If you did use the code which includes #32  then perhaps the code ;

``` ruby
      optional :v, :verbose, 'Set verbosity level' do |value, cmd|
        case value
        when true
          R10K::Logging.level = 'INFO'
        when String
          R10K::Logging.level = value
        end
      end
```

needs a change in order? Perhaps it should be "when String... else INFO"? I am not a ruby wiz and could not get my little test jig going before my clock is done for today!

**Comment by adrienthebo** [comment]
@AnneTheAgile thanks for checking up on this! I do believe that this does stem from a version older than 1.0.0, which displayed this behavior. I just did some testing around this code and it looks like it's behaving, so I'm going to close this issue out. If you're still seeing this issue please reopen this ticket and we can continue this discussion. And thanks for the issue report!

**Comment by fonk** [comment]
Hi!

Either it doesn't work again - or it's not very intuitive ;-)

[root@puppet1 ~]# r10k --verbose DEBUG deploy environment env_prod -p
WARN     -> Environment "hotfix_2.2.2" contained non-word characters, correcting name to hotfix_2_2_2
WARN     -> Environment "hotfix_3.1.2" contained non-word characters, correcting name to hotfix_3_1_2
WARN     -> Environment "release-1.1" contained non-word characters, correcting name to release_1_1
[root@puppet1 ~]# r10k --verbose ERROR deploy environment env_prod -p
WARN     -> Environment "hotfix_2.2.2" contained non-word characters, correcting name to hotfix_2_2_2
WARN     -> Environment "hotfix_3.1.2" contained non-word characters, correcting name to hotfix_3_1_2
WARN     -> Environment "release-1.1" contained non-word characters, correcting name to release_1_1
[root@puppet1 ~]# r10k --verbose error deploy environment env_prod -p
WARN     -> Environment "hotfix_2.2.2" contained non-word characters, correcting name to hotfix_2_2_2
WARN     -> Environment "hotfix_3.1.2" contained non-word characters, correcting name to hotfix_3_1_2
WARN     -> Environment "release-1.1" contained non-word characters, correcting name to release_1_1
[root@puppet1 ~]# r10k version
r10k 1.5.1
[root@puppet1 ~]# 

My goal is to suppress the emitted warnings!

**Comment by scotje** [comment]
I just tested on master and `--verbose ERROR` successfully suppressed the warnings. I suspect upgrading will resolve the issue for you. You can also set the `invalid_branches` option on a Git source to `correct` which will suppress those specific warnings: https://github.com/adrienthebo/r10k/blob/master/doc/dynamic-environments/git-environments.mkd#invalid_branches

**Comment by fonk** [comment]
Hi again!
I'm on r10k 2.4.3 now and it's still not working:

```
[root@puppet1 ~]# r10k version
r10k 2.4.3
[root@puppet1 ~]# r10k --verbose ERROR deploy environment env_prod -p
WARN     -> The r10k configuration file at /etc/r10k.yaml is deprecated.
WARN     -> Please move your r10k configuration to /etc/puppetlabs/r10k/r10k.yaml.
WARN     -> Environment "feature-restler2" contained non-word characters, correcting name to feature_restler2
WARN     -> Environment "release-8.2.2" contained non-word characters, correcting name to release_8_2_2
WARN     -> Environment "release-9" contained non-word characters, correcting name to release_9
WARN     -> Environment "release-10.1" contained non-word characters, correcting name to release_10_1
WARN     -> Environment "release-6.1" contained non-word characters, correcting name to release_6_1
WARN     -> Environment "release-7.0" contained non-word characters, correcting name to release_7_0
WARN     -> Environment "release-8.2" contained non-word characters, correcting name to release_8_2
WARN     -> Environment "release_12.6" contained non-word characters, correcting name to release_12_6
WARN     -> Environment "release_13.0" contained non-word characters, correcting name to release_13_0
WARN     -> Environment "release-1.1" contained non-word characters, correcting name to release_1_1
WARN     -> Environment "release_10.2" contained non-word characters, correcting name to release_10_2
WARN     -> Environment "release_11.7" contained non-word characters, correcting name to release_11_7
WARN     -> Environment "release_12.0" contained non-word characters, correcting name to release_12_0
WARN     -> Environment "release_13.5" contained non-word characters, correcting name to release_13_5
WARN     -> Environment "release_14.1" contained non-word characters, correcting name to release_14_1
WARN     -> Environment "release_15.1" contained non-word characters, correcting name to release_15_1
WARN     -> Environment "release_16.2" contained non-word characters, correcting name to release_16_2
WARN     -> Environment "release_17.4" contained non-word characters, correcting name to release_17_4
```

Any suggestions?

**Comment by techsuhi** [comment]
This work:
`[root@puppet1 repos]# r10k deploy environment env_prod -p --verbose ERROR`

But this one not:
`[root@puppet1 ~]# r10k --verbose ERROR deploy environment env_prod -p`
