### ISSUE TITLE
Drop in replacement for puppet-librarian?

### ISSUE THREAD

**Issue by kwolf-zz** [puppetlabs/r10k#50]
We're pretty heavily invested in Puppet Librarian right now, but I'd like to switch over to r10k and take advantages it's ability to deploy environments.

It is possible to use it as somewhat of a drop in replacement for librarian?  At leave I believe I read that somewhere.

I'm having a heck of a time getting it going.  It'd be nice if there was a little more documentation around that.  Also there's really no documentation on the config file, and options supported in it.

**Comment by Ancillas** [comment]
Hey Kevin,

I think I can help get you going.  If you can elaborate on where you're getting stuck, I might be able to improve the documentation for you.

Greg

**Comment by adrienthebo** [comment]
@kwolf sorry for the delay in responding, I've been swamped with other priorities. Do you want to use `r10k` to deploy entire environments, or just deploy modules from a Puppetfile?

**Comment by solarkennedy** [comment]
It is possible to start using r10k as a replacement for puppet-librarian at first, and then move on to environment stuff.

But the equivalent to stock libarian-puppet is:

`PUPPETFILE=Puppetfile; r10k puppetfile install`

**Comment by solarkennedy** [comment]
Oh, except for dependencies. The readme was updated to include this info in 29f9471 per #89.

**Comment by ferventcoder** [comment]
If you are installing modules sometimes off of forge, sometimes from a repository, you will also want to remove the `owner/module` and just `module`. This works in librarian but doesn't appear to work with r10k. I filed #92 on this.

**Comment by adrienthebo** [comment]
Since this issue is almost a year old (When did that happen?), the README has been updated with the current limitations of r10k, there are issues filed for the other issues mentioned, and the standalone r10k puppetfile install command is available, I'm closing this issue. If there are still concerns or questions please comment and I can reopen this issue.
