### ISSUE TITLE
A new gem really really needs to be cut

### ISSUE THREAD

**Issue by jeffb-stell** [puppetlabs/r10k#508]
2.0.3 (latest cut gem) doesn't support the local module to prevent overwrites.

It would be exceedingly keen for a new gem to be cut (even if labeled prerelease)

**Comment by adrienthebo** [comment]
We're working on it, but we've got a specific feature payload - https://tickets.puppetlabs.com/browse/RK/fixforversion/13518 has the details. We'll release 2.1.0 as soon as we're feature complete. With luck this will be in a couple of weeks, 3 weeks at the most.

**Comment by adrienthebo** [comment]
So unfortunately it's taking longer than expected, but at this point we're finishing a few last minute bugs that CI found - as soon as CI goes green we can ship. We're not implementing any other features at this point but just want to make sure that this release doesn't ship with known issues.
