### ISSUE TITLE
Keep Forge modules up to date after initial install

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/r10k#51]
As discussed in IRC I am opening this issue (a lot later than I'd planned, sorry) for discussion.

When specifying a Forge module in the Puppetfile without specifying a version, for example:

```
mod "adrien/boolean"
```

r10k initially installs the module in the latest version available on the Forge, as one would expect. But when the module gets updated on the Forge, r10k does not seem to notice or care and keeps the initially installed version. 

I would expect running `r10k deploy environment && r10k deploy module boolean` to update the adrien/boolean module to the latest version available on the Forge, just like it would a module installed from Git.

Thoughts?

**Comment by adrienthebo** [comment]
:+1:, this definitely needs to be done. I don't have this targeted in a release at this time, but it's a must-have feature.

**Comment by adrienthebo** [comment]
@antaflos I have an initial implementation for tracking forge modules. Instead of automatically tracking the latest version if no version is given, you can specify a version of `:latest` and it should install the latest module. I chose the opt-in approach so that we don't break existing behavior in a 1.x release, and I'll change that in 2.0.

The branch is at https://github.com/adrienthebo/r10k/tree/next, could you give it a shot?

**Comment by antaflos** [comment]
@adrienthebo thanks for getting back to this! I'll give it a shot in the next few days I hope.

I think the opt-in approach is definitely the way to go, even in 2.0. Think of modules like puppetlabs-postgresql and puppetlabs-puppetdb which completely changed APIs between 2.x and 3.x in a non-backwards compatible way (on line with semver). I wouldn't want to automatically update to `:latest` in cases like these without being prepared.

**Comment by jlambert121** [comment]
Would it also be easy to add the ability to just generate a log message if the module version you are using is out of date?  Right now it is a manual check of modules whenever I get around to it to see if there are updates.  I can open a new ticket as well if this doesn't easily fall into this issue.

**Comment by adrienthebo** [comment]
@jlambert121 could you add that comment to https://github.com/adrienthebo/r10k/issues/67 ? The ticket describes some desire for reporting but it would be good to have that fleshed out.

**Comment by adrienthebo** [comment]
Support for a version of `:latest` has been released in 1.2.0; if this is not working please open a new issue and we can continue this conversation there. Thanks for reporting this issue!
