### ISSUE TITLE
Puppetfile - "issue" with pull request/merge

### ISSUE THREAD

**Issue by ryayon** [puppetlabs/r10k#513]
Hi all,

  I have a concern with r10k.

  My concern is that the Puppetfile needs to be pushed to my remote repository so I can check the changes I commited.
  To do that, I need to commit changes (included to the Puppetfile) then I need to push it to the remote repository.

  Once I want to merge these changes from a specific branch to the master branch, I do NOT want to include this file. In other words, I want to merge all files except the Puppetfile file.

  For instance, on my staging environment, the Puppetfile will be configured to deploy all staging branch from every module. If I merge this file to my production branch, that means that my production environment will have also all staging branch deployed which is not what I want (indeed I want all production branch to be deployed).

  What do you suggest?

Reminder: I can't ignore the file as I have to push it to the remote repository (origin) 

Regards,
Rudy YAYON

**Comment by scotje** [comment]
It seems like a bad practice to have a long-running "staging" branch of all your modules. Having staging/production tracking different branches of all your modules is going to make deployments very unpredictable. The control repo staging environment should be directly promotable to production.

Specific module features and fixes should have branches in your module repos which you can then test in a feature branch of your control repo. The module changes should then be merged and the control repo Puppetfile updated to track the new version (if you are not tracking :latest on the module).
