### ISSUE TITLE
Feature: Parallel checkout of modules

### ISSUE THREAD

**Issue by lindenle** [puppetlabs/r10k#54]
It would be great if r10k could take a parallel job parameter to speed up checkout of modules.

**Comment by rbowlby** [comment]
+1

**Comment by adrienthebo** [comment]
I've been planning on adding this feature, it's a bit tricky to do correctly but I think this is a key feature. I'm initially targeting it at 1.2.0.

**Comment by lindenle** [comment]
http://jessewolgamott.com/blog/2013/02/07/the-one-where-i-introduce-celluloid-pmap/

Could you use that in the task runner? 
In this code (https://github.com/adrienthebo/r10k/blob/master/lib/r10k/task_runner.rb#L23):

``` javascript
  until @tasks.empty?
        current = @tasks.first
        current.task_runner = self
        begin
          current.call
        rescue Interrupt => e
          logger.error "Aborted!"
          $stderr.puts e.backtrace.join("\n").red if @trace
          @succeeded = false
          throw :abort
        rescue => e
          logger.error "Task #{current} failed while running: #{e.message}"
          $stderr.puts e.backtrace.join("\n").red if @trace

          @errors[current] = e
          @succeeded = false
        end
        @tasks.shift
```

**Comment by luisfdez** [comment]
@scotje connected to this issue, is there any roadmap to add some kind of parallelism to `r10k`. I think it's a must to scale it properly.

**Comment by lvlie** [comment]
+1

**Comment by alex-harvey-z3q** [comment]
+1

**Comment by alexharv074** [comment]
@adrienthebo  Is this on the roadmap yet?  I've just parallelised all of the Rspec builds for my customer and now I have to tell them "Um, however I can't parallelise it in production".

**Comment by lpciuser** [comment]
+1

**Comment by maxadamo** [comment]
@adrienthebo you only need to implement threaded execution for the methods. Is it really tricky to implement? Or is there something that I am overlooking, underestimating?

**Comment by theody-magill-amp** [comment]
+1

**Comment by maxadamo** [comment]
Of course,  an option to limit the number of executions should be mandatory. In my case I have 80 remote repositories.

**Comment by dominics** [comment]
@maxadamo see the discussion in https://github.com/puppetlabs/r10k/pull/417 for some of the difficulties (although the naive approach in that PR still works great for my use case, and I haven't run into any real-world parallelism issues)

**Comment by maxadamo** [comment]
OMG, we have been to Mars but we can't use threads in a script! @adrienthebo that are specious arguments (as I don't want to believe that you lack competencies to such extents). I am a python developer, but we know that things are more similar than it seems to be. 
1. We know that there is thread and there is sub-process which doesn't share memory, but even a quick research would have shown to you, that libgit2 is is "threads aware", and it says is just safe to run threads, and it also explains how to deal with error messages. Libgit2 documentation shows however a corner case with crypto libraries, depending on the OS and so far (libssh and so on). Ok, let's switch to sub-process if this is really the case. 
2. obviously, log is "one statement per method" (you write the log once, at once, per each method) and there is no risk of overlapping. Or you likely have (like @dominics have stated) a single line. 
3. I haven't seen yet that movie where caching allowed to pull 100 repos in 15 seconds. 

This feature certainly adds a layer of "complexity", and you might not be willing to deal with it. That's OK, but please, encourage people to fork your repository, or please, make a beta branch of your code, where you initially add the feature and let people experiment with it.

**Comment by adrienthebo** [comment]
The issue isn't that r10k/libgit2 isn't threadsafe; it's that concurrent r10k processes can simultaneously try to run git fetches on the same cached git repo. This condition itself produces some race conditions within git itself when the ref object is updated via multiple simultaneous pulls. When this occurs libgit2 treats this as a critical error and aborts. To prevent this r10k needs to lock the cached git repositories itself.

At this point I am no longer part of the maintainer team for r10k, and the GitHub issue tracker is active to preserve existing issues but is not used for discussion with the current maintainers. Please see https://tickets.puppet.com/browse/RK for the current issue tracker. Since I am not maintaining this repository you'll need to speak with the current maintainers for either fixing this via a community pull request or advocating that the maintainers take this task on.

**Comment by alex-harvey-z3q** [comment]
@maxadamo  You could always use Puppetlabs_spec_helper in production!

**Comment by alex-harvey-z3q** [comment]
(That's a joke by the way, but I'm seriously considering it for my own use-case.)

**Comment by maxadamo** [comment]
I finally found a fantastic solution, which is called **g10k** and with the help of "ssh control master" and detecting the branch name in the post commit and pulling only the specific branch, I passed from 300 seconds to 8 seconds:  4000% faster. 
g10k is written in Go, and uses routines (threads). It's on github. It works very well.

**Comment by jacksgt** [comment]
@maxadamo I assume you mean this repo ![xorpaul/g10k](https://github.com/xorpaul/g10k)?

**Comment by alexharv074** [comment]
I lose up to 90 seconds or so throughout each day calling r10k as a dependency of our unit tests. Would there be any way to call g10k from bundler when running unit tests that depend on r10k?

**Comment by maxadamo** [comment]
@jacksgt YES.

**Comment by maxadamo** [comment]
if you like **g10k** you may want to try my [g10k-webook](https://github.com/maxadamo/g10k-webhook) (a replacement for r10k_gitlab_webhook)

**Comment by baurmatt** [comment]
Opened https://tickets.puppetlabs.com/browse/RK-298 as this issue tracker seems to be unmonitored.

**Comment by maxadamo** [comment]
@baurmatt I encourage you to use g10k. I see no reasons to wait for something that will never come, when you have an alternative that works very well. 
https://github.com/xorpaul/g10k

**Comment by baurmatt** [comment]
@maxadamo Yeah, i've saw g10k. But i prefer to have it included in a official Puppetlabs product.

**Comment by maxadamo** [comment]
@baurmatt  I don't want to insist, but an alternative written in ruby cannot work the same way as g10k does. You won't use it only because is branded "Puppetlabs".

**Comment by baurmatt** [comment]
Problem is easily spoken:

- https://packages.ubuntu.com/search?keywords=g10k&searchon=names&suite=yakkety&section=all
- https://forge.puppet.com/modules?utf-8=%E2%9C%93&sort=rank&q=g10k

**Comment by maxadamo** [comment]
@baurmatt and? 
- You don't really need a package for a go binary. 
- since g10k is a drop-in replacement, if you really want to use the puppet class, you just rename r10k and create a symlink from g10k to r10k, and the same class will work. But do you need a class to manage the Puppetfile?

**Comment by maxadamo** [comment]
@baurmatt and?

- You don't necessarily need a package for a go binary.
- since g10k is a drop-in replacement, if you really want to use the puppet class, you just rename r10k and create a symlink from g10k to r10k, and the same class will work. But do you need a class to manage the Puppetfile?

**I mean**, it's ok to ask for an "official" tool, but on the other side, how do they want to implement threads?
With ruby is suboptimal.
Will they use Go? Then it will become a drop-in replacement for the drop-in replacement.
Wille they use jruby? I doubt it.

**Comment by alex-harvey-z3q** [comment]
Parallelisation needs to be in r10k. Ruby does threading just fine. Use Go when you have a need to handle thousands of requests per second with low latency. r10k has no such need. All it does is clone a bunch of Git repos. That kind of parallelisation could be implemented in the Bash shell, for all the difference it would make.

**Comment by maxadamo** [comment]
@alexharv074 makes sense what you are saying, but you guys understand that this request was.open 4 years ago and there is no will and the pull request has been rejected? 
That's why I miss the point of iterating the request. 
When I used r10k it needed around 5 minutes to complete. 
With g10k it takes 10 seconds for me. 
End of story. 
I need to work and I can't wait another 4 years. 
If waiting years is not a problem for you and you want it Ruby and branded by Puppetlabs, you can wait.

**Comment by alex-harvey-z3q** [comment]
I share your frustration @maxadamo and I may also use g10k. I would hope that Puppet can get their act together and fix this before too many people migrate to g10k.

**Comment by jacksgt** [comment]
I agree with @alexharv074 , parallelisation is a basic feature in today's environment and r10k should implement it.

In the mean time, we are using [postrun](https://github.com/vision-it/postrun) by @martialblog . It's a python script which does parallel checkout of all the modules (drop in replacement for r10k). Works very well, supports checking out individual modules and branches -- did I mention it's very fast? :grin:

**Comment by maxadamo** [comment]
@jacksgt use it at your risk: subprocess does not seem to be thread safe. Bear in mind that this script, in my case, would spawn 100 threads and I don't know if it's a good idea to use a library which is not intended to work with threads.

**Comment by baurmatt** [comment]
I think this got implemented by #861.

**Comment by npwalker** [comment]
I agree that it looks like #861 did this has anyone on this issue configured pool_size to more than 1 and seen benefits?

**Comment by baurmatt** [comment]
Hey @npwalker, yes we've replaced [g10k](https://github.com/xorpaul/g10k) with this. We currently running with `pool_size: 5` and really happy with this! Performance is, more or less, equal to g10k.

**Comment by npwalker** [comment]
@baurmatt awesome thanks for the information.  I'd like to bump the default pool_size to something larger than one so it's good to know that 5 works well for you.

**Comment by mwaggett** [comment]
This has been resolved by https://github.com/puppetlabs/r10k/pull/861, closing.
