### ISSUE TITLE
What is the best way to authenticate puppet master to github for multiple repos 

### ISSUE THREAD

**Issue by WeipingGuo** [puppetlabs/r10k#541]
I have set up a git control repo, and separated repos for individual modules. In the puppet master, I generated SSH key and added to control repo. Now r10k can clone the code from the control repo.

However, if I tried to add the same key to another individual repo, github does not like it since the the SSH key is already in use.

Just wonder what is the best way to authenticate the puppet master to access control and individual repos.

Thanks.
Weiping

**Comment by adreyer** [comment]
For now you have to set up a separate github user with it's own key and give it read access to your repos. If you don't need a separate key for security reasons(for example if you're only running r10k locally) you can just give r10k your key or add an r10k key to your account.

In master/2.2 you'll be able to specify a different deploy key for each user.

**Comment by WeipingGuo** [comment]
Thank you very much. I will set up a machine user for r10K.
