### ISSUE TITLE
separating hieradata from control repository

### ISSUE THREAD

**Issue by riteshnanda09** [puppetlabs/r10k#553]
Hello ,

I would like to separate my hieradata from control repository .I was able to using r10k.yaml

:cachedir: '/var/cache/r10k'
sources:
  puppet:
    remote: 'http://xxxxx/xx/control-repo.git'
    basedir: '/etc/puppet/environments'
  data:
    remote: 'http://xxxxxx/xx/control-hiera.git'
    basedir: '/etc/puppet/hieradata'

Mine  is a masterless puppet approach. 

What i want is when there are changes in hieradata ,  i would release a new version for hieradata , Change that version in Puppetfile kept in control-hiera . This would make it easy for us to revert back to old version easily.

moduledir '/etc/puppet/'
mod 'hieradata',
  :git => 'http://xxxxxx/xx/hiera-data.git'
   :ref => "1.1.0"

Then deploy the code . But using Puppetfile , it creates a module directory puts the  hieradata inside module directory. How can i aviod that.

Or if there is any other way people have tried doing it , please share it.

**Comment by riteshnanda09** [comment]
It similar what was asked in #171 . Do anyone know , do we have plans to get that.

**Comment by riteshnanda09** [comment]
Should i expect any reply , i see no reply in many questions asked by people.

**Comment by colinhunt** [comment]
:+1:

**Comment by scotje** [comment]
Good news! #602 which was merged today is the first step in enabling this type of workflow, and if you don't mind managing the ref manually in your Puppetfile, you can probably start using this pretty quickly. There will be a new gem release in relatively near future that includes this and a couple other upcoming related changes.
