### ISSUE TITLE
Support for plain tarballs

### ISSUE THREAD

**Issue by dannytrigo** [puppetlabs/r10k#567]
I would like to support downloading Puppet module tarballs from plain HTTP URLs, not just from Puppet Forge. For example:
mod "mymodule", :tarball => "http://puppetrepo/me-mymodule-1.0.13.tar.gz"

I find it strange that this doesn't already exist, when a tarball is a standard packaging format for modules (puppet module build). Is there a reason for it not already existing, or it simply needs implementing?

**Comment by Cinderhaze** [comment]
I would love for support like this, as well as potentially support for s3 based urls

**Comment by rnelson0** [comment]
@dannytrigo I am not sure it is encouraged, but doubt it would be frowned upon as an option. If it is implemented well - including tests and docs - I am pretty sure it could be merged.

My concern as a user is how much of an impact that would have on deployment times and how it would verify authenticity (esp with a high likelyhood of self-signed certs with https).

**Comment by scotje** [comment]
@dannytrigo How would you want to determine whether or not the module needed to be updated/redeployed? Theoretically it could just redeploy every time r10k deploys the environment, but that seems pretty inefficient. We could also just require a certain format to the tarball URL that includes a version number, or have a separate key to declare the desired version.

**Comment by Cinderhaze** [comment]
I know that in our usecase, having an http mirror of forge tarballs, requiring the tar file to have the version in it is enough.
