### ISSUE TITLE
[feature]: ignore branches that matches regexp

### ISSUE THREAD

**Issue by iakovgan** [puppetlabs/r10k#574]
Some times we need a temporary feature branch in environment repository, and we do not need to deploy r10k environment. It would be  nice to have a :ignore_branch_regexp: . If branch matches regexp, it would not be deployed by r10k.

**Comment by hybby** [comment]
This would be great.  Or the inverse, a setting where only branch names that match the regexp will be deployed.

**Comment by fatmcgav** [comment]
Another +1 from me aswell... I've got some 'local' dev env setups that I dont want to deploy on a production PM for example...

**Comment by martinseener** [comment]
What's the status of this? I don't think it's too hard but iam Ops not a dev, so it's hard for me to do the PR myself but i like this feature, since we constantly have 2 to 5 other branches we develop on, so the more branches r10k uses, the longer the run takes :(

**Comment by nmaludy** [comment]
+1 here

We use "feature" and "bugfix" branches all the time and it would be nice to have r10k ignore then instead of cluttering our environment directory.

**Comment by gregoirefra** [comment]
+1 We create a bunch of branch for sometime no reason because some of my team member are not used to git yet and some of those branch if not all are not really required to be deploy so being able to whitelist the one we want would be a really nice to have 😃

**Comment by nmaludy** [comment]
I've opened up a PR that fully implements this feature. If anyone is interested in helping test, the code can be found here: https://github.com/EncoreTechnologies/r10k/tree/feature/branch-filtering

**Comment by pietervogelaar** [comment]
+1

I really want this. We use feature branches to make changes to the Puppetfile in environment branches. But r10k must not try to deploy these feature branches.

**Comment by nmaludy** [comment]
@pietervogelaar good news, i have a PR available: https://github.com/puppetlabs/r10k/pull/757

Just needs to be reviewed and merged.

**Comment by adrienthebo** [comment]
PR #777 looks like it implemented this feature. I'm going to double check that this feature was implemented and if so I'll close out this issue.
