### ISSUE TITLE
Alt forge configuration ignored

### ISSUE THREAD

**Issue by terrimonster** [puppetlabs/r10k#579]
Setting an alternate forge in Puppetfile and in r10k.yaml (according to https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd) results in r10k using forgeapi.puppetlabs.com anyway.

I can use the alternate server to install modules using PMT:

$ puppet module install --module_repository=http://myforge.example.com:8080 puppetlabs-concat
Notice: Preparing to install into /home/user/.puppetlabs/etc/code/modules ...
Notice: Downloading from http://myforge.example.com:8080 ...
Notice: Installing -- do not interrupt ...
/home/user/.puppetlabs/etc/code/modules
└─┬ puppetlabs-concat (v2.1.0)
  └── puppetlabs-stdlib (v4.11.0)

Puppetfile:

forge 'http://myforge.example.com'

mod 'puppetlabs/ntp'
...

Snippet for /etc/puppetlabs/r10k/r10k.yaml: 

forge:
  baseurl: 'http://myforge.example.com'

r10k deploy environment --verbose debug2:

[2016-03-28 16:44:41 - DEBUG] Environment production is new, updating all modules
[2016-03-28 16:44:41 - INFO] Deploying module /etc/puppetlabs/code/environments/production/modules/ntp
[2016-03-28 16:44:41 - ERROR] Unable to connect to https://forgeapi.puppetlabs.com: Connection refused - connect(2) for "forgeapi.puppetlabs.com" port 443

(I disabled the proxy entirely - local forge is on same network as puppet server and is reachable by puppet server, confirmed via PMT install)

Puppet forge server installed is https://github.com/unibet/puppet-forge-server using local modules installed in a directory.

Thanks!

**Comment by scotje** [comment]
Can you confirm if the r10k.yaml configuration is: 

``` yaml
forge:
baseurl: 'http://myforge.example.com'
```

or:

``` yaml
forge:
  baseurl: 'http://myforge.example.com'
```

Indentation is important in YAML.

**Comment by terrimonster** [comment]
Indentation is confirmed. Lost in copypasta.

**Comment by scotje** [comment]
Hmmm, I so far haven't been able to replicate this, what version of r10k? Also, can you try passing the path to your config file as an option just to make sure the right config is being used?

`r10k deploy environment production -p -c /etc/puppetlabs/r10k/r10k.yaml -v debug2`

**Comment by terrimonster** [comment]
Version of r10k that ships with latest PE - 2.0.3. I also tried passing in the config file as in your example, same result.

**Comment by scotje** [comment]
The baseurl config option wasn't added until r10k 2.1.0 which should be shipping in PE starting with 2015.3.0. https://github.com/puppetlabs/r10k/blob/master/CHANGELOG.mkd#210

**Comment by terrimonster** [comment]
Well that explains it. Sorry for missing that. Thank you very much for your help!

**Comment by scotje** [comment]
No problem!
