### ISSUE TITLE
verbose flag handling sucks

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/r10k#6]
cri doesn't support multiple flags like `-vvvv`, and log4r has the reverse handling of what people would expect. Thus setting a higher verbosity would mean doing `-v 1` and a lower verbosity would be `-v 6`. This should be cleaned up.

**Comment by udoprog** [comment]
Maybe #27 helps a bit?

**Comment by adrienthebo** [comment]
Resolved by #27 and released in 1.0.0rc3. Thanks!
