### ISSUE TITLE
Make Puppetfile filename configurable

### ISSUE THREAD

**Issue by tuxmea** [puppetlabs/r10k#638]
We have a weird setup where we access modules from different git repo servers. All repo servers are in separate networks.
We want to provide a way to still work with on control repo only by specifiying different Puppetfile's on command line/r10k.yaml.
At the moment there seems no possibility to specify that r10k should make use of another file instead of Puppetfile.

**Comment by aptituz** [comment]
You mean that you are missing a way to specify a Puppetfile with the deploy action, do you? Because the puppetfile action supports a puppetfile argument and also an environment variable (PUPPETFILE).

**Comment by scotje** [comment]
This PR: https://github.com/puppetlabs/r10k/pull/687 added a per-source configuration option to r10k.yaml to specify the Puppetfile name.

**Comment by adrienthebo** [comment]
#687 implemented this feature, I'm going to presume that this issue has been resolved. @tuxmea please comment on this issue or reopen it if this isn't the case. Thanks!

**Comment by tuxmea** [comment]
@adrienthebo that is exactly what we were looking for. Many thanks.
