### ISSUE TITLE
r10k 2.4.1 puppetfile install is overwritting the local module changes

### ISSUE THREAD

**Issue by starchx** [puppetlabs/r10k#639]
Hi, we were using r10k 2.3.0 and r10k puppetfile install keeps local module changes. 

upgrading to r10k 2.4.1, this is no longer the case. 

In our development environment, we use r10k with Vagrant within the team, and this new behavior easily destroy our uncommit works. 

Any chance can introduce a flag (eg, -f) to force overwrite?

**Comment by scotje** [comment]
Hmmm, this was a change to make the `r10k deploy` action more reliable, but inadvertently is affecting `r10k puppetfile install`. I agree that there should probably be an option for `r10k puppetfile install` and the default should probably be the old behavior.

**Comment by scotje** [comment]
Created https://tickets.puppetlabs.com/browse/RK-264 in the Puppet JIRA to track this issue.

**Comment by scotje** [comment]
I think what we will do in the short term is just revert this change for the "puppetfile install" action, as outlined in this ticket: https://tickets.puppetlabs.com/browse/RK-265

**Comment by scotje** [comment]
This should be resolved when #640 is merged.

**Comment by starchx** [comment]
Awesome. Thanks Jesse.

**Comment by andersonmills** [comment]
@starchx Just checking in, did #640 in fact fix your problem?

**Comment by starchx** [comment]
@andersonmills yes, it works. :+1:
