### ISSUE TITLE
[feature] set forge.baseUrl and forge.proxy in Puppetfile

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/r10k#643]
allow setting of forge base url in puppetfile
proposed syntax:

```
forge.baseUrl: 'https://some.forgeapi'
```

**Comment by cdenneen** [comment]
Why can't use the `forge` url provided in most `Puppetfile`'s? 
Basically if Puppetfile['forge'] then override r10k.yaml[forge.baseurl]  setting the proxy is nice option but I'd like to see r10k use the default `forge` everyone still uses.

**Comment by TheMeier** [comment]
`This is currently a noop and is provided for compatibility with librarian-puppet`
