### ISSUE TITLE
r10k doesn't identify itself as the cause when exiting on exception

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/r10k#647]
## Summary

When r10k exits on exception, it doesn't identify that the program generating the error was R10K
## Expected behaviour

r10k should identify itself when exiting on error, eg:

```
Error running r10k: detailed error message...
```
## Actual behaviour

Users receive errors that are completely generic, eg:

```
Error while running: #<NoMethodError: undefined method `keys' for false:FalseClass>
```
## Steps to reproduce

See #645 
## Why this is a problem

r10k tends to get embedded in other systems or be deeply nested inside other systems/puppet code.  The current style of error messages are easy look like could come from any Ruby code on the system and make debugging systems end-to-end very difficult

**Comment by scotje** [comment]
Resolved by #694
