### ISSUE TITLE
Only deploy certain branches

### ISSUE THREAD

**Issue by rhoml** [puppetlabs/r10k#649]
We are running into this issue, we have one puppet repo that is used by almost 100 people, we'd like to be able to deploy only environment that start with certain regex pattern. I haven't seen anything on the documentation around this feature

**Comment by Vincent--** [comment]
Seems to be a duplicate of https://github.com/puppetlabs/r10k/issues/574

**Comment by rhoml** [comment]
Oh yes, i'll close it
