### ISSUE TITLE
Allow shallow clones

### ISSUE THREAD

**Issue by lindenle** [puppetlabs/r10k#65]
When checking out an environment you don't necessarily need anything but the last commit. It might make r10k faster to allow shallow clones.

**Comment by adrienthebo** [comment]
When r10k clones new git repositories, it doesn't actually clone any of the objects. All git repositories are cached, and all working directories use git object alternative directories. If you look at .git/objects/info/alternatives you should see the path to a bare repository, but there should not actually be any objects stored under .git/objects. Are you seeing something else in your environment?

**Comment by lindenle** [comment]
@adrienthebo I think maybe I was confused about how r10k works. I just noticed that in my environment checkout I have the whole history (using puppetfile mode) and thought that maybe it would be slightly faster to do shallow clones (via an option) during install.

**Comment by adrienthebo** [comment]
Could you clarify what you mean by having the whole history? Are all the objects present in the `.git` directory?

**Comment by adrienthebo** [comment]
Since this hasn't seen an update in 2 months and there aren't steps to reproduce this, I'm going to close this issue. If this is still a problem please reopen this issue and we can continue this discussion.
