### ISSUE TITLE
r10k hangs deploying a new environment from gitlab

### ISSUE THREAD

**Issue by amateo** [puppetlabs/r10k#650]
Hello,

  I'm moving my module repositories from a gitolite server to a gitlab. The problem I have is that since I move them, whenever I try to deploy a new environment r10k hangs on git commands.

  It usually hangs when it reaches the 5th gitlab module. A ps shows:

```
puppet   26459 25118  0 13:20 ?        00:00:00 git --git-dir /opt/puppetlabs/server/data/puppetserver/r10k/git@<gitlab_url>-puppet-telematica-atop.git fetch origin --prune
puppet   26462 26459  0 13:20 ?        00:00:00 ssh git@<gitlab_url> git-upload-pack 'puppet-telematica/atop.git'
```

and a strace of this process shows

```
$ sudo strace -p 26462
Process 26462 attached
read(3, 
```

  If I manually kill the git process, then r10k continues with the next module, but if fails again after a few ones. I have to repeat this process for a few modules to r10k could end deploying the environment (without the failed modules). If I run the deploy again, then it correctly deploys some of the previously failed modules, but sometimes it fails again with a few. Repeating the deploy a few times ends with the environment completely deployed.

  I have never found this behavior with our repositories in a gitolite server.

  I am running r10k 2.4.3 (I started debugging the problem with 2.3.0, but I have upgraded it too) and using the gitshell provider. I have tried to use the rugged provider, but I can't because my server is ubuntu and libssh is compiled with libgcrypt.

**Comment by SamK** [comment]
Hi,

I'm suffering from more or less the same issue: r10k is hanging and does nothing untill I "kill -9" the process. This happens once every 4-6 deployments. I'm using r10k v2.5.5 on Ubuntu 16.04 LTS (which provides Puppet 3.8.5 and Ruby 2.3.1p112).

I digged a bit and discovered that the code hangs exactly here:  https://github.com/puppetlabs/r10k/blob/2.5.5/lib/r10k/util/subprocess/runner/posix.rb#L75. R10k tries to read a pipe but nothing comes out of it.

The ps command shows something like this:
```
$ ps auxwwf
[...]
root       719  0.0  0.1  65520  6144 ?        Ss   03:57   0:00 /usr/sbin/sshd -D
root     32376  0.0  0.1  99568  6792 ?        Ss   13:36   0:00  \_ sshd: samk [priv]
samk     32401  0.0  0.0  99568  4012 ?        S    13:36   0:00  |   \_ sshd: samk@pts/1
root     32415  0.0  0.0  57108  4036 pts/1    Ss+  13:36   0:00  |       \_ sudo -S -p sudo password: /bin/bash -l -c cd .puppet-control >/dev/null && r10k deploy environment --puppetfile --verbose=notice
root     32416  0.0  0.0  12536  3128 pts/1    S+   13:36   0:00  |           \_ /bin/bash -l -c cd .puppet-control >/dev/null && r10k deploy environment --puppetfile --verbose=notice
root     32417  0.0  1.1 309608 48524 pts/1    Sl+  13:36   0:01  |               \_ /usr/bin/ruby2.3 /usr/local/bin/r10k deploy environment --puppetfile --verbose=notice
root      3832 99.1  0.8 309624 33004 ?        Rs   13:37  52:54  |                   \_ /usr/bin/ruby2.3 /usr/local/bin/r10k deploy environment --puppetfile --verbose=notice
[...]
```
The strace output of the parent shows the same as amateo.
```
$ sudo strace -p 32417
strace: Process 32417 attached
read(11,
```

The strace of the child process however shows an infinite amount of these lines scrolling very fast:
```
$ sudo strace -p 26462
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
[... going on an on...]
```

I feel like the issue is related to the ` Fcntl::FD_CLOEXEC` declaration where the pipe is declared but I can't be sure; my Ruby knowledge is very limited and I don't know where to search nor how to debug deeper.

This bug is not blocker but makes our deployment process unreliable which is annoying.

EDIT: I am not using Gitlab. The repos are downloaded from Github and a local Bitbucket server so I don't think it's related to the server.

**Comment by strickra** [comment]
We're experiencing this same issue, as well.

I can confirm, however, it's not related to the explicit Fcntl::F_SETFD (which is redundant since ruby 2.0 -- all open()s are with FD_CLOEXEC). I applied this patch to our r10k and we're still experiencing it.

```
*** var/lib/gems/2.3.0/gems/r10k-2.5.5/lib/r10k/util/subprocess/runner/posix.rb.FCS	2017-12-01 20:27:05.312749533 +0000
--- var/lib/gems/2.3.0/gems/r10k-2.5.5/lib/r10k/util/subprocess/runner/posix.rb	2017-12-01 20:27:19.764881277 +0000
*************** class R10K::Util::Subprocess::Runner::PO
*** 96,103 ****
    end
  
    def pipe
!     ::IO.pipe.tap do |pair|
!       pair.each { |p| p.fcntl(Fcntl::F_SETFD, Fcntl::FD_CLOEXEC) }
!     end
    end
  end
--- 96,101 ----
    end
  
    def pipe
!     ::IO.pipe
    end
  end
```

**Comment by cova-fe** [comment]
I'm exeperiencing the very same issue and it seems to be somewhat related to the traffic/load on network or gitlab server. Basically the issue happens more often when gitlab has more users working on it; it seems that if some slowness or delay happens, the child process is not able to recover and endlessly loops.
The protocol used by git is https://, not git://

**Comment by arnaudmorin** [comment]
I am also affected by this. I used this kind of script to kill the stuck processes

```
#!/bin/bash
# @author Arnaud Morin

# Script to kill -9 old r10k processes which are preventing the infra to upgrade by itself.
# We need this script because we are affected by those ruby bugs:
# https://github.com/puppetlabs/r10k/issues/768
# https://github.com/puppetlabs/r10k/issues/650

# First find all r10k
PIDS=$(pidof -x r10k)

for PID in $PIDS ; do
    PIDTIME=$(awk '{print int($22 / 100)}' /proc/$PID/stat)
    UPTIME=$(awk '{print int($1)}' /proc/uptime)
    DIFF=$((UPTIME - PIDTIME))

    # If process is older than an hour
    if [ $DIFF -gt 3600 ] ; then
        echo "Process $PID is alive since $DIFF seconds. Killing..."
        kill -9 $PID
    fi
done

```
