### ISSUE TITLE
Cannot use r10k puppetfile check when a git module is tracking the control repo branch

### ISSUE THREAD

**Issue by chriscowley** [puppetlabs/r10k#659]
When a module entry in my `Puppetfile` contains something like:

```
mod 'profile',
    :git => 'ssh://git@<my-gitlab>/puppet/puppet-profile.git',
    :branch => :control_branch,
    :default_branch => 'master'
```

running `r10k puppetfile check` returns an error with the message:

```
Failed to evaluate /<path-to-controlrepo>/Puppetfile
Original exception:
Cannot track control repo branch from Puppetfile in this context: environment is nil or did not provide a valid ref
```

**Comment by scotje** [comment]
Indeed, I'll see if I can add a condition to `puppetfile check` for this.

**Comment by scotje** [comment]
Created https://tickets.puppetlabs.com/browse/RK-269 to track this.

**Comment by andersonmills** [comment]
#698 has been merged. We should be publishing 2.5.2 soon with the fix.

**Comment by tuxmea** [comment]
this is solved logn ago.
can we close this issue?
