### ISSUE TITLE
selinux context issues due to "moving" files from temporary directory

### ISSUE THREAD

**Issue by TJM** [puppetlabs/r10k#661]
While using SELinux in "enforcing" mode, pulling down modules from Forge, the SELINUX context is `user_temp_t` instead of `puppet_etc_t` which makes the files unreadable to the puppet master.

**Comment by TJM** [comment]
Simple workaround is to run `restorecon -Rv /etc/puppet/environments/(env)`

**Comment by lvlie** [comment]
Code should do "mv -Z" or similar.

**Comment by TJM** [comment]
@lvlie - I would recommend using `cp` instead of `mv`, as older versions may not support `mv` (EL6). Alternatively, we could set the "temporary" directory to some place under `/etc/puppet` (`/etc/puppetlabs`), which would have the "correct" context, and would even work better to ensure that its a semi-atomic operation. The `/tmp` directory is likely on another filesystem (outside of a lab), so mv is just going to copy, then unlink anyhow.
