### ISSUE TITLE
Some level of reporting

### ISSUE THREAD

**Issue by zachfi** [puppetlabs/r10k#67]
I would like some ability to get reporting information out of r10k.
- Machine consumable (json, etc)
- How many branches were deployed
- How much time was taken in total

This should at least be able to get us something intelligent to send to graphite so that we know the state of the deploy system.

**Comment by jlambert121** [comment]
I like to keep my modules up to date, but don't want them to necessarily want to implement the #51 solution of setting module versions to 'latest'.  It would be great if the reports could include modules that were no longer current so they could be evaluated for upgrade.
