### ISSUE TITLE
r10k is unable to delete module directories ? 

### ISSUE THREAD

**Issue by It4lik** [puppetlabs/r10k#684]
Hi, 

First let me thank you for providing and maintaining this little but useful utility  :)

Just wanted to know, if :

- I specify a module in a specific environment Puppetfile
-  r10k deploy environment --puppetfile
- then I delete the module specification in the Puppetfile
- rerun r10k deploy environment --puppetfile
- module directory in Puppet Master is not deleted. Is it a normal behaviour ? Am i supposed to manually purge that repo ? 

Thank you :)
It4

**Comment by adreyer** [comment]
No, modules removed from the puppetfile in the upstream control repo should be removed from the environment.

**Comment by It4lik** [comment]
Okay found the problem, this was related to git, not r10k, i'm closing...
Sorry @adreyer and thanks for the answer
