### ISSUE TITLE
[Suggestions] Puppetfile paths and better redirection (stdout/stderr) for syntax checks

### ISSUE THREAD

**Issue by It4lik** [puppetlabs/r10k#686]
Hi, 

Thanks for this great tool :)  Simple concepts, but so much efficient. 

I came accross two details that bother me a bit, i had to build little workarounds in my shellscripts (I'm using r10k in some git hooks). 

First, r10k syntax check for Puppetfile just looks for Puppetfile in current directory, it seems impossible to **specify a custom path to a Puppetfile**... A bit odd, i have to cd in a specific directory, issue the syntax check and cd back in the first work directory (which is my work directory for the whole shellscript). 

Also, if the check succeed, r10k binary will print out **"Syntax OK"**. Yeah, cool, but why this had to be outputted **in STDERR instead of STDOUT** ? I mean, if the execution is successful (exit code 0), this should be outputted in STDOUT isn't it ? 
In my case, I wanted to log STDERR in a file and print "Syntax OK" message (instead of logging it), but the successful message actually also goes to STDERR... 

**EDIT** : Well I found that nearly everything is redirected to STDERR, even the successful synchronization (with the basic `r10k deploy environment -v` command for example). Is this done on purpose ? I think yes, 'cause "INFO" is specified, as a verbosity level but... why STDERR ? :|

Best regards, 
It4.

ps : Sorry for not taking the time to look at your code by myself, i'm a bit in the hurry at the moment, and i'm far from being a ruby expert

**Comment by scotje** [comment]
Regarding setting path options for the `puppetfile` and `moduledir`, there are currently a couple environment variables you can set right now, but we plan to switch to explicit options soon. See https://tickets.puppetlabs.com/browse/RK-160 for more information.

**Comment by It4lik** [comment]
Mmmh sorry if my english isn't good enough to be easily understood. 
But I don't think we're talking about the same thing. 

I just got a shell script written in bash that issues a r10k command to syntax-check some Puppetfiles. 
I wanted to do :
`r10k puppetfile check /path/to/puppetfile`

The expected behaviour, or at least, what _I expect,_ of this command is :
  - **IF** the exit status of r10k command is 0, **THEN** print "Syntax OK" in STDOUT
  - **IF** the exit status is different from 0, **THEN** print errors in STDERR

And using the 2> redirection, I can write in the shell output "Syntax OK" when the check is good and write the error output in a file when the command failed. 
**BUT** the "Syntax OK" message is actually also redirected to STDERR. I mean. "Syntax OK" doesn't look like an error message. Or is it just me ?

**Comment by scotje** [comment]
STDERR is really for diagnostic messages not just "errors"; data that is not appropriate to be piped into another process. (http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout)

However, I do think we could improve the output of the `puppetfile check` subcommand. To me it seems like there should be no output when the syntax is correct and a list of problems (probably on STDOUT) when there are issues.

**Comment by It4lik** [comment]
Right, little misunderstood of shell concepts on my part. 

Agree, that could be better ! 

Thanks for answers :)
