### ISSUE TITLE
Support running `generate types` after deploying an environment

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/r10k#693]
Over in this [thread](https://github.com/voxpupuli/puppet-r10k/issues/293), we were wondering if R10K itself could be enhanced to support running `generate types` after deploying an environment.

This [documentation](https://docs.puppet.com/puppet/latest/environment_isolation.html#enable-environment-isolation-with-r10k) suggests running `generate types` using the [`postrun`](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#postrun) option, but AFAICT, that is only run when deploying *all* environments; it is not suitable when just deploying a single environment.

Perhaps there are already plans to add this functionality?

Thanks.

**Comment by raphink** [comment]
`puppet generate types` can be ran with `--environment <env>` to generate for individual environments. The problem is that [`postrun` doesn't allow to pass the environment name](https://github.com/puppetlabs/r10k/issues/697)
