### ISSUE TITLE
Expose environment in postrun

### ISSUE THREAD

**Issue by jkroepke** [puppetlabs/r10k#697]
When I deploy a specific branch like `r10k deploy environment prod -pv`, it would be awsome to expose the environment prod to to postrun process, for example as environment variable, eg.

**Comment by shaheed121** [comment]
This option is much needed. For eg: To run puppet generate types for the environment we are deploying.

**Comment by elconas** [comment]
This is important as it is needed for a post provisioning "puppet generate type --environment ENV" command.

**Comment by mwaggett** [comment]
fixed by https://github.com/puppetlabs/r10k/pull/836
