### ISSUE TITLE
[feature] deploy staged content

### ISSUE THREAD

**Issue by janschumann** [puppetlabs/r10k#703]
Instead of having to commit all changes in order to deploy environments, it would be nice to be able to deploy staged content from the current working directory.

`r10k deploy --staged environment development`

If the `--staged` option is given an environment is mandatory and the content of the current working directory is copied to the environment folder.

We are using vagrant machines to test our puppet setup. The provisioner config look something like this:

```ruby
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "environments"
    puppet.environment = "production"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.options = "--verbose --debug --parser=future"
  end
```

In order to update the `environments` folder, which is used inside the machine, currently we have to commit and push changes and call `r10k deploy`. So that the workflow looks like this:

```bash
git add some/file
git commit -m "some message"
git push origin development
r10k deploy environment development
vagrant provision 
```

After implementing this feature, the workflow would look like this:

```bash
r10k deploy --staged environment development
vagrant provision 
git add some/file
git commit -m "some message"
git push origin development
```

Does this make sense to you?

**Comment by scotje** [comment]
Could something similar be accomplished by using `r10k puppetfile install` if we added an `environment` option to help it resolve control repo branch tracking and such?
