### ISSUE TITLE
Option to display log of changes being deployed

### ISSUE THREAD

**Issue by pkmiec** [puppetlabs/r10k#706]
In our environment, folks like to see what changes (something similar to `git log --oneline`) are being pulled in when running `r10k deploy environment`. Is there an option for that?

I don't know the r10k internals, so I don't know the feasibility of this request. Thanks.

**Comment by pkmiec** [comment]
I noticed, r10k executes, `git --git-dir /var/cache/r10k/<source> fetch origin --prune`,  which produces,
```
From <source>
   a283f4c..51e2e6f  master     -> master
   9f5e922..d77f0a3  stage      -> stage
```

Perhaps displaying such a summary for the environments that were updated would be very useful as well.

**Comment by scotje** [comment]
If you specify the `-v` option with a level of at least INFO (which is the default when `-v` is specified), r10k will log the new SHA for each environment deployed:

```
$ r10k deploy environment production -p -v
INFO     -> Deploying environment /tmp/environments/production
INFO     -> Environment production is now at c37f9d48a9eb42c85203994d2eedc6d2ba92e2fd
...
```

Are you looking for more detail than that?

**Comment by pkmiec** [comment]
We are currently using `-v` option, but that only tells us the resulting commit. It is nice to see where we where and potentially what has changed. I created a wrapper around r10k to display more information,
```ruby
#!/usr/bin/env ruby

ENVIRONMENTS_PATH='/etc/puppetlabs/code/environments'

def get_revs
  revs = {}

  Dir.foreach(ENVIRONMENTS_PATH) do |dir|
    next if dir.start_with?('.')

    revision = `git --git-dir \"#{File.join(ENVIRONMENTS_PATH, dir)}/.git\" rev-parse HEAD 2>&1`
    revs[dir] = revision.strip if $?.success?
  end

  revs
end

pre_revs = get_revs

output = `/opt/puppetlabs/puppet/bin/r10k deploy environment -v info #{ARGV.join(' ')} 2>&1`
$?.success? || exit($?.exitcode)

environments = []
output.each_line do |line|
  if line =~ /Deploying environment (.*)/
    environments << $1.split('/').last
  end
  puts line
end

post_revs = get_revs

puts
environments.sort.each do |environment|
  pre_rev = pre_revs[environment].to_s.rjust(40)
  post_rev = post_revs[environment].to_s.rjust(40)

  puts "#{pre_rev}...#{post_rev}: #{environment}"
end

exit unless environments.size == 1

environment = environments.first
pre_rev = pre_revs[environment]
post_rev = post_revs[environment]

exit unless pre_rev && post_rev

cmd = "git --git-dir \"#{File.join(ENVIRONMENTS_PATH, environment)}/.git\" diff --stat #{pre_rev} #{post_rev}"
puts
puts cmd
system(cmd)
```

Perhaps other would find something like this useful as well.

**Comment by SteveKeller** [comment]
This would be a great feature, if i can see that some modules has been updated.

I always use "r10k deploy environment production -pv" to update the puppet modules.

In my opinion, the best way is to implement this in the status section on the left side.

INFO     -> Deploying environment /tmp/environments/production
Something like:
UPDATED    -> Deploying environment /tmp/environments/production

The aim is, when I trigger a r10k run, that I have an overview which modules **really** has changed.
