### ISSUE TITLE
r10k not exposing git tags of the deployed control repository

### ISSUE THREAD

**Issue by Falkor** [puppetlabs/r10k#743]
Hi, 

I'm trying to extract a meaningful configuration version for each puppet runs using a custom [`config_version` script under `environment.conf`](https://docs.puppet.com/puppet/4.10/config_file_environment.html#configversion) . 
My idea was to extract from R10K deployed environments within `/etc/puppetlabs/code/environments/<environment>` the last git tag to format the version as <last-tag>-<short-sha1>. Ex: 'v0.4.19-452f953'. 
However it happens that r10k does not expose all tags within deployed environment, making the returned version inaccurate. 

**Detailed report**

Here is en extract of the script I wish to use for  [config_version](https://docs.puppet.com/puppet/4.10/config_file_environment.html#configversion)
```bash
# Usage: $0 <environment> [<environmentpath>]

CATALOG_VERSION=$(date +%s)
ENVIRONMENTPATH=$(puppet config print environmentpath)
ENVIRONMENT=$(puppet config print environment)

set_catlog_version_from_git() {
    local path=$1
    [ ! -d "${path}/.git" ] && return
    [ -z "$(which git)" ]   && return
    # collect last tag, if any
    local last_tag=$(git --git-dir ${path}/.git    describe --abbrev=0 --tags 2>/dev/null)
    # now last commit
    local head_sha=$(git --git-dir ${path}/.git    rev-parse --short HEAD     2>/dev/null)
    [ -n "${last_tag}" ] && CATALOG_VERSION="${last_tag}-${head_sha}" || CATALOG_VERSION="${head_sha}"
}
case $1 in
    -h | --help)    usage;         exit 0;;
    -V | --version) print_version; exit 0;;
    *) ENVIRONMENT=$1;;
esac
shift
[ $# -ge 1 ] && ENVIRONMENTPATH=$1

set_catlog_version_from_git "${ENVIRONMENTPATH}/${ENVIRONMENT}"
echo ${CATALOG_VERSION}
```

This works fine if I test it locally on my laptop having a copy of the control repo. 
```bash
$> cd /path/to/control-repo
$> git checkout production
$> git branch  
  devel
* production
$> cat environment.conf
[...]
config_version = 'bin/config_version.sh $environment $environmentpath'
$> git tag -l     # List the existing tags
v0.0.0
v0.1.0
v0.2.0
v0.3.0
v0.3.1
v0.4.0
v0.4.1
v0.4.10
v0.4.11
v0.4.12
v0.4.13
v0.4.14
v0.4.15
v0.4.16
v0.4.17
v0.4.18
v0.4.19
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
$> git last 
commit 452f9532e9f657f41a7b3f3fd24b135f86335105 (HEAD -> production, tag: v0.4.19, origin/production)
$> ./bin/config_version $(pwd) /      # Fake run to get the appropriate path 
v0.4.19-452f953
```

However it happens that upon r10k deployment, the full git history (expecially tags) seems not present which prevent an accurate value for the last tag (Extracted using `git --git-dir ${path}/.git    describe --abbrev=0 --tags`) to be displayed. 

```bash
# On puppet master 
$> cat /etc/puppetlabs/r10k/r10k.yaml
---
:cachedir: /opt/puppetlabs/puppet/cache/r10k
:sources:
  puppet:
    basedir: /etc/puppetlabs/code/environments
    remote: ssh://git@<gitlab>/<group>/control-repo.git
# devel and production environment are deployed under /etc/puppetlabs/code/environments/{devel, production}
$> r10k deploy environment devel -pvt
$> /etc/puppetlabs/code/environments/production/bin/config_version.sh production
v0.1.0-452f953     
$> cd  /etc/puppetlabs/code/environments/production/
$> git status
# HEAD detached at 452f953
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       .r10k-deploy.json
#       environment.conf.rpmnew
nothing added to commit but untracked files present (use "git add" to track)
$> git tag -l
v0.0.0
v0.1.0
```

As you can see the short commit hash is correct, but for some reason only 2 tags are visible within the deployed environment. 
Have I missed a specific configuration and/or Is there a way to 'force' r10k to expose all tags in the deployed directory?

**Comment by Falkor** [comment]
Any update/comment on this issue?

**Comment by ciaby** [comment]
Hi, I'm also having this issue. I tried to patch r10k and add --tags to the "git fetch" command, but it doesn't seem to update the tag list in module directory. I also tried to disable the cache in order to keep the .git directory inside the module, that didn't work either.
Any clue why is that?
