### ISSUE TITLE
Ignoring context path when using remote forge repository

### ISSUE THREAD

**Issue by jainishshah17** [puppetlabs/r10k#748]
I am using remote forge repository which has context path. I am configuring it using r10k.yaml file as shown below:
```
forge:
  baseurl: 'http://localhost:8080/artifactory/api/puppet/puppet-local'
```

It is able to fetch information about module from `http://localhost:8080/artifactory/api/puppet/puppet-local/v3/modules/puppetlabs-mysql`
also it gets release information from `http://localhost:8080/artifactory/api/puppet/puppet-local/v3/releases/puppetlabs-mysql-3.10.0`

It only ignore context path when tries to download module archive by using `http://localhost:8080/v3/files/puppetlabs-nginx-99.99.99.tar.gz` instead of `http://localhost:8080/artifactory/api/puppet/puppet-local/v3/files/puppetlabs-nginx-99.99.99.tar.gz`

**Comment by andersonmills** [comment]
@jainishshah17 We have seen this issue with puppet_forge 2.2.2. Later versions have a fix for the prefix problem. It was fixed slightly differently than your commit. See https://github.com/puppetlabs/forge-ruby/pull/41 for the fix and the tests around it.

Let me know if this can be closed.

**Comment by jainishshah17** [comment]
Tested. Thank you!!!
