### ISSUE TITLE
R10K doesn't ensure module names are valid

### ISSUE THREAD

**Issue by pzim** [puppetlabs/r10k#78]
if Puppetfile has mod references with the org in the name, it appears to run successfully, but then prunes the modules dir when finished. It would be helpful to have it check mod names for validity prior to attempting to clone their repositories.

Example Puppetfile entries to reproduce:

mod 'puppetlabs/postgresql',
  :git => "https://github.com/puppetlabs/puppetlabs-postgresql",
  :ref => '2.5.0'
mod 'puppetlabs/puppetdb',
  :git => "https://github.com/puppetlabs/puppetlabs-puppetdb",
  :ref => '2.0.0'

**Comment by blbradley** [comment]
I think this has to do with how r10k takes the name from the 'mod' statement in the Puppetfile. It works if you remove the author name from 'mod' when using a git source.

Ex:

```
mod 'postgres',
  :git => 'https://github.com/puppetlabs/puppetlabs-postgresql',
  :ref => '2.5.0'
```

Also, since r10k doesn't resolve module dependencies, you will need to define and resolve them manually in the Puppetfile.

**Comment by adrienthebo** [comment]
The original issue with pruning Git modules that included the owner in the module name should be resolved as part of GH-92. That being said we should validate the rest of the modulename and ensure it matches `[\w_]`.

**Comment by adrienthebo** [comment]
This may have been addressed in 865a0212e as part of GH-92.

**Comment by adrienthebo** [comment]
Verified in 4ac4f76 as working:

```
└> cat Puppetfile
mod 'puppetlabs/postgresql',
:git => "https://github.com/puppetlabs/puppetlabs-postgresql",
:ref => '2.5.0'
mod 'puppetlabs/puppetdb',
:git => "https://github.com/puppetlabs/puppetlabs-puppetdb",
:ref => '2.0.0'
└> bexec r10k puppetfile install
└> ls modules 
postgresql  puppetdb
```

**Comment by erinn** [comment]
Is this module name validation correct? Is there any guide on naming conventions? The regex doesn't allow for underscores or hyphens. In the https://docs.puppetlabs.com/puppet/latest/reference/modules_fundamentals.html guide it references create my_module, this wouldn't work with R10k as it is. I have been digging around trying to figure out what is what, but I figured I would ask.

**Comment by elyscape** [comment]
Not allowing for hyphens is by design, as [hyphens are not allowed in module names](https://docs.puppetlabs.com/puppet/latest/reference/modules_fundamentals.html#allowed-module-names).  As for underscores, the regex allows for underscores.  Underscores are included in `\w`.

**Comment by elyscape** [comment]
That being said, it might not hurt to replace [the regexes used](https://github.com/puppetlabs/r10k/blob/master/lib/r10k/module/base.rb#L93-L101) with variants of the one Puppet Labs offers, like so:

``` ruby

  def parse_title(title)
    if (match = title.match(/\A(\[a-z][a-z0-9_]*)\Z/))
      [nil, match[1]]
    elsif (match = title.match(/\A(\[a-z][a-z0-9_]*)[-\/](\[a-z][a-z0-9_]*)\Z/))
      [match[1], match[2]]
    else
      raise ArgumentError, "Module names must match either 'modulename' or 'owner/modulename'"
    end
  end
```
