### ISSUE TITLE
Please release 2.5.6

### ISSUE THREAD

**Issue by gdubicki** [puppetlabs/r10k#784]
We badly need a new version with RK-305 fixed (#780). Please release 2.5.6 that will include it.

Commits between 2.5.5 and current 2.5.x branch: https://github.com/puppetlabs/r10k/compare/dde99f29fd8f871db7043bd9902615a8f3dbbe71...2.5.x

**Comment by scotje** [comment]
Hello, is the recently released 2.6.0 sufficient?

**Comment by gdubicki** [comment]
Yes, thanks @scotje !
