### ISSUE TITLE
Warning about duplicate module names should take `install_path` option into consideration

### ISSUE THREAD

**Issue by c33s** [puppetlabs/r10k#785]
> WARN     -> Puppetfiles should not contain duplicate module names and will result in an error in r10k v3.x.

it would be a sad thing, if you raise an error. it would be a very good thing, if you let the user decide if its an error or not.

in my case i use the `puppetfile` to add hieradata and roles for a customer. so its quite valid to have the "module" name two times.

```
mod 'hiera_data-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'hieradata/customer'
mod 'roles-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'site/customer'
```

any chance to get this reverted to the current behavior? the new change just make it more unflexible, the warning was enough.

**Comment by scotje** [comment]
Is that `Puppetfile` snippet returning a warning or error right now? What you provided there should not be triggering a warning as far as I can tell.

**Comment by c33s** [comment]
> r10k version
> r10k 2.5.5

currently it is returning a  warning, but as i posted above it states that it will throw an error in v3.x, which i think it should not.

**Comment by scotje** [comment]
The two entries you posted resolve to module names of "company" and "***". Perhaps the original is more like this?

```ruby
mod 'namespace-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'hieradata/customer'
mod 'namespace-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'site/customer'
```

That would trigger the warning right now but it probably just needs to be updated so that dupes are only an issue if they are installing into the same directory. That's just a bug in the implementation of the check which can be resolved.

**Comment by c33s** [comment]
i fixed the code snippet from the issue description. typical copy and paste error.

yes i meant to have the same module name

```
mod 'hiera_data-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'hieradata/customer'
mod 'roles-company',
    :git => 'git@gitlab.com:...',
    :install_path => 'site/customer'
```

your rephrasing of the issue is perfect, yes if r10k considers the install path it should be ok.

**Comment by scotje** [comment]
Created https://tickets.puppetlabs.com/browse/RK-309 to track this.

**Comment by c33s** [comment]
not stale

**Comment by Magisus** [comment]
Looks like we did [flip this](https://github.com/puppetlabs/r10k/commit/0bf3f177c58b21223f6c95874ae7b41f51a8a6fc) to actually erroring in 3.0, without adding the check for `install_path`.

Agreed that it should make this distinction.

**Comment by c33s** [comment]
not stale

**Comment by Magisus** [comment]
Still a bug.

**Comment by gpiucco** [comment]
still a bug

**Comment by mwaggett** [comment]
Hi @c33s, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.
