### ISSUE TITLE
Constant checksum mismatch on Windows since 2.6.0 release

### ISSUE THREAD

**Issue by ColinHebert** [puppetlabs/r10k#787]
Since the release of 2.6.0 r10k runs consistently fail:

```
09-Dec-2017 06:56:18 | Windows-2016: ERROR         -> PuppetForge::V3::Release::ChecksumMismatch
09-Dec-2017 06:56:20 | Windows-2016: ERROR         -> PuppetForge::V3::Release::ChecksumMismatch
09-Dec-2017 06:56:21 | Windows-2016: ERROR         -> PuppetForge::V3::Release::ChecksumMismatch
09-Dec-2017 06:56:22 | Windows-2016: ERROR         -> PuppetForge::V3::Release::ChecksumMismatch
```

This is likely due to the changes brought in with "(RK-291) Add storage of local tarball md5", see cc1656d883930e36e8a29867b828bd0faed838ef.

**Comment by ColinHebert** [comment]
Pinging @andersonmills who might have an idea of what's going on/

**Comment by andersonmills** [comment]
Yep. Found the problem. Ruby's File.read on windows and unix return different values. Had to add "mode: 'rb'" to force binary reading. Whee! Will work to get a bugfix out soon.

**Comment by andersonmills** [comment]
2.6.1 has been released and fixed this bug AFAIK. Let me know if you still have problems, @ColinHebert .
