### ISSUE TITLE
Moduledir - Incorrect documentation or behaviour

### ISSUE THREAD

**Issue by yannh** [puppetlabs/r10k#788]
The documentation states that the moduledir is relative to the Puppetfile:
  https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#moduledir

> The moduledir setting specifies where modules from the Puppetfile will be installed.  This defaults to the modules directory relative to the Puppetfile

Does this mean that the following command:

`r10k puppetfile install --puppetfile test-fixtures/Puppetfile`

should install the modules in test-fixtures/modules rather than modules (current behaviour)? I am not sure what the intended behaviour should be, but there seems to be an inconsistency...

Let me know if/how I can help!

**Comment by andersonmills** [comment]
Appreciate the heads up. Will look at this... @andersonmills
