### ISSUE TITLE
Different moduledirs

### ISSUE THREAD

**Issue by amateo** [puppetlabs/r10k#79]
Hello,

 I'm migrating our legacy puppet2.7 with svn to a new 3.4 and using git instead of svn. Until now, in our svn we are using a monolithic repository where we put all the modules (ours and downloaded from forge).

  In this new git based system, I was thinking about using two different directories, on for my own modules, and the other for external (mainly forge, I guess) ones. I was also thinking about integrating all of them with git submodules until a deeper search in the web directed me not to do and using r10k instead.

  But now I have a few questions:
1. (maybe not directly related with r10k) What is the recommended approach for our own modules. I mean, is it better to develop all our own modules in the same git repository? Or is it recommended to use one repository for each module?
2. I would like to maintain forge's (and other external sources) modules installed in a different directory than ours and configure puppet modulepath with these two directories. Is it possible? Has it any sense with r10k?

**Comment by adrienthebo** [comment]
@amateo please pardon the delay in responding to this, I've been behind on responding to issues.

1) What is the recommended way of developing your modules?

Short answer: do whatever works best for your environment. :) The longer answer is, it depends and the solutions are on a spectrum.

With r10k you have two main ways of getting modules onto your master.

One way is to have all of your modules in a single repository, and modify them as you need to. This is simple, fairly easy to understand, and has fewer moving parts. Unfortunately it is difficult to pull in external module dependencies; doing so means basically vendoring them.

The other way is to have a git repository that only contains a Puppetfile at the root of the repository and have all of your modules in independent repositories. This gives you a high level of modularity and isolation, gives you more options for access control, and makes it trivial to pull in external dependencies. However this means forking and committing to switch out environments to develop on a module branch (pending #23) which is pretty heavyweight.

These two options are not mutually exclusive, and can be mixed however you want. I've found a few rough guidelines for where modules go while using r10k.

First off, if you're developing a module that's internal only or is fairly simple to begin with, start it in the main repository. If for some reason you decide to extract it you can use git-subtree to synthesize a new repository for that module, delete it from the git repository, and re-add it via the Puppetfile. You can basically swap in and out modules as you see fit, although I've generally seen the main repository as a "nursery" where modules are started and the more polished ones get extracted and published.

2) How can you separate your modules out from other modules?

With the main repository you can have multiple top level directories that contain different groups of modules, broken up as you see fit. In general I've seen people seen people split modules into `dist/` and `site/` modules where dist modules are reusable modules and site modules are site specific.

For using these different groups you can add multiple paths to `$confdir`, as you've noted. This pattern is very very common.

If you want to split up modules into different directories in a Puppetfile, that's not currently possible. Issue #24 discusses this need and it should come in a future release of r10k, but right now the best bet is to just use logical separation in your Puppetfile. You can split up Puppetfiles into smaller Puppetfiles, if that helps. At the end of the day the logical separation is really nice to break up concerns but it shouldn't be a show stopper.

Let me know if you have any additional questions or comments about r10k.

**Comment by adrienthebo** [comment]
Since this issue hasn't seen an update in a few months I'm closing it out, please comment on this issue if you have more questions and I can reopen it.
