### ISSUE TITLE
Forge based modules fails to detect missing module face

### ISSUE THREAD

**Issue by codec** [puppetlabs/r10k#8]
While bootstrapping a new master I've noticed that r10k doesn't fail when the puppet module face is not available (in my case the machine only had 2.7.11).

**Comment by adrienthebo** [comment]
Yep, I need to have better handling of feature detection. There's no good way to say "this issue is accepted," so... this issue is accepted. :)

I'm wrapping up some work on puppet-network and then I should be able to hop to this ticket shortly.

**Comment by codec** [comment]
Oh, I was just looking to fix this. Unfortunately this seems to be an issue with puppet as it returns 0 no matter what the face does. :( (see https://github.com/puppetlabs/puppet/blob/master/lib/puppet/util/command_line.rb)

**Comment by codec** [comment]
There's an upstream bug for this at http://projects.puppetlabs.com/issues/15642

**Comment by adrienthebo** [comment]
I'm going to target this bug at 1.1.0 so that 1.0.0 can get into RC.

**Comment by adrienthebo** [comment]
1.1.0 has been blocked for a while, so I'm going to untarget this issue in the naive hope that 1.1.0 will get out the door sooner, and I can come back to this then.

**Comment by rnelson0** [comment]
Adrien, bump for status, I think it can be closed.

**Comment by adrienthebo** [comment]
This is still an issue, we run entirely on hopes and dreams when calling `puppet module $command`. I think that this can be closed out when #1 is implemented but if that doesn't get done then we need to make sure that the `puppet` executable is present and the `puppet module` subcommand is functional.

**Comment by rnelson0** [comment]
@adrienthebo perhaps checking for an exit code of 1 versus 127 will be helpful. For example, puppet module vs the not-present pupppet module:

```
[rnelson0@puppet ~]$ puppet module
Error: 'module' has no default action.  See `puppet help module`.
[rnelson0@puppet ~]$ echo $?
1
[rnelson0@puppet ~]$ pupppet module
-bash: pupppet: command not found
[rnelson0@puppet ~]$ echo $?
127
```

**Comment by adrienthebo** [comment]
The original case the problems was that of this was a version of puppet that did not include the pmt, the exit code would be zero. I could just drop support for 2.7 and be done with it though.

**Comment by rnelson0** [comment]
I think that gives you three values for the return code of "puppet module":
0 - puppet module isn't there at all, and puppet returns 0 for invalid faces
1 - puppet module exists but it returns a 1 when not provided a valid
command
127 - she'll can't find puppet at all

I would think dropping 2.7 is probably okay for most but I believe this
would be backwards compatible.

On Saturday, October 18, 2014, Adrien Thebo notifications@github.com
wrote:

> The original case the problems was that of this was a version of puppet
> that did not include the pmt, the exit code would be zero. I could just
> drop support for 2.7 and be done with it though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/adrienthebo/r10k/issues/8#issuecomment-59618358.

## 

Rob Nelson
rnelson0@gmail.com

**Comment by adrienthebo** [comment]
Since #1 is closed, this issue is no longer applicable.
