### ISSUE TITLE
r10k puppetfile install - no such file or directory

### ISSUE THREAD

**Issue by sgrigorov** [puppetlabs/r10k#803]
How can I specify the location of Puppetfile? When I run e10k puppetfile install I get this error:
ERROR	 -> No such file or directory @ rb_sysopen - /root/Puppetfile

**Comment by scotje** [comment]
I believe it defaults to looking in the current directory, but you can use the `--puppetfile=<value>` flag to specify an alternate location.

**Comment by sgrigorov** [comment]
Great, Thank you!
