### ISSUE TITLE
failed to start SSH session: Unable to exchange encryption keys

### ISSUE THREAD

**Issue by skrussell** [puppetlabs/r10k#804]
So, it turns out [github have remove support for some older crypto standards on SSH](https://github.com/blog/2507-weak-cryptographic-standards-removed), and this has broken r10k deploys for us with the error message:
`failed to start SSH session: Unable to exchange encryption keys`

Ruby Gem versions:
```
[root@lonpm1 ~]# gem list | grep -E '(rugged|r10k)'
r10k (2.6.2)
rugged (0.26.0)
```

OS: `CentOS Linux release 7.4.1708 (Core)`

We've been using the rugged library for over a year now, and it was working fine until this change came in; r10k yaml config is:
```
git:
  provider: 'rugged'
  private_key: '/etc/puppetlabs/r10k/ssh/id_rsa'
```
I can't find anyway to change the cryptographic options for rugged, and I'm going to now attempt to switch to using shellgit.

I'm not sure where the problem lies (libgit limitation? Rugged limitation? r10k not providing config options?) but either way, this could cause problems for other people, so I wanted to log a bug about it here so at the very least it could be documented.

**Comment by scotje** [comment]
I believe `rugged` links against your system's `libssh2` library for SSH support, can you check that the version of that library you have installed supports the updated cipher list? If not you may need to upgrade that and then rebuild `rugged`.

**Comment by skrussell** [comment]
I have the most recent version of `libssh2` available on a default CentOS 7.4 install:
```
[russell@newpm1 ~]$ rpm -qa | grep libssh2
libssh2-devel-1.4.3-10.el7_2.1.x86_64
libssh2-1.4.3-10.el7_2.1.x86_64
```
How can I best check what ciphers it supports? I upgraded to the latest version of rugged only on Friday (in a vain hope that that would fix the problem), so it is already built against the above (latest, on CentOS) version (though I realise it's way behind the latest upstream).

**Comment by scotje** [comment]
It looks like 1.4.3 only supports what are now considered insecure key exchange algorithms: https://github.com/libssh2/libssh2/blob/libssh2-1.4.3/src/kex.c#L939-L944 (Unless CentOS has backported additional algorithms.)

libssh2 1.7.0 implements `diffie-hellman-group-exchange-sha256` which Github should support.

If you are able to install a version of `git` that can connect successfully to Github, shellgit seems like the best workaround for RHEL/Centos 7 at the moment since I don't see any packages for a newer libssh2 available. :(

**Comment by skrussell** [comment]
Thanks for your help and for investigating. I have managed to get `shellgit` working (not sure why I had trouble previously, but I did, hence I used rugged), so I will just have to stick with that for now.

Perhaps you can add a note to the docs to warn other CentOS 7 users of yet another limitation of this ageing OS.

**Comment by skrussell** [comment]
@scotje - fwiw, Ubuntu 16.04 also only has libssh2 1.5.0, so I suspect this github change could effect a number of people out there, and not just CentOS users.

**Comment by scotje** [comment]
Yeah, the change timing wasn't ideal in terms of OS support timelines. 😞  I wouldn't be terribly surprised to see newer versions of libssh2 backported eventually.

**Comment by ghost** [comment]
FYI I was able to pull the latest 1.4.3 source RPM for CentOS 7, rip out the patches, and get it to build against 1.8.0 source, at which point, it all began working.

I'm thinking of submitting a version bump request upstream, but lots of luck seeing that before CentOS 8.
