### ISSUE TITLE
Invalid filenames for windows should not prevent the usage of a module

### ISSUE THREAD

**Issue by c33s** [puppetlabs/r10k#815]
if you install `puppet/network` version `0.9.0` https://github.com/voxpupuli/puppet-network/tree/v0.9.0 on windows with `r10k puppetfile install` this leads to the following error
```
ERROR    -> No such file or directory @ rb_file_s_stat - C:/Users/user/AppData/Local/Temp/d20180529-9172-1m9q41f/puppet-network-0.9.0/puppet-network-0.9.0/spec/fixtures/provider/network_config/redhat_spec/network-scripts/ifcfg-eth0:10000000
```
this is because the module, in this case the fixture files contain invalid filenames for windows https://github.com/voxpupuli/puppet-network/issues/224 it would be a good thing to show only a warning and just skip the file. it is a sad thing that the whole module cannot be used just because of redhat fixtures, while i won't run tests and will deploy to debian :(

**Comment by binford2k** [comment]
I'm not convinced that's a good idea. In this case, ignoring the error would be relatively benign, but what if the file that didn't write properly was actually a core part of the module's code? The requested change would delay the error from deploy time (when it's relatively benign to catch and correct) to runtime, when puppet runs could fail.

**Comment by c33s** [comment]
not stale

@binford2k well simply not allowing to use a module is even more unhandy. at least it sould be allowed to use some kind of `--force`

**Comment by c33s** [comment]
not stale

**Comment by mwaggett** [comment]
@c33s We recently added an `exclude_spec` config option for skipping the deployment of module `spec` directories. Could you try setting that and then let us know whether you're able to use the offending module now? See [these docs](https://github.com/puppetlabs/r10k/blob/main/doc/dynamic-environments/configuration.mkd#exclude_spec) for more info on the setting.
