### ISSUE TITLE
Noop Setting: private_key when using shellgit

### ISSUE THREAD

**Issue by seoester** [puppetlabs/r10k#828]
There seems to be no support for the `private_key` setting (global or on a repository basis) when using the `shellgit` provider.

Do you intend to implement this feature? Otherwise, this should perhaps be noted in the documentation.

**Comment by BarnumD** [comment]
I'm stuck trying to get r10k to work via ssh keys as well.  shellgit doesn't seem to support it and rugged is broken (#843) for me.

**Comment by surajbora1** [comment]
Any way to set private_key while using shellgit provider in r10k

**Comment by seoester** [comment]
After a quick glance at the shellgit code I reckon this has not been addressed yet.

This enhancement is still of interest.

**Comment by pskopnik** [comment]
This enhancement is still of interest.

**Comment by Magisus** [comment]
So, the `shellgit` provider just uses the git CLI under the hood. It pulls ssh keys from your ssh-agent and generally is _very_ resistant to them being provided in other ways. You'll probably have to configure your system, rather than r10k, to get this to work. For some ideas on how to do this, see [this post](https://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use).

I don't think we're likely to fix this issue, but I can add something to the docs to elaborate on this.

**Comment by Magisus** [comment]
Are you looking for something more elaborate than what's already in https://github.com/puppetlabs/r10k/blob/main/doc/git/providers.mkd#ssh-configuration?

**Comment by Magisus** [comment]
Going to close this, as this is not really possible to support, given the way native git interacts with SSH. Please configure your underlying git and SSH (e.g. adding keys to the SSH agent), rather than configuring this via r10k's config file.

**Comment by seoester** [comment]
Yes, I think that's fine. I checked the documentation and the relevant information is clearly there (and has been for a while, I'm not sure where I missed it).

If this issue reappears, you could add an error/warning if the configuration is present with the shellgit provider.

https://github.com/puppetlabs/r10k/issues/828#issuecomment-902790320
> So, the shellgit provider just uses the git CLI under the hood. It pulls ssh keys from your ssh-agent and generally is very resistant to them being provided in other ways.

Implementation of this feature should be relatively straightforward through the [`GIT_SSH_COMMAND`](https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHCOMMANDcode) environment variable.
However, it is only available in Git >= 2.3.0 (e.g. not in EL7).
