### ISSUE TITLE
r10k 3.0.0 works only with cri -v 2.12.0

### ISSUE THREAD

**Issue by avillalobos** [puppetlabs/r10k#857]
I've tried to install r10k on the CI workflow, and I realized that r10k now doesn't work with newer cri libraries. It did several tests and cri -v 2.12.0 is the last version it works with r10k, from v2.13.0 onwards, there is the following error:

root@gs-puppet-master ~]# gem install cri -v 2.13.0
Fetching: cri-2.13.0.gem (100%)
Successfully installed cri-2.13.0
Parsing documentation for cri-2.13.0
Installing ri documentation for cri-2.13.0
Done installing documentation for cri after 1 seconds
1 gem installed
[root@gs-puppet-master ~]# r10k deploy environment -t
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/cri-2.13.0/lib/cri/command_dsl.rb:9:in `<class:CommandDSL>': uninitialized constant Cri::Error (NameError)
Did you mean?  IOError
               Errno
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/cri-2.13.0/lib/cri/command_dsl.rb:6:in `<module:Cri>'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/cri-2.13.0/lib/cri/command_dsl.rb:3:in `<top (required)>'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/r10k-3.0.0/lib/r10k/cli/ext/logging.rb:1:in `<top (required)>'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/r10k-3.0.0/lib/r10k/cli.rb:3:in `<top (required)>'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/r10k-3.0.0/bin/r10k:3:in `<top (required)>'
	from /opt/puppetlabs/puppet/bin/r10k:23:in `load'
	from /opt/puppetlabs/puppet/bin/r10k:23:in `<main>'
[root@gs-puppet-master ~]#

**Comment by ostavnaas** [comment]
This bug is fixed in PR https://github.com/puppetlabs/r10k/pull/854 and reported as issue in https://github.com/puppetlabs/r10k/issues/853
