### ISSUE TITLE
Replacement of librarian-puppet with local sources

### ISSUE THREAD

**Issue by ironpinguin** [puppetlabs/r10k#87]
Hi,

we use also local resources in our project for modules where are managed with the rest of the application code in a git repository.
To migrate our project to r10k we need the possibility to define modules with the :path argument.

I start to implement this in a fork. It will be nice if you use this new module from my pull request.

Ciao
Michele

**Comment by adrienthebo** [comment]
This seems like a reasonable thing to include. Could you provide some use cases/motivations for how you use this feature and examples for how others could use it?

**Comment by bvis** [comment]
Hi,

We are using this feature as well, this is very useful when you are trying to develop a puppet module and you do not want to publish it still to forge.

It is very useful to force the usage of a particular revision in the repo instead.

**Comment by walidshaari** [comment]
yes with the lack of standardising how you can have an internal forge right now (e.g. pulp vs. django-forge,..etc) that would be a good quick solution to the development use case.
