### ISSUE TITLE
Load modules from git sub folders

### ISSUE THREAD

**Issue by khobbits** [puppetlabs/r10k#883]
Excuse me if there is a way to do this, but i'm pulling my hair out.

I'm trying to pull modules from another team's control repo, using something like this:

mod 'systems',
    :git => 'git@gitlab:puppet/global.git',
    :ref => 'windows',
    :path => "site/systems/"

mod 'software',
    :git => 'git@gitlab:puppet/global.git',
    :ref => 'windows',
    :path => "site/software"

Is this just not possible, or am i missing something?

**Comment by MikaelSmith** [comment]
I don't believe that's possible. It seems like an interesting improvement. Although some better workflows seem to either be to merge between control repos or pull the other team's modules out as independent modules.

**Comment by khobbits** [comment]
I don't disagree with the statement, however I'd rather not directly merge from their repo, as we're doing things in different ways, and as I'm 'downstream', I don't get to decide how they structure their repo.

The goal here would be to just reuse some preexisting modules, that have been structured in a slightly non-standard way.

I know git doesn't allow you to check out subfolders, but if the git repository was cloned somewhere, it should be possible to copy into the module tree a subfolder.

I'm thinking it may be possible to use a single 'unusable' mod, and then use a file mod, to reference a sub folder?

**Comment by khobbits** [comment]
This would still be useful, although I've worked around it for now.
