### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by tscholz** [puppetlabs/r10k#901]
Hi there

First, many thanks for this gem.

You have added a Google Analytics callback to the docker entry point. Everyone that is using this image is calling it from now on maybe without knowing it.

I don't think that this is how it should be done. If you really need this callback, it should be opt-in and not the default. From my point of view I would prefer to see this analytics thing being removed at all.

Best,
Thomas

**Comment by stahnma** [comment]
Hey thanks for the feedback. We're trying to gather data on usage of our software, and it's anonymous. It helps our development staff focus on the things that impact larger percentages of users. Your web browser, OS, and other tools do this as well. (the page where you filed an issue does this). 

If there isn't a way to opt out currently, there will be in the relatively near future, and we'll make sure that's documented.

**Comment by nwolfe** [comment]
Hey @tscholz,

We currently have an ENV variable to disable metrics submission: `PUPPERWARE_DISABLE_ANALYTICS=true`

Set that when running the r10k container and you should see a message saying metrics are disabled.

**Comment by rb83** [comment]
Woah, luckily there's at least opt-out. We were just about to use r10k within sensitive environments. IMHO, this should be opt-in, but looking at puppetlab's homepage (marketo? newrelic? crazyegg?) I don't think this will be seen the same by puppetlabs. Thanks for the hint @nwolfe.

**Comment by tscholz** [comment]
@nwolfe Thanks for the hint. We will start to build our own image, no longer using this one. :(

I strongly disagree with the way puppet labs has chosen to  collect usage data here. There are download numbers on Github, Docker Hub and Ruby Gems available - no need to go with this spy-ware like approach. What's next, let the Gem itself call home? Do we have to inspect code of all puppet labs software in the future looking for things like that?

Currently the docker image is collecting data that indicates how often customers change there infrastructure. This is a piece of information the customers should be asked if they really want to share. We don't.

**Comment by nwolfe** [comment]
@tscholz @rb83 Thank you for the feedback!

We've made some changes which are now in the latest image:

- Metrics are now disabled by default; opt-in via setting the ENV variable
- Container output no longer includes entrypoint script messages, only r10k CLI output
- Documentation added to DockerHub (https://hub.docker.com/r/puppet/r10k)

**Comment by tscholz** [comment]
@nwolfe Many thanks for making these changes. 👍
