### ISSUE TITLE
Feature request - specify a specific source to deploy

### ISSUE THREAD

**Issue by myoung34** [puppetlabs/r10k#91]
It seems as though r10k doesn't always run. On occasion the output will be

``` bash
[R10K::Task::Deployment::DeployEnvironments - INFO] Loading environments from all sources
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment master
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[SSH] exit-status: 0
```

I have not found a rhyme or reason to this, but I"m using a jenkins job to redeploy r10k when modules change, and this pretends it did when it actually did not. If I were to re-run this same command, it would most likely do it successfully. The process should either report something that I can grep for that it won't re-deploy, or ensure it happens every time.

**Comment by adrienthebo** [comment]
Can you run r10k with `-v debug2` and provide the output of that when a run fails like this?

**Comment by myoung34** [comment]
Finally caught it in action with debug2:

```
Started by upstream project "Puppet - Hiera" build number 3
originally caused by:
 Started by user Marcus Young
Building in workspace /var/lib/jenkins/jobs/Redeploy Puppet Modules/workspace
executing script:
git_branch="origin/master"

# Validate the build param. Should be 'dev' or 'master'
# This corresponds to the r10k setup.
environment=$(echo "$git_branch" | awk '{split($0,a,"/"); print a[2]}')
if [[ "$environment" == "master" ]]; then
  /usr/bin/r10k deploy environment master -v debug2 -p
  exit 0
elif [[ "$environment" == "dev" ]]; then
  /usr/bin/r10k deploy environment dev -v debug2 -p
  exit 0
else
  echo "Invalid environment parameter [$environment] passed to build."
  echo "  Should be one of 'dev' or 'master'."
  exit 1
fi
[R10K::Git::Cache - DEBUG1] Execute: "git branch, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-hiera.git\"}"
[R10K::Git::Cache - DEBUG2] [git branch, args: {:git_dir=>"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-hiera.git"}] STDOUT:   master
[R10K::Git::Cache - DEBUG1] Execute: "git branch, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-r10k.git\"}"
[R10K::Git::Cache - DEBUG2] [git branch, args: {:git_dir=>"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-r10k.git"}] STDOUT:   dev
* master
[R10K::Task::Deployment::DeployEnvironments - INFO] Loading environments from all sources
[R10K::Git::Cache - DEBUG1] Execute: "git fetch --prune, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-hiera.git\"}"
[R10K::Git::Cache - DEBUG1] Execute: "git branch, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-hiera.git\"}"
[R10K::Git::Cache - DEBUG2] [git branch, args: {:git_dir=>"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-hiera.git"}] STDOUT:   master
[R10K::Git::Cache - DEBUG1] Execute: "git fetch --prune, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-r10k.git\"}"
[R10K::Git::Cache - DEBUG1] Execute: "git branch, args: {:git_dir=>\"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-r10k.git\"}"
[R10K::Git::Cache - DEBUG2] [git branch, args: {:git_dir=>"/var/cache/r10k/ssh---git@stash.server.com-7999-pup-r10k.git"}] STDOUT:   dev
* master
[R10K::Task::Deployment::DeployEnvironments - WARN] Environment master not found in any source
[R10K::Task::Deployment::PurgeEnvironments - DEBUG] No stale environments in /etc/puppet/hiera
[R10K::Task::Deployment::PurgeEnvironments - DEBUG] No stale environments in /etc/puppet/environments
[SSH] exit-status: 0
Finished: SUCCESS
```

Since this is Jenkins, i could possibly make it search STDOUT for "no stale environments", however it would be nice to give it a force flag that works regardless, or possibly Error instead of Warn on `[R10K::Task::Deployment::DeployEnvironments - WARN] Environment master not found in any source` so that I could sleep 30 and redo the job since I know something changed. What's odd is that it reported no stale environments. This is a downstream job. I made a change to hiera, and it kicked this job off. To deploy my hiera yaml's, I **NEED** r10k to run even though the environments didn't change, Hiera did.

**Comment by adrienthebo** [comment]
Oh, so this is specifically the case where you're deploying a single environment, and if that environment doesn't exist then r10k fails silently when it should be returning a non-zero exit code. Does that sound right?

**Comment by myoung34** [comment]
Yea, although I seem to have found another scenario lately. Given this config:

```
# The location to use for storing cached Git repos
:cachedir: '/var/cache/r10k'

# A list of git repositories to create
:sources:
  # This will clone the git repository and instantiate an environment per
  # branch in /etc/puppet/environments
  :mycode:
    remote: 'git@github.com:my-org/org-shared-modules'
    basedir: '/etc/puppet/environments'
  :hiera:
    remote: 'git@github.com:my-org/org-hiera'
    basedir: '/etc/puppet/hiera'
```

I need a way to specify deploying hiera environments only. I don't see a way in the current r10k binary

**Comment by AlexRRR** [comment]
@myoung34 I would very interested to know if this has been solved:

> I need a way to specify deploying hiera environments only. I don't see a way in the current r10k binary

Does https://github.com/puppetlabs/r10k/issues/118 solve that? I am confused. I know I can deploy environments by name, but what about hiera data? If so, it needs to be documented. Thank you!

**Comment by adrienthebo** [comment]
@AlexRRR I haven't heard much interest in this issue since February of 2014 so haven't devoted to development resources towards this; if there's more interest now then I might be able to make it more of a priority issue.

**Comment by adrienthebo** [comment]
In addition, if you're treating hiera data as another source, you can update the hiera data "environments" by name; it's not as broad of a brush as updating things by sources but it'll get you closer to the desired use case.

**Comment by AlexRRR** [comment]
@adrienthebo Thanks, our use case is simple we have multiple puppet modules, when we make changes to one after a successful CI build it will trigger an R10k 'deploy module' via MCollective which is relatively fast. But for Hiera changes I have to do a full synchronize which takes ages (if ages were about a minute).

> if you're treating hiera data as another source, you can update the hiera data "environments" by name

You mean instead of using `hiera:` as a source in r10k.yaml just have the hiera data repo inside the Puppetfile?

**Comment by AlexRRR** [comment]
Got it to work as you suggested. I agree there is no need for sources deployment. Thanks for you help!
