### ISSUE TITLE
Duplicated setting cachedir

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/r10k#916]
Should this setting be duplicated like this? If so, we should have a comment explaining why.

https://github.com/puppetlabs/r10k/blob/1da5e992dee10b94c23360613a474a2cae215b26/lib/r10k/initializers.rb#L33-L34

**Comment by dhollinger** [comment]
May have been fixed in [RK-360](https://tickets.puppetlabs.com/projects/RK/issues/RK-360?filter=allissues)

**Comment by Magisus** [comment]
It's not duplicated: it's used to configure two different aspects of the system. It means that r10k will use the same cache location for all modules it fetches, whether it fetches them from Git or from the Forge. We could still add a comment 🤷‍♀
