### ISSUE TITLE
Bug: Digest::Base cannot be directly inherited in Ruby

### ISSUE THREAD

**Issue by baurmatt** [puppetlabs/r10k#979]
## Describe the Bug
r10k sometimes throws an `Digest::Base cannot be directly inherited in Ruby` error. This leads to module not being deployed and therefore other errors (failing CI pipelines in our case).

This showed up after we enabled the `pool_size` feature. (Currently using `pool_size: 10`)

## Expected Behavior
r10k doesn't fail and successfully deploys all modules.

## Steps to Reproduce
Currently I can't reliably reproduce this. We had 6 (out of probably thousands) jobs failing with this error within ~24h.

## Environment
 - Ruby: 2.5.3
 - r10k Version: 3.3.1
 - Platform: Debian 9.8 running in a docker container onto of a OpenStack VM.

**Comment by baurmatt** [comment]
Running `r10k` with `--trace` surprisingly fast returned this stack trace:

```
ERROR	 -> Digest::Base cannot be directly inherited in Ruby
/usr/local/lib/ruby/2.5.0/digest.rb:35:in `new'
/usr/local/lib/ruby/2.5.0/digest.rb:35:in `file'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/forge/module_release.rb:119:in `verify'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/forge/module_release.rb:90:in `install'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/module/forge.rb:149:in `install'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/module/forge.rb:48:in `sync'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/action/puppetfile/install.rb:36:in `visit_module'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/action/visitor.rb:24:in `visit'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/module/base.rb:86:in `accept'
/usr/local/bundle/gems/r10k-3.3.1/lib/r10k/puppetfile.rb:217:in `block in visitor_thread'
```

**Comment by baurmatt** [comment]
Looks like https://github.com/aerospike/aerospike-client-ruby/issues/45 had the same problem. Accessing a digest by `Digest::SHA256` isn't thread-safe. `Digest(:SHA256)` is the way to go.

Going to open up a PR for this.

**Comment by tskirvin** [comment]
I'm seeing this consistently now, and it's causing r10k runs to fail.  Fully up-to-date r10k on RHEL 8, puppetserver-7.17.1-1.el8.noarch.

**Comment by tskirvin** [comment]
Same deal when I try it on puppetserver-8.6.1-1.  And I should note that it's not happening *every* run, but if I run it against a few dozen branches, I'm seeing errors about 5-6 times.

Note that I'm *not* seeing this error on my puppetserver-7.9.1-1.el8.noarch hosts.
