### ISSUE TITLE
Task Deploy - Unhandled options [:reg] specified for R10K::Module::Git

### ISSUE THREAD

**Issue by pjfoley** [puppetlabs/r10k#98]
Hi,

There appears to be an issue with the current (1.2.0) version of r10k:

``` shell
10:53 - root@dna: tmp/puppet-test
$ r10k version
1.2.0

10:53 - root@dna: tmp/puppet-test
$ r10k deploy environment -p -c r10k.yaml -v
[R10K::Task::Deployment::DeployEnvironments - INFO] Loading environments from all sources
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment production
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Environment::Deploy:0x000000017d31a0> failed while running: Unhandled options [:reg] specified for R10K::Module::Git
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment production
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Puppetfile::Sync:0x000000015aa810> failed while running: Unhandled options [:reg] specified for R10K::Module::Git
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment production
[R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /root/tmp/puppet-test/etc/puppet/environments
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /root/tmp/puppet-test/etc/puppet/hieradata
```

It appears that somewhere an option for git repositories is set but the code is not there to handle it?

Just incase it was a gem dependancy issue I built a clean debian install on a VM and then did a gem install r10k.  It has the same issue, the older version of r10k (1.4.0) works with the same r10k.yaml file.

Any thoughts on what I can do to resolve this?

Peter

**Comment by adrienthebo** [comment]
I think that what you're seeing is stricter validation. In r10k 1.x, the options set on modules was not validated, and if you passed an invalid option it would be silently ignored. In r10k 1.2.0 an error will be raised if you give an invalid option.

Perhaps instead of `:reg`, you meant `:ref`?

**Comment by pjfoley** [comment]
_face palm_.

Sorry for the noise that was exactly what it was.  Looking at the error message given I can better understand what it means.

Not sure if you want to make the error message bigger, but could I suggest adding in brackets something like "(check to see if you have made a typo)".

If not happy to leave it as is.
