### ISSUE TITLE
postrun after deploying a module

### ISSUE THREAD

**Issue by amateo** [puppetlabs/r10k#982]
There is a `postrun` option that enables running a script after deploying an environment. But this script is not run after deploying a module (not an environment).
I think it would be useful to be able to run this script after deploying a module.

**Comment by chrisongthb** [comment]
We need this feature, too. Any news here?

**Comment by packetcafe** [comment]
+1  for this feature.. it would be really handy for the postrun to run for all deployment include a single module.

**Comment by chrisongthb** [comment]
This issue is still important to us.

**Comment by kendall-moore** [comment]
+1 for this feature. Deploying a module is still a deployment, so there's no reason postrun shouldn't be triggered.

**Comment by packetcafe** [comment]
+1  I'm also waiting for the feature, it not stable at all!.

**Comment by Magisus** [comment]
Agreed, this should be fixed. Related jira ticket: https://tickets.puppetlabs.com/browse/RK-369

**Comment by Magisus** [comment]
The `postrun` command for environments will read a variable `$modifiedenvs` and [sub in](https://github.com/puppetlabs/r10k/blob/ded1045f29f99a624c19eae25d96217cd0dee179/lib/r10k/action/deploy/environment.rb#L126-L131) the environments being deployed. We probably want to respect this for `deploy module` too, but should it only supply environments that were both requested _and_ actually had the module in question? Or all requested envs, regardless of whether they were actually updated?

**Comment by alexjfisher** [comment]
Preferably, just the environments that were updated?

**Comment by Magisus** [comment]
Cool, that makes sense to me too.

**Comment by Magisus** [comment]
If it turns out that no environments were actually updated (e.g. because none of the requested ones contained the module), do we still want to run the command at all? Or only if it does not include `$modifiedenvs`?

**Comment by Magisus** [comment]
I have a PR up that only runs the command if any envs actually synced modules, and populates `$modifiedenvs` with the changed environments, see https://github.com/puppetlabs/r10k/pull/1190. Still working on tests but would appreciate thoughts on the approach and functionality.

**Comment by Magisus** [comment]
This has been merged, and will be released soon (in the next month), or we could do sooner if there's interest, please let us know. Also if anyone has any issues with it or needs any tweaks to the functionality.
