### ISSUE TITLE
Don't run git fetch origin for every source when environment is specified

### ISSUE THREAD

**Issue by JvGinkel** [puppetlabs/r10k#995]
## Describe the Bug
When you provide a environment in the r10k command I would suspect that only this environment would be processed. But for every source configured it will also run a
```
git --git-dir /var/cache/r10k/git@gitlab.internal.lan-mybranch-puppet-control-repo.git fetch origin --prune
```
When you have a lot of environments(sources) configured this will add a lot of time to the r10k run.

## Expected Behavior
I would expect that the `fetch origin --prune` command would only run for the specified environment at the r10k command. There is no use to update the others now as we are not going to deploy those environments.

## Steps to Reproduce
1. Create a r10k.yaml with a lot of sources
2. Start a r10k deploy with an environment specified like `/opt/puppetlabs/puppet/bin/r10k deploy environment mybranch -pv 1`
3. Watch output and see a `fetch origin --prune` command for every source specified in the r10k.yaml

## Environment
 - Version r10k 3.3.1
 - Platform Debian GNU/Linux 9.9 (stretch)

**Comment by isqo** [comment]
I think that r10k has to fetch the sources into its local cache to know the branches that corresponds to the environments and hence compare them to the specified environment.
Maybe this is super naive, but shouldn't r10k call "git ls-remote sources" and compare the refs/heads returned to the specified environment before preloading the cache ?

**Comment by JvGinkel** [comment]
Don't do that github-actions bot :) 

I still believe that when you provide an environment that you want to deploy there is no use in running a `fetch origin --prune` command for every environment(source) specified in the r10k config file. 

It's fine when you don't specify anything then just loop true all environments and cleanup stuff and deploy everything.

**Comment by Magisus** [comment]
There is some other work we're doing around being smarter and more flexible about how, when, and what we prune and validate. If we had something like https://github.com/puppetlabs/r10k/issues/744 (which we are intending to build), it starts making more sense to remove some of the aggressive purging we do that make regular single-env deploys slow.
